package net.snake.dao.languageflash;

import java.util.List;

import net.snake.dao.languageflash.LanguageFlash;
import net.snake.dao.languageflash.LanguageFlashExample;

public interface LanguageFlashDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int countByExample(LanguageFlashExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int deleteByExample(LanguageFlashExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	void insert(LanguageFlash record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	void insertSelective(LanguageFlash record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	List selectByExample(LanguageFlashExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	LanguageFlash selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int updateByExampleSelective(LanguageFlash record, LanguageFlashExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int updateByExample(LanguageFlash record, LanguageFlashExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int updateByPrimaryKeySelective(LanguageFlash record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	int updateByPrimaryKey(LanguageFlash record);
}
