package net.snake.dao.language;

import java.util.List;

import net.snake.dao.language.Language;
import net.snake.dao.language.LanguageExample;

public interface LanguageDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int countByExample(LanguageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int deleteByExample(LanguageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	void insert(Language record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	void insertSelective(Language record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	List selectByExample(LanguageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	Language selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int updateByExampleSelective(Language record, LanguageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int updateByExample(Language record, LanguageExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int updateByPrimaryKeySelective(Language record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	int updateByPrimaryKey(Language record);
}
