package net.snake.dao.languageflash;

import java.util.List;

import net.snake.dao.languageflash.LanguageFlash;
import net.snake.dao.languageflash.LanguageFlashExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LanguageFlashDAOImpl extends SqlMapClientDaoSupport implements LanguageFlashDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public LanguageFlashDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int countByExample(LanguageFlashExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_language_flash.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int deleteByExample(LanguageFlashExample example) {
		int rows = getSqlMapClientTemplate().delete("t_language_flash.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		LanguageFlash key = new LanguageFlash();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("t_language_flash.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public void insert(LanguageFlash record) {
		getSqlMapClientTemplate().insert("t_language_flash.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public void insertSelective(LanguageFlash record) {
		getSqlMapClientTemplate().insert("t_language_flash.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public List selectByExample(LanguageFlashExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_language_flash.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public LanguageFlash selectByPrimaryKey(Integer id) {
		LanguageFlash key = new LanguageFlash();
		key.setId(id);
		LanguageFlash record = (LanguageFlash) getSqlMapClientTemplate().queryForObject(
				"t_language_flash.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int updateByExampleSelective(LanguageFlash record, LanguageFlashExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_language_flash.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int updateByExample(LanguageFlash record, LanguageFlashExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_language_flash.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int updateByPrimaryKeySelective(LanguageFlash record) {
		int rows = getSqlMapClientTemplate().update(
				"t_language_flash.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	public int updateByPrimaryKey(LanguageFlash record) {
		int rows = getSqlMapClientTemplate().update("t_language_flash.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_language_flash
	 * @ibatorgenerated  Tue May 24 13:24:34 CST 2011
	 */
	private static class UpdateByExampleParms extends LanguageFlashExample {
		private Object record;
		public UpdateByExampleParms(Object record, LanguageFlashExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
