package net.snake.dao.horsemodel;

import java.util.List;

import net.snake.dao.horsemodel.HorseModel;
import net.snake.dao.horsemodel.HorseModelExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HorseModelDAOImpl extends SqlMapClientDaoSupport implements HorseModelDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public HorseModelDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int countByExample(HorseModelExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_horse_model.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int deleteByExample(HorseModelExample example) {
		int rows = getSqlMapClientTemplate().delete("t_horse_model.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		HorseModel key = new HorseModel();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_horse_model.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public void insert(HorseModel record) {
		getSqlMapClientTemplate().insert("t_horse_model.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public void insertSelective(HorseModel record) {
		getSqlMapClientTemplate().insert("t_horse_model.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public List selectByExample(HorseModelExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_horse_model.queryall",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public HorseModel selectByPrimaryKey(Integer id) {
		HorseModel key = new HorseModel();
		key.setId(id);
		HorseModel record = (HorseModel) getSqlMapClientTemplate().queryForObject(
				"t_horse_model.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int updateByExampleSelective(HorseModel record, HorseModelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_horse_model.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int updateByExample(HorseModel record, HorseModelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_horse_model.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int updateByPrimaryKeySelective(HorseModel record) {
		int rows = getSqlMapClientTemplate().update(
				"t_horse_model.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	public int updateByPrimaryKey(HorseModel record) {
		int rows = getSqlMapClientTemplate()
				.update("t_horse_model.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_horse_model
	 * @ibatorgenerated  Fri May 06 18:15:47 CST 2011
	 */
	private static class UpdateByExampleParms extends HorseModelExample {
		private Object record;
		public UpdateByExampleParms(Object record, HorseModelExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
