package net.snake.dao.skilleffect;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SkillEffectExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public SkillEffectExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	protected SkillEffectExample(SkillEffectExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}
		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}
		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}
		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}
		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}
		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}
		public Criteria andIdIsNull() {
			addCriterion("f_id is null");
			return this;
		}
		public Criteria andIdIsNotNull() {
			addCriterion("f_id is not null");
			return this;
		}
		public Criteria andIdEqualTo(Integer value) {
			addCriterion("f_id =", value, "id");
			return this;
		}
		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("f_id <>", value, "id");
			return this;
		}
		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("f_id >", value, "id");
			return this;
		}
		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_id >=", value, "id");
			return this;
		}
		public Criteria andIdLessThan(Integer value) {
			addCriterion("f_id <", value, "id");
			return this;
		}
		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_id <=", value, "id");
			return this;
		}
		public Criteria andIdIn(List values) {
			addCriterion("f_id in", values, "id");
			return this;
		}
		public Criteria andIdNotIn(List values) {
			addCriterion("f_id not in", values, "id");
			return this;
		}
		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("f_id between", value1, value2, "id");
			return this;
		}
		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_id not between", value1, value2, "id");
			return this;
		}
		public Criteria andNameIsNull() {
			addCriterion("f_name is null");
			return this;
		}
		public Criteria andNameIsNotNull() {
			addCriterion("f_name is not null");
			return this;
		}
		public Criteria andNameEqualTo(String value) {
			addCriterion("f_name =", value, "name");
			return this;
		}
		public Criteria andNameNotEqualTo(String value) {
			addCriterion("f_name <>", value, "name");
			return this;
		}
		public Criteria andNameGreaterThan(String value) {
			addCriterion("f_name >", value, "name");
			return this;
		}
		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("f_name >=", value, "name");
			return this;
		}
		public Criteria andNameLessThan(String value) {
			addCriterion("f_name <", value, "name");
			return this;
		}
		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("f_name <=", value, "name");
			return this;
		}
		public Criteria andNameLike(String value) {
			addCriterion("f_name like", value, "name");
			return this;
		}
		public Criteria andNameNotLike(String value) {
			addCriterion("f_name not like", value, "name");
			return this;
		}
		public Criteria andNameIn(List values) {
			addCriterion("f_name in", values, "name");
			return this;
		}
		public Criteria andNameNotIn(List values) {
			addCriterion("f_name not in", values, "name");
			return this;
		}
		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("f_name between", value1, value2, "name");
			return this;
		}
		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("f_name not between", value1, value2, "name");
			return this;
		}
		public Criteria andUserScopeIsNull() {
			addCriterion("f_user_scope is null");
			return this;
		}
		public Criteria andUserScopeIsNotNull() {
			addCriterion("f_user_scope is not null");
			return this;
		}
		public Criteria andUserScopeEqualTo(Byte value) {
			addCriterion("f_user_scope =", value, "userScope");
			return this;
		}
		public Criteria andUserScopeNotEqualTo(Byte value) {
			addCriterion("f_user_scope <>", value, "userScope");
			return this;
		}
		public Criteria andUserScopeGreaterThan(Byte value) {
			addCriterion("f_user_scope >", value, "userScope");
			return this;
		}
		public Criteria andUserScopeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_user_scope >=", value, "userScope");
			return this;
		}
		public Criteria andUserScopeLessThan(Byte value) {
			addCriterion("f_user_scope <", value, "userScope");
			return this;
		}
		public Criteria andUserScopeLessThanOrEqualTo(Byte value) {
			addCriterion("f_user_scope <=", value, "userScope");
			return this;
		}
		public Criteria andUserScopeIn(List values) {
			addCriterion("f_user_scope in", values, "userScope");
			return this;
		}
		public Criteria andUserScopeNotIn(List values) {
			addCriterion("f_user_scope not in", values, "userScope");
			return this;
		}
		public Criteria andUserScopeBetween(Byte value1, Byte value2) {
			addCriterion("f_user_scope between", value1, value2, "userScope");
			return this;
		}
		public Criteria andUserScopeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_user_scope not between", value1, value2, "userScope");
			return this;
		}
		public Criteria andScopeRadiusIsNull() {
			addCriterion("f_scope_radius is null");
			return this;
		}
		public Criteria andScopeRadiusIsNotNull() {
			addCriterion("f_scope_radius is not null");
			return this;
		}
		public Criteria andScopeRadiusEqualTo(Integer value) {
			addCriterion("f_scope_radius =", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusNotEqualTo(Integer value) {
			addCriterion("f_scope_radius <>", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusGreaterThan(Integer value) {
			addCriterion("f_scope_radius >", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_scope_radius >=", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusLessThan(Integer value) {
			addCriterion("f_scope_radius <", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusLessThanOrEqualTo(Integer value) {
			addCriterion("f_scope_radius <=", value, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusIn(List values) {
			addCriterion("f_scope_radius in", values, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusNotIn(List values) {
			addCriterion("f_scope_radius not in", values, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusBetween(Integer value1, Integer value2) {
			addCriterion("f_scope_radius between", value1, value2, "scopeRadius");
			return this;
		}
		public Criteria andScopeRadiusNotBetween(Integer value1, Integer value2) {
			addCriterion("f_scope_radius not between", value1, value2, "scopeRadius");
			return this;
		}
		public Criteria andUseLimitIsNull() {
			addCriterion("f_use_limit is null");
			return this;
		}
		public Criteria andUseLimitIsNotNull() {
			addCriterion("f_use_limit is not null");
			return this;
		}
		public Criteria andUseLimitEqualTo(Integer value) {
			addCriterion("f_use_limit =", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitNotEqualTo(Integer value) {
			addCriterion("f_use_limit <>", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitGreaterThan(Integer value) {
			addCriterion("f_use_limit >", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_use_limit >=", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitLessThan(Integer value) {
			addCriterion("f_use_limit <", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitLessThanOrEqualTo(Integer value) {
			addCriterion("f_use_limit <=", value, "useLimit");
			return this;
		}
		public Criteria andUseLimitIn(List values) {
			addCriterion("f_use_limit in", values, "useLimit");
			return this;
		}
		public Criteria andUseLimitNotIn(List values) {
			addCriterion("f_use_limit not in", values, "useLimit");
			return this;
		}
		public Criteria andUseLimitBetween(Integer value1, Integer value2) {
			addCriterion("f_use_limit between", value1, value2, "useLimit");
			return this;
		}
		public Criteria andUseLimitNotBetween(Integer value1, Integer value2) {
			addCriterion("f_use_limit not between", value1, value2, "useLimit");
			return this;
		}
		public Criteria andAoeTypeIsNull() {
			addCriterion("f_aoe_type is null");
			return this;
		}
		public Criteria andAoeTypeIsNotNull() {
			addCriterion("f_aoe_type is not null");
			return this;
		}
		public Criteria andAoeTypeEqualTo(Byte value) {
			addCriterion("f_aoe_type =", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeNotEqualTo(Byte value) {
			addCriterion("f_aoe_type <>", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeGreaterThan(Byte value) {
			addCriterion("f_aoe_type >", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_aoe_type >=", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeLessThan(Byte value) {
			addCriterion("f_aoe_type <", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_aoe_type <=", value, "aoeType");
			return this;
		}
		public Criteria andAoeTypeIn(List values) {
			addCriterion("f_aoe_type in", values, "aoeType");
			return this;
		}
		public Criteria andAoeTypeNotIn(List values) {
			addCriterion("f_aoe_type not in", values, "aoeType");
			return this;
		}
		public Criteria andAoeTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_aoe_type between", value1, value2, "aoeType");
			return this;
		}
		public Criteria andAoeTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_aoe_type not between", value1, value2, "aoeType");
			return this;
		}
		public Criteria andHurtConsiderationWayIsNull() {
			addCriterion("f_hurt_consideration_way is null");
			return this;
		}
		public Criteria andHurtConsiderationWayIsNotNull() {
			addCriterion("f_hurt_consideration_way is not null");
			return this;
		}
		public Criteria andHurtConsiderationWayEqualTo(Byte value) {
			addCriterion("f_hurt_consideration_way =", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayNotEqualTo(Byte value) {
			addCriterion("f_hurt_consideration_way <>", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayGreaterThan(Byte value) {
			addCriterion("f_hurt_consideration_way >", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_hurt_consideration_way >=", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayLessThan(Byte value) {
			addCriterion("f_hurt_consideration_way <", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayLessThanOrEqualTo(Byte value) {
			addCriterion("f_hurt_consideration_way <=", value, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayIn(List values) {
			addCriterion("f_hurt_consideration_way in", values, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayNotIn(List values) {
			addCriterion("f_hurt_consideration_way not in", values, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayBetween(Byte value1, Byte value2) {
			addCriterion("f_hurt_consideration_way between", value1, value2, "hurtConsiderationWay");
			return this;
		}
		public Criteria andHurtConsiderationWayNotBetween(Byte value1, Byte value2) {
			addCriterion("f_hurt_consideration_way not between", value1, value2, "hurtConsiderationWay");
			return this;
		}
		public Criteria andTypeIsNull() {
			addCriterion("f_type is null");
			return this;
		}
		public Criteria andTypeIsNotNull() {
			addCriterion("f_type is not null");
			return this;
		}
		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("f_type =", value, "type");
			return this;
		}
		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("f_type <>", value, "type");
			return this;
		}
		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("f_type >", value, "type");
			return this;
		}
		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_type >=", value, "type");
			return this;
		}
		public Criteria andTypeLessThan(Byte value) {
			addCriterion("f_type <", value, "type");
			return this;
		}
		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_type <=", value, "type");
			return this;
		}
		public Criteria andTypeIn(List values) {
			addCriterion("f_type in", values, "type");
			return this;
		}
		public Criteria andTypeNotIn(List values) {
			addCriterion("f_type not in", values, "type");
			return this;
		}
		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_type between", value1, value2, "type");
			return this;
		}
		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_type not between", value1, value2, "type");
			return this;
		}
		public Criteria andHurtValueIsNull() {
			addCriterion("f_hurt_value is null");
			return this;
		}
		public Criteria andHurtValueIsNotNull() {
			addCriterion("f_hurt_value is not null");
			return this;
		}
		public Criteria andHurtValueEqualTo(Integer value) {
			addCriterion("f_hurt_value =", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueNotEqualTo(Integer value) {
			addCriterion("f_hurt_value <>", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueGreaterThan(Integer value) {
			addCriterion("f_hurt_value >", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value >=", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueLessThan(Integer value) {
			addCriterion("f_hurt_value <", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueLessThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value <=", value, "hurtValue");
			return this;
		}
		public Criteria andHurtValueIn(List values) {
			addCriterion("f_hurt_value in", values, "hurtValue");
			return this;
		}
		public Criteria andHurtValueNotIn(List values) {
			addCriterion("f_hurt_value not in", values, "hurtValue");
			return this;
		}
		public Criteria andHurtValueBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value between", value1, value2, "hurtValue");
			return this;
		}
		public Criteria andHurtValueNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value not between", value1, value2, "hurtValue");
			return this;
		}
		public Criteria andDurationIsNull() {
			addCriterion("f_duration is null");
			return this;
		}
		public Criteria andDurationIsNotNull() {
			addCriterion("f_duration is not null");
			return this;
		}
		public Criteria andDurationEqualTo(Integer value) {
			addCriterion("f_duration =", value, "duration");
			return this;
		}
		public Criteria andDurationNotEqualTo(Integer value) {
			addCriterion("f_duration <>", value, "duration");
			return this;
		}
		public Criteria andDurationGreaterThan(Integer value) {
			addCriterion("f_duration >", value, "duration");
			return this;
		}
		public Criteria andDurationGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_duration >=", value, "duration");
			return this;
		}
		public Criteria andDurationLessThan(Integer value) {
			addCriterion("f_duration <", value, "duration");
			return this;
		}
		public Criteria andDurationLessThanOrEqualTo(Integer value) {
			addCriterion("f_duration <=", value, "duration");
			return this;
		}
		public Criteria andDurationIn(List values) {
			addCriterion("f_duration in", values, "duration");
			return this;
		}
		public Criteria andDurationNotIn(List values) {
			addCriterion("f_duration not in", values, "duration");
			return this;
		}
		public Criteria andDurationBetween(Integer value1, Integer value2) {
			addCriterion("f_duration between", value1, value2, "duration");
			return this;
		}
		public Criteria andDurationNotBetween(Integer value1, Integer value2) {
			addCriterion("f_duration not between", value1, value2, "duration");
			return this;
		}
		public Criteria andPreDurationIsNull() {
			addCriterion("f_pre_duration is null");
			return this;
		}
		public Criteria andPreDurationIsNotNull() {
			addCriterion("f_pre_duration is not null");
			return this;
		}
		public Criteria andPreDurationEqualTo(Integer value) {
			addCriterion("f_pre_duration =", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationNotEqualTo(Integer value) {
			addCriterion("f_pre_duration <>", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationGreaterThan(Integer value) {
			addCriterion("f_pre_duration >", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_pre_duration >=", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationLessThan(Integer value) {
			addCriterion("f_pre_duration <", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationLessThanOrEqualTo(Integer value) {
			addCriterion("f_pre_duration <=", value, "preDuration");
			return this;
		}
		public Criteria andPreDurationIn(List values) {
			addCriterion("f_pre_duration in", values, "preDuration");
			return this;
		}
		public Criteria andPreDurationNotIn(List values) {
			addCriterion("f_pre_duration not in", values, "preDuration");
			return this;
		}
		public Criteria andPreDurationBetween(Integer value1, Integer value2) {
			addCriterion("f_pre_duration between", value1, value2, "preDuration");
			return this;
		}
		public Criteria andPreDurationNotBetween(Integer value1, Integer value2) {
			addCriterion("f_pre_duration not between", value1, value2, "preDuration");
			return this;
		}
		public Criteria andEffectRepeatOptionIsNull() {
			addCriterion("f_effect_repeat_option is null");
			return this;
		}
		public Criteria andEffectRepeatOptionIsNotNull() {
			addCriterion("f_effect_repeat_option is not null");
			return this;
		}
		public Criteria andEffectRepeatOptionEqualTo(Byte value) {
			addCriterion("f_effect_repeat_option =", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionNotEqualTo(Byte value) {
			addCriterion("f_effect_repeat_option <>", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionGreaterThan(Byte value) {
			addCriterion("f_effect_repeat_option >", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_effect_repeat_option >=", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionLessThan(Byte value) {
			addCriterion("f_effect_repeat_option <", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionLessThanOrEqualTo(Byte value) {
			addCriterion("f_effect_repeat_option <=", value, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionIn(List values) {
			addCriterion("f_effect_repeat_option in", values, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionNotIn(List values) {
			addCriterion("f_effect_repeat_option not in", values, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionBetween(Byte value1, Byte value2) {
			addCriterion("f_effect_repeat_option between", value1, value2, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatOptionNotBetween(Byte value1, Byte value2) {
			addCriterion("f_effect_repeat_option not between", value1, value2, "effectRepeatOption");
			return this;
		}
		public Criteria andEffectRepeatCountIsNull() {
			addCriterion("f_effect_repeat_count is null");
			return this;
		}
		public Criteria andEffectRepeatCountIsNotNull() {
			addCriterion("f_effect_repeat_count is not null");
			return this;
		}
		public Criteria andEffectRepeatCountEqualTo(Integer value) {
			addCriterion("f_effect_repeat_count =", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountNotEqualTo(Integer value) {
			addCriterion("f_effect_repeat_count <>", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountGreaterThan(Integer value) {
			addCriterion("f_effect_repeat_count >", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_effect_repeat_count >=", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountLessThan(Integer value) {
			addCriterion("f_effect_repeat_count <", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountLessThanOrEqualTo(Integer value) {
			addCriterion("f_effect_repeat_count <=", value, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountIn(List values) {
			addCriterion("f_effect_repeat_count in", values, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountNotIn(List values) {
			addCriterion("f_effect_repeat_count not in", values, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_repeat_count between", value1, value2, "effectRepeatCount");
			return this;
		}
		public Criteria andEffectRepeatCountNotBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_repeat_count not between", value1, value2, "effectRepeatCount");
			return this;
		}
		public Criteria andSpecialEffectChangeIsNull() {
			addCriterion("f_special_effect_change is null");
			return this;
		}
		public Criteria andSpecialEffectChangeIsNotNull() {
			addCriterion("f_special_effect_change is not null");
			return this;
		}
		public Criteria andSpecialEffectChangeEqualTo(Byte value) {
			addCriterion("f_special_effect_change =", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeNotEqualTo(Byte value) {
			addCriterion("f_special_effect_change <>", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeGreaterThan(Byte value) {
			addCriterion("f_special_effect_change >", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_special_effect_change >=", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeLessThan(Byte value) {
			addCriterion("f_special_effect_change <", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeLessThanOrEqualTo(Byte value) {
			addCriterion("f_special_effect_change <=", value, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeIn(List values) {
			addCriterion("f_special_effect_change in", values, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeNotIn(List values) {
			addCriterion("f_special_effect_change not in", values, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeBetween(Byte value1, Byte value2) {
			addCriterion("f_special_effect_change between", value1, value2, "specialEffectChange");
			return this;
		}
		public Criteria andSpecialEffectChangeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_special_effect_change not between", value1, value2, "specialEffectChange");
			return this;
		}
		public Criteria andEffectRepeatTypeIsNull() {
			addCriterion("f_effect_repeat_type is null");
			return this;
		}
		public Criteria andEffectRepeatTypeIsNotNull() {
			addCriterion("f_effect_repeat_type is not null");
			return this;
		}
		public Criteria andEffectRepeatTypeEqualTo(Byte value) {
			addCriterion("f_effect_repeat_type =", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeNotEqualTo(Byte value) {
			addCriterion("f_effect_repeat_type <>", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeGreaterThan(Byte value) {
			addCriterion("f_effect_repeat_type >", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_effect_repeat_type >=", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeLessThan(Byte value) {
			addCriterion("f_effect_repeat_type <", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_effect_repeat_type <=", value, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeIn(List values) {
			addCriterion("f_effect_repeat_type in", values, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeNotIn(List values) {
			addCriterion("f_effect_repeat_type not in", values, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_effect_repeat_type between", value1, value2, "effectRepeatType");
			return this;
		}
		public Criteria andEffectRepeatTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_effect_repeat_type not between", value1, value2, "effectRepeatType");
			return this;
		}
		public Criteria andDescIsNull() {
			addCriterion("f_desc is null");
			return this;
		}
		public Criteria andDescIsNotNull() {
			addCriterion("f_desc is not null");
			return this;
		}
		public Criteria andDescEqualTo(String value) {
			addCriterion("f_desc =", value, "desc");
			return this;
		}
		public Criteria andDescNotEqualTo(String value) {
			addCriterion("f_desc <>", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThan(String value) {
			addCriterion("f_desc >", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc >=", value, "desc");
			return this;
		}
		public Criteria andDescLessThan(String value) {
			addCriterion("f_desc <", value, "desc");
			return this;
		}
		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("f_desc <=", value, "desc");
			return this;
		}
		public Criteria andDescLike(String value) {
			addCriterion("f_desc like", value, "desc");
			return this;
		}
		public Criteria andDescNotLike(String value) {
			addCriterion("f_desc not like", value, "desc");
			return this;
		}
		public Criteria andDescIn(List values) {
			addCriterion("f_desc in", values, "desc");
			return this;
		}
		public Criteria andDescNotIn(List values) {
			addCriterion("f_desc not in", values, "desc");
			return this;
		}
		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("f_desc between", value1, value2, "desc");
			return this;
		}
		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("f_desc not between", value1, value2, "desc");
			return this;
		}
		public Criteria andHurtAddsIsNull() {
			addCriterion("f_hurt_adds is null");
			return this;
		}
		public Criteria andHurtAddsIsNotNull() {
			addCriterion("f_hurt_adds is not null");
			return this;
		}
		public Criteria andHurtAddsEqualTo(Integer value) {
			addCriterion("f_hurt_adds =", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsNotEqualTo(Integer value) {
			addCriterion("f_hurt_adds <>", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsGreaterThan(Integer value) {
			addCriterion("f_hurt_adds >", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_adds >=", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsLessThan(Integer value) {
			addCriterion("f_hurt_adds <", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsLessThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_adds <=", value, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsIn(List values) {
			addCriterion("f_hurt_adds in", values, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsNotIn(List values) {
			addCriterion("f_hurt_adds not in", values, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_adds between", value1, value2, "hurtAdds");
			return this;
		}
		public Criteria andHurtAddsNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_adds not between", value1, value2, "hurtAdds");
			return this;
		}
		public Criteria andPercentIsNull() {
			addCriterion("f_percent is null");
			return this;
		}
		public Criteria andPercentIsNotNull() {
			addCriterion("f_percent is not null");
			return this;
		}
		public Criteria andPercentEqualTo(Integer value) {
			addCriterion("f_percent =", value, "percent");
			return this;
		}
		public Criteria andPercentNotEqualTo(Integer value) {
			addCriterion("f_percent <>", value, "percent");
			return this;
		}
		public Criteria andPercentGreaterThan(Integer value) {
			addCriterion("f_percent >", value, "percent");
			return this;
		}
		public Criteria andPercentGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_percent >=", value, "percent");
			return this;
		}
		public Criteria andPercentLessThan(Integer value) {
			addCriterion("f_percent <", value, "percent");
			return this;
		}
		public Criteria andPercentLessThanOrEqualTo(Integer value) {
			addCriterion("f_percent <=", value, "percent");
			return this;
		}
		public Criteria andPercentIn(List values) {
			addCriterion("f_percent in", values, "percent");
			return this;
		}
		public Criteria andPercentNotIn(List values) {
			addCriterion("f_percent not in", values, "percent");
			return this;
		}
		public Criteria andPercentBetween(Integer value1, Integer value2) {
			addCriterion("f_percent between", value1, value2, "percent");
			return this;
		}
		public Criteria andPercentNotBetween(Integer value1, Integer value2) {
			addCriterion("f_percent not between", value1, value2, "percent");
			return this;
		}
		public Criteria andTypePnIsNull() {
			addCriterion("f_type_pn is null");
			return this;
		}
		public Criteria andTypePnIsNotNull() {
			addCriterion("f_type_pn is not null");
			return this;
		}
		public Criteria andTypePnEqualTo(Byte value) {
			addCriterion("f_type_pn =", value, "typePn");
			return this;
		}
		public Criteria andTypePnNotEqualTo(Byte value) {
			addCriterion("f_type_pn <>", value, "typePn");
			return this;
		}
		public Criteria andTypePnGreaterThan(Byte value) {
			addCriterion("f_type_pn >", value, "typePn");
			return this;
		}
		public Criteria andTypePnGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_type_pn >=", value, "typePn");
			return this;
		}
		public Criteria andTypePnLessThan(Byte value) {
			addCriterion("f_type_pn <", value, "typePn");
			return this;
		}
		public Criteria andTypePnLessThanOrEqualTo(Byte value) {
			addCriterion("f_type_pn <=", value, "typePn");
			return this;
		}
		public Criteria andTypePnIn(List values) {
			addCriterion("f_type_pn in", values, "typePn");
			return this;
		}
		public Criteria andTypePnNotIn(List values) {
			addCriterion("f_type_pn not in", values, "typePn");
			return this;
		}
		public Criteria andTypePnBetween(Byte value1, Byte value2) {
			addCriterion("f_type_pn between", value1, value2, "typePn");
			return this;
		}
		public Criteria andTypePnNotBetween(Byte value1, Byte value2) {
			addCriterion("f_type_pn not between", value1, value2, "typePn");
			return this;
		}
		public Criteria andJituiDistanceIsNull() {
			addCriterion("f_jitui_distance is null");
			return this;
		}
		public Criteria andJituiDistanceIsNotNull() {
			addCriterion("f_jitui_distance is not null");
			return this;
		}
		public Criteria andJituiDistanceEqualTo(Integer value) {
			addCriterion("f_jitui_distance =", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceNotEqualTo(Integer value) {
			addCriterion("f_jitui_distance <>", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceGreaterThan(Integer value) {
			addCriterion("f_jitui_distance >", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_jitui_distance >=", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceLessThan(Integer value) {
			addCriterion("f_jitui_distance <", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceLessThanOrEqualTo(Integer value) {
			addCriterion("f_jitui_distance <=", value, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceIn(List values) {
			addCriterion("f_jitui_distance in", values, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceNotIn(List values) {
			addCriterion("f_jitui_distance not in", values, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceBetween(Integer value1, Integer value2) {
			addCriterion("f_jitui_distance between", value1, value2, "jituiDistance");
			return this;
		}
		public Criteria andJituiDistanceNotBetween(Integer value1, Integer value2) {
			addCriterion("f_jitui_distance not between", value1, value2, "jituiDistance");
			return this;
		}
		public Criteria andIconIdIsNull() {
			addCriterion("f_icon_id is null");
			return this;
		}
		public Criteria andIconIdIsNotNull() {
			addCriterion("f_icon_id is not null");
			return this;
		}
		public Criteria andIconIdEqualTo(Integer value) {
			addCriterion("f_icon_id =", value, "iconId");
			return this;
		}
		public Criteria andIconIdNotEqualTo(Integer value) {
			addCriterion("f_icon_id <>", value, "iconId");
			return this;
		}
		public Criteria andIconIdGreaterThan(Integer value) {
			addCriterion("f_icon_id >", value, "iconId");
			return this;
		}
		public Criteria andIconIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_icon_id >=", value, "iconId");
			return this;
		}
		public Criteria andIconIdLessThan(Integer value) {
			addCriterion("f_icon_id <", value, "iconId");
			return this;
		}
		public Criteria andIconIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_icon_id <=", value, "iconId");
			return this;
		}
		public Criteria andIconIdIn(List values) {
			addCriterion("f_icon_id in", values, "iconId");
			return this;
		}
		public Criteria andIconIdNotIn(List values) {
			addCriterion("f_icon_id not in", values, "iconId");
			return this;
		}
		public Criteria andIconIdBetween(Integer value1, Integer value2) {
			addCriterion("f_icon_id between", value1, value2, "iconId");
			return this;
		}
		public Criteria andIconIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_icon_id not between", value1, value2, "iconId");
			return this;
		}
		public Criteria andEffectIdIsNull() {
			addCriterion("f_effect_id is null");
			return this;
		}
		public Criteria andEffectIdIsNotNull() {
			addCriterion("f_effect_id is not null");
			return this;
		}
		public Criteria andEffectIdEqualTo(Integer value) {
			addCriterion("f_effect_id =", value, "effectId");
			return this;
		}
		public Criteria andEffectIdNotEqualTo(Integer value) {
			addCriterion("f_effect_id <>", value, "effectId");
			return this;
		}
		public Criteria andEffectIdGreaterThan(Integer value) {
			addCriterion("f_effect_id >", value, "effectId");
			return this;
		}
		public Criteria andEffectIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_effect_id >=", value, "effectId");
			return this;
		}
		public Criteria andEffectIdLessThan(Integer value) {
			addCriterion("f_effect_id <", value, "effectId");
			return this;
		}
		public Criteria andEffectIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_effect_id <=", value, "effectId");
			return this;
		}
		public Criteria andEffectIdIn(List values) {
			addCriterion("f_effect_id in", values, "effectId");
			return this;
		}
		public Criteria andEffectIdNotIn(List values) {
			addCriterion("f_effect_id not in", values, "effectId");
			return this;
		}
		public Criteria andEffectIdBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_id between", value1, value2, "effectId");
			return this;
		}
		public Criteria andEffectIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_id not between", value1, value2, "effectId");
			return this;
		}
		public Criteria andGoodmodelIdIsNull() {
			addCriterion("f_goodmodel_id is null");
			return this;
		}
		public Criteria andGoodmodelIdIsNotNull() {
			addCriterion("f_goodmodel_id is not null");
			return this;
		}
		public Criteria andGoodmodelIdEqualTo(Integer value) {
			addCriterion("f_goodmodel_id =", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotEqualTo(Integer value) {
			addCriterion("f_goodmodel_id <>", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdGreaterThan(Integer value) {
			addCriterion("f_goodmodel_id >", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_goodmodel_id >=", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdLessThan(Integer value) {
			addCriterion("f_goodmodel_id <", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_goodmodel_id <=", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdIn(List values) {
			addCriterion("f_goodmodel_id in", values, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotIn(List values) {
			addCriterion("f_goodmodel_id not in", values, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdBetween(Integer value1, Integer value2) {
			addCriterion("f_goodmodel_id between", value1, value2, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_goodmodel_id not between", value1, value2, "goodmodelId");
			return this;
		}
		public Criteria andBuffFlagIsNull() {
			addCriterion("f_buff_flag is null");
			return this;
		}
		public Criteria andBuffFlagIsNotNull() {
			addCriterion("f_buff_flag is not null");
			return this;
		}
		public Criteria andBuffFlagEqualTo(Byte value) {
			addCriterion("f_buff_flag =", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagNotEqualTo(Byte value) {
			addCriterion("f_buff_flag <>", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagGreaterThan(Byte value) {
			addCriterion("f_buff_flag >", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_buff_flag >=", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagLessThan(Byte value) {
			addCriterion("f_buff_flag <", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagLessThanOrEqualTo(Byte value) {
			addCriterion("f_buff_flag <=", value, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagIn(List values) {
			addCriterion("f_buff_flag in", values, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagNotIn(List values) {
			addCriterion("f_buff_flag not in", values, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagBetween(Byte value1, Byte value2) {
			addCriterion("f_buff_flag between", value1, value2, "buffFlag");
			return this;
		}
		public Criteria andBuffFlagNotBetween(Byte value1, Byte value2) {
			addCriterion("f_buff_flag not between", value1, value2, "buffFlag");
			return this;
		}
		public Criteria andIsDieCleanIsNull() {
			addCriterion("f_is_die_clean is null");
			return this;
		}
		public Criteria andIsDieCleanIsNotNull() {
			addCriterion("f_is_die_clean is not null");
			return this;
		}
		public Criteria andIsDieCleanEqualTo(Byte value) {
			addCriterion("f_is_die_clean =", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanNotEqualTo(Byte value) {
			addCriterion("f_is_die_clean <>", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanGreaterThan(Byte value) {
			addCriterion("f_is_die_clean >", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_is_die_clean >=", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanLessThan(Byte value) {
			addCriterion("f_is_die_clean <", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanLessThanOrEqualTo(Byte value) {
			addCriterion("f_is_die_clean <=", value, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanIn(List values) {
			addCriterion("f_is_die_clean in", values, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanNotIn(List values) {
			addCriterion("f_is_die_clean not in", values, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanBetween(Byte value1, Byte value2) {
			addCriterion("f_is_die_clean between", value1, value2, "isDieClean");
			return this;
		}
		public Criteria andIsDieCleanNotBetween(Byte value1, Byte value2) {
			addCriterion("f_is_die_clean not between", value1, value2, "isDieClean");
			return this;
		}
		public Criteria andHurtValueMinIsNull() {
			addCriterion("f_hurt_value_min is null");
			return this;
		}
		public Criteria andHurtValueMinIsNotNull() {
			addCriterion("f_hurt_value_min is not null");
			return this;
		}
		public Criteria andHurtValueMinEqualTo(Integer value) {
			addCriterion("f_hurt_value_min =", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinNotEqualTo(Integer value) {
			addCriterion("f_hurt_value_min <>", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinGreaterThan(Integer value) {
			addCriterion("f_hurt_value_min >", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value_min >=", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinLessThan(Integer value) {
			addCriterion("f_hurt_value_min <", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinLessThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value_min <=", value, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinIn(List values) {
			addCriterion("f_hurt_value_min in", values, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinNotIn(List values) {
			addCriterion("f_hurt_value_min not in", values, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value_min between", value1, value2, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMinNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value_min not between", value1, value2, "hurtValueMin");
			return this;
		}
		public Criteria andHurtValueMaxIsNull() {
			addCriterion("f_hurt_value_max is null");
			return this;
		}
		public Criteria andHurtValueMaxIsNotNull() {
			addCriterion("f_hurt_value_max is not null");
			return this;
		}
		public Criteria andHurtValueMaxEqualTo(Integer value) {
			addCriterion("f_hurt_value_max =", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxNotEqualTo(Integer value) {
			addCriterion("f_hurt_value_max <>", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxGreaterThan(Integer value) {
			addCriterion("f_hurt_value_max >", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value_max >=", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxLessThan(Integer value) {
			addCriterion("f_hurt_value_max <", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxLessThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_value_max <=", value, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxIn(List values) {
			addCriterion("f_hurt_value_max in", values, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxNotIn(List values) {
			addCriterion("f_hurt_value_max not in", values, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value_max between", value1, value2, "hurtValueMax");
			return this;
		}
		public Criteria andHurtValueMaxNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_value_max not between", value1, value2, "hurtValueMax");
			return this;
		}
		public Criteria andAttackerIsIdeCleanIsNull() {
			addCriterion("f_attacker_is_ide_clean is null");
			return this;
		}
		public Criteria andAttackerIsIdeCleanIsNotNull() {
			addCriterion("f_attacker_is_ide_clean is not null");
			return this;
		}
		public Criteria andAttackerIsIdeCleanEqualTo(Byte value) {
			addCriterion("f_attacker_is_ide_clean =", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanNotEqualTo(Byte value) {
			addCriterion("f_attacker_is_ide_clean <>", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanGreaterThan(Byte value) {
			addCriterion("f_attacker_is_ide_clean >", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_attacker_is_ide_clean >=", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanLessThan(Byte value) {
			addCriterion("f_attacker_is_ide_clean <", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanLessThanOrEqualTo(Byte value) {
			addCriterion("f_attacker_is_ide_clean <=", value, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanIn(List values) {
			addCriterion("f_attacker_is_ide_clean in", values, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanNotIn(List values) {
			addCriterion("f_attacker_is_ide_clean not in", values, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanBetween(Byte value1, Byte value2) {
			addCriterion("f_attacker_is_ide_clean between", value1, value2, "attackerIsIdeClean");
			return this;
		}
		public Criteria andAttackerIsIdeCleanNotBetween(Byte value1, Byte value2) {
			addCriterion("f_attacker_is_ide_clean not between", value1, value2, "attackerIsIdeClean");
			return this;
		}
		public Criteria andDuMaxHurtIsNull() {
			addCriterion("f_du_max_hurt is null");
			return this;
		}
		public Criteria andDuMaxHurtIsNotNull() {
			addCriterion("f_du_max_hurt is not null");
			return this;
		}
		public Criteria andDuMaxHurtEqualTo(Integer value) {
			addCriterion("f_du_max_hurt =", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtNotEqualTo(Integer value) {
			addCriterion("f_du_max_hurt <>", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtGreaterThan(Integer value) {
			addCriterion("f_du_max_hurt >", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_du_max_hurt >=", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtLessThan(Integer value) {
			addCriterion("f_du_max_hurt <", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtLessThanOrEqualTo(Integer value) {
			addCriterion("f_du_max_hurt <=", value, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtIn(List values) {
			addCriterion("f_du_max_hurt in", values, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtNotIn(List values) {
			addCriterion("f_du_max_hurt not in", values, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtBetween(Integer value1, Integer value2) {
			addCriterion("f_du_max_hurt between", value1, value2, "duMaxHurt");
			return this;
		}
		public Criteria andDuMaxHurtNotBetween(Integer value1, Integer value2) {
			addCriterion("f_du_max_hurt not between", value1, value2, "duMaxHurt");
			return this;
		}
		public Criteria andClipsDescIsNull() {
			addCriterion("f_clips_desc is null");
			return this;
		}
		public Criteria andClipsDescIsNotNull() {
			addCriterion("f_clips_desc is not null");
			return this;
		}
		public Criteria andClipsDescEqualTo(String value) {
			addCriterion("f_clips_desc =", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescNotEqualTo(String value) {
			addCriterion("f_clips_desc <>", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescGreaterThan(String value) {
			addCriterion("f_clips_desc >", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_clips_desc >=", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescLessThan(String value) {
			addCriterion("f_clips_desc <", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescLessThanOrEqualTo(String value) {
			addCriterion("f_clips_desc <=", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescLike(String value) {
			addCriterion("f_clips_desc like", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescNotLike(String value) {
			addCriterion("f_clips_desc not like", value, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescIn(List values) {
			addCriterion("f_clips_desc in", values, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescNotIn(List values) {
			addCriterion("f_clips_desc not in", values, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescBetween(String value1, String value2) {
			addCriterion("f_clips_desc between", value1, value2, "clipsDesc");
			return this;
		}
		public Criteria andClipsDescNotBetween(String value1, String value2) {
			addCriterion("f_clips_desc not between", value1, value2, "clipsDesc");
			return this;
		}
		public Criteria andNameI18nIsNull() {
			addCriterion("f_name_i18n is null");
			return this;
		}
		public Criteria andNameI18nIsNotNull() {
			addCriterion("f_name_i18n is not null");
			return this;
		}
		public Criteria andNameI18nEqualTo(String value) {
			addCriterion("f_name_i18n =", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotEqualTo(String value) {
			addCriterion("f_name_i18n <>", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThan(String value) {
			addCriterion("f_name_i18n >", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_name_i18n >=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThan(String value) {
			addCriterion("f_name_i18n <", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThanOrEqualTo(String value) {
			addCriterion("f_name_i18n <=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLike(String value) {
			addCriterion("f_name_i18n like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotLike(String value) {
			addCriterion("f_name_i18n not like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nIn(List values) {
			addCriterion("f_name_i18n in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotIn(List values) {
			addCriterion("f_name_i18n not in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nBetween(String value1, String value2) {
			addCriterion("f_name_i18n between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotBetween(String value1, String value2) {
			addCriterion("f_name_i18n not between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andDescI18nIsNull() {
			addCriterion("f_desc_i18n is null");
			return this;
		}
		public Criteria andDescI18nIsNotNull() {
			addCriterion("f_desc_i18n is not null");
			return this;
		}
		public Criteria andDescI18nEqualTo(String value) {
			addCriterion("f_desc_i18n =", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotEqualTo(String value) {
			addCriterion("f_desc_i18n <>", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThan(String value) {
			addCriterion("f_desc_i18n >", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n >=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThan(String value) {
			addCriterion("f_desc_i18n <", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n <=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLike(String value) {
			addCriterion("f_desc_i18n like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotLike(String value) {
			addCriterion("f_desc_i18n not like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nIn(List values) {
			addCriterion("f_desc_i18n in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotIn(List values) {
			addCriterion("f_desc_i18n not in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nBetween(String value1, String value2) {
			addCriterion("f_desc_i18n between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotBetween(String value1, String value2) {
			addCriterion("f_desc_i18n not between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andClipsDescI18nIsNull() {
			addCriterion("f_clips_desc_i18n is null");
			return this;
		}
		public Criteria andClipsDescI18nIsNotNull() {
			addCriterion("f_clips_desc_i18n is not null");
			return this;
		}
		public Criteria andClipsDescI18nEqualTo(String value) {
			addCriterion("f_clips_desc_i18n =", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nNotEqualTo(String value) {
			addCriterion("f_clips_desc_i18n <>", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nGreaterThan(String value) {
			addCriterion("f_clips_desc_i18n >", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_clips_desc_i18n >=", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nLessThan(String value) {
			addCriterion("f_clips_desc_i18n <", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nLessThanOrEqualTo(String value) {
			addCriterion("f_clips_desc_i18n <=", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nLike(String value) {
			addCriterion("f_clips_desc_i18n like", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nNotLike(String value) {
			addCriterion("f_clips_desc_i18n not like", value, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nIn(List values) {
			addCriterion("f_clips_desc_i18n in", values, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nNotIn(List values) {
			addCriterion("f_clips_desc_i18n not in", values, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nBetween(String value1, String value2) {
			addCriterion("f_clips_desc_i18n between", value1, value2, "clipsDescI18n");
			return this;
		}
		public Criteria andClipsDescI18nNotBetween(String value1, String value2) {
			addCriterion("f_clips_desc_i18n not between", value1, value2, "clipsDescI18n");
			return this;
		}
	}
}
