package net.snake.dao.skilleffect;

import java.util.List;

import net.snake.dao.skilleffect.SkillEffect;
import net.snake.dao.skilleffect.SkillEffectExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SkillEffectDAOImpl extends SqlMapClientDaoSupport implements SkillEffectDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public SkillEffectDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int countByExample(SkillEffectExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_skill_effect.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int deleteByExample(SkillEffectExample example) {
		int rows = getSqlMapClientTemplate().delete("t_skill_effect.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		SkillEffect key = new SkillEffect();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_skill_effect.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public void insert(SkillEffect record) {
		getSqlMapClientTemplate().insert("t_skill_effect.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public void insertSelective(SkillEffect record) {
		getSqlMapClientTemplate().insert("t_skill_effect.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public List selectByExample(SkillEffectExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_skill_effect.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public SkillEffect selectByPrimaryKey(Integer id) {
		SkillEffect key = new SkillEffect();
		key.setId(id);
		SkillEffect record = (SkillEffect) getSqlMapClientTemplate().queryForObject(
				"t_skill_effect.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int updateByExampleSelective(SkillEffect record, SkillEffectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_skill_effect.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int updateByExample(SkillEffect record, SkillEffectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_skill_effect.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int updateByPrimaryKeySelective(SkillEffect record) {
		int rows = getSqlMapClientTemplate().update(
				"t_skill_effect.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	public int updateByPrimaryKey(SkillEffect record) {
		int rows = getSqlMapClientTemplate().update("t_skill_effect.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_skill_effect
	 * @ibatorgenerated  Wed Jul 27 15:40:01 CST 2011
	 */
	private static class UpdateByExampleParms extends SkillEffectExample {
		private Object record;
		public UpdateByExampleParms(Object record, SkillEffectExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
