package net.snake.dao.taskdialog;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Date;

public class TaskdialogExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public TaskdialogExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	protected TaskdialogExample(TaskdialogExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}
		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}
		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}
		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}
		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}
		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}
		public Criteria andIdIsNull() {
			addCriterion("f_id is null");
			return this;
		}
		public Criteria andIdIsNotNull() {
			addCriterion("f_id is not null");
			return this;
		}
		public Criteria andIdEqualTo(Integer value) {
			addCriterion("f_id =", value, "id");
			return this;
		}
		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("f_id <>", value, "id");
			return this;
		}
		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("f_id >", value, "id");
			return this;
		}
		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_id >=", value, "id");
			return this;
		}
		public Criteria andIdLessThan(Integer value) {
			addCriterion("f_id <", value, "id");
			return this;
		}
		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_id <=", value, "id");
			return this;
		}
		public Criteria andIdIn(List values) {
			addCriterion("f_id in", values, "id");
			return this;
		}
		public Criteria andIdNotIn(List values) {
			addCriterion("f_id not in", values, "id");
			return this;
		}
		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("f_id between", value1, value2, "id");
			return this;
		}
		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_id not between", value1, value2, "id");
			return this;
		}
		public Criteria andTaskIdIsNull() {
			addCriterion("f_task_id is null");
			return this;
		}
		public Criteria andTaskIdIsNotNull() {
			addCriterion("f_task_id is not null");
			return this;
		}
		public Criteria andTaskIdEqualTo(Integer value) {
			addCriterion("f_task_id =", value, "taskId");
			return this;
		}
		public Criteria andTaskIdNotEqualTo(Integer value) {
			addCriterion("f_task_id <>", value, "taskId");
			return this;
		}
		public Criteria andTaskIdGreaterThan(Integer value) {
			addCriterion("f_task_id >", value, "taskId");
			return this;
		}
		public Criteria andTaskIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_task_id >=", value, "taskId");
			return this;
		}
		public Criteria andTaskIdLessThan(Integer value) {
			addCriterion("f_task_id <", value, "taskId");
			return this;
		}
		public Criteria andTaskIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_task_id <=", value, "taskId");
			return this;
		}
		public Criteria andTaskIdIn(List values) {
			addCriterion("f_task_id in", values, "taskId");
			return this;
		}
		public Criteria andTaskIdNotIn(List values) {
			addCriterion("f_task_id not in", values, "taskId");
			return this;
		}
		public Criteria andTaskIdBetween(Integer value1, Integer value2) {
			addCriterion("f_task_id between", value1, value2, "taskId");
			return this;
		}
		public Criteria andTaskIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_task_id not between", value1, value2, "taskId");
			return this;
		}
		public Criteria andDialogTypeIsNull() {
			addCriterion("f_dialog_type is null");
			return this;
		}
		public Criteria andDialogTypeIsNotNull() {
			addCriterion("f_dialog_type is not null");
			return this;
		}
		public Criteria andDialogTypeEqualTo(Integer value) {
			addCriterion("f_dialog_type =", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeNotEqualTo(Integer value) {
			addCriterion("f_dialog_type <>", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeGreaterThan(Integer value) {
			addCriterion("f_dialog_type >", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_dialog_type >=", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeLessThan(Integer value) {
			addCriterion("f_dialog_type <", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_dialog_type <=", value, "dialogType");
			return this;
		}
		public Criteria andDialogTypeIn(List values) {
			addCriterion("f_dialog_type in", values, "dialogType");
			return this;
		}
		public Criteria andDialogTypeNotIn(List values) {
			addCriterion("f_dialog_type not in", values, "dialogType");
			return this;
		}
		public Criteria andDialogTypeBetween(Integer value1, Integer value2) {
			addCriterion("f_dialog_type between", value1, value2, "dialogType");
			return this;
		}
		public Criteria andDialogTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_dialog_type not between", value1, value2, "dialogType");
			return this;
		}
		public Criteria andNpcIdIsNull() {
			addCriterion("f_npc_id is null");
			return this;
		}
		public Criteria andNpcIdIsNotNull() {
			addCriterion("f_npc_id is not null");
			return this;
		}
		public Criteria andNpcIdEqualTo(Integer value) {
			addCriterion("f_npc_id =", value, "npcId");
			return this;
		}
		public Criteria andNpcIdNotEqualTo(Integer value) {
			addCriterion("f_npc_id <>", value, "npcId");
			return this;
		}
		public Criteria andNpcIdGreaterThan(Integer value) {
			addCriterion("f_npc_id >", value, "npcId");
			return this;
		}
		public Criteria andNpcIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_npc_id >=", value, "npcId");
			return this;
		}
		public Criteria andNpcIdLessThan(Integer value) {
			addCriterion("f_npc_id <", value, "npcId");
			return this;
		}
		public Criteria andNpcIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_npc_id <=", value, "npcId");
			return this;
		}
		public Criteria andNpcIdIn(List values) {
			addCriterion("f_npc_id in", values, "npcId");
			return this;
		}
		public Criteria andNpcIdNotIn(List values) {
			addCriterion("f_npc_id not in", values, "npcId");
			return this;
		}
		public Criteria andNpcIdBetween(Integer value1, Integer value2) {
			addCriterion("f_npc_id between", value1, value2, "npcId");
			return this;
		}
		public Criteria andNpcIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_npc_id not between", value1, value2, "npcId");
			return this;
		}
		public Criteria andTalkTypeIsNull() {
			addCriterion("f_talk_type is null");
			return this;
		}
		public Criteria andTalkTypeIsNotNull() {
			addCriterion("f_talk_type is not null");
			return this;
		}
		public Criteria andTalkTypeEqualTo(Integer value) {
			addCriterion("f_talk_type =", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeNotEqualTo(Integer value) {
			addCriterion("f_talk_type <>", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeGreaterThan(Integer value) {
			addCriterion("f_talk_type >", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_talk_type >=", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeLessThan(Integer value) {
			addCriterion("f_talk_type <", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_talk_type <=", value, "talkType");
			return this;
		}
		public Criteria andTalkTypeIn(List values) {
			addCriterion("f_talk_type in", values, "talkType");
			return this;
		}
		public Criteria andTalkTypeNotIn(List values) {
			addCriterion("f_talk_type not in", values, "talkType");
			return this;
		}
		public Criteria andTalkTypeBetween(Integer value1, Integer value2) {
			addCriterion("f_talk_type between", value1, value2, "talkType");
			return this;
		}
		public Criteria andTalkTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_talk_type not between", value1, value2, "talkType");
			return this;
		}
		public Criteria andTalkContentIsNull() {
			addCriterion("f_talk_content is null");
			return this;
		}
		public Criteria andTalkContentIsNotNull() {
			addCriterion("f_talk_content is not null");
			return this;
		}
		public Criteria andTalkContentEqualTo(String value) {
			addCriterion("f_talk_content =", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentNotEqualTo(String value) {
			addCriterion("f_talk_content <>", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentGreaterThan(String value) {
			addCriterion("f_talk_content >", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentGreaterThanOrEqualTo(String value) {
			addCriterion("f_talk_content >=", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentLessThan(String value) {
			addCriterion("f_talk_content <", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentLessThanOrEqualTo(String value) {
			addCriterion("f_talk_content <=", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentLike(String value) {
			addCriterion("f_talk_content like", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentNotLike(String value) {
			addCriterion("f_talk_content not like", value, "talkContent");
			return this;
		}
		public Criteria andTalkContentIn(List values) {
			addCriterion("f_talk_content in", values, "talkContent");
			return this;
		}
		public Criteria andTalkContentNotIn(List values) {
			addCriterion("f_talk_content not in", values, "talkContent");
			return this;
		}
		public Criteria andTalkContentBetween(String value1, String value2) {
			addCriterion("f_talk_content between", value1, value2, "talkContent");
			return this;
		}
		public Criteria andTalkContentNotBetween(String value1, String value2) {
			addCriterion("f_talk_content not between", value1, value2, "talkContent");
			return this;
		}
		public Criteria andTalkContentIdIsNull() {
			addCriterion("f_talk_content_id is null");
			return this;
		}
		public Criteria andTalkContentIdIsNotNull() {
			addCriterion("f_talk_content_id is not null");
			return this;
		}
		public Criteria andTalkContentIdEqualTo(Integer value) {
			addCriterion("f_talk_content_id =", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdNotEqualTo(Integer value) {
			addCriterion("f_talk_content_id <>", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdGreaterThan(Integer value) {
			addCriterion("f_talk_content_id >", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_talk_content_id >=", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdLessThan(Integer value) {
			addCriterion("f_talk_content_id <", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_talk_content_id <=", value, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdIn(List values) {
			addCriterion("f_talk_content_id in", values, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdNotIn(List values) {
			addCriterion("f_talk_content_id not in", values, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdBetween(Integer value1, Integer value2) {
			addCriterion("f_talk_content_id between", value1, value2, "talkContentId");
			return this;
		}
		public Criteria andTalkContentIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_talk_content_id not between", value1, value2, "talkContentId");
			return this;
		}
		public Criteria andDialogIdIsNull() {
			addCriterion("f_dialog_id is null");
			return this;
		}
		public Criteria andDialogIdIsNotNull() {
			addCriterion("f_dialog_id is not null");
			return this;
		}
		public Criteria andDialogIdEqualTo(Integer value) {
			addCriterion("f_dialog_id =", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdNotEqualTo(Integer value) {
			addCriterion("f_dialog_id <>", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdGreaterThan(Integer value) {
			addCriterion("f_dialog_id >", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_dialog_id >=", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdLessThan(Integer value) {
			addCriterion("f_dialog_id <", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_dialog_id <=", value, "dialogId");
			return this;
		}
		public Criteria andDialogIdIn(List values) {
			addCriterion("f_dialog_id in", values, "dialogId");
			return this;
		}
		public Criteria andDialogIdNotIn(List values) {
			addCriterion("f_dialog_id not in", values, "dialogId");
			return this;
		}
		public Criteria andDialogIdBetween(Integer value1, Integer value2) {
			addCriterion("f_dialog_id between", value1, value2, "dialogId");
			return this;
		}
		public Criteria andDialogIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_dialog_id not between", value1, value2, "dialogId");
			return this;
		}
		public Criteria andTalknpcIdIsNull() {
			addCriterion("f_talkNpc_id is null");
			return this;
		}
		public Criteria andTalknpcIdIsNotNull() {
			addCriterion("f_talkNpc_id is not null");
			return this;
		}
		public Criteria andTalknpcIdEqualTo(Integer value) {
			addCriterion("f_talkNpc_id =", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdNotEqualTo(Integer value) {
			addCriterion("f_talkNpc_id <>", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdGreaterThan(Integer value) {
			addCriterion("f_talkNpc_id >", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_talkNpc_id >=", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdLessThan(Integer value) {
			addCriterion("f_talkNpc_id <", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_talkNpc_id <=", value, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdIn(List values) {
			addCriterion("f_talkNpc_id in", values, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdNotIn(List values) {
			addCriterion("f_talkNpc_id not in", values, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdBetween(Integer value1, Integer value2) {
			addCriterion("f_talkNpc_id between", value1, value2, "talknpcId");
			return this;
		}
		public Criteria andTalknpcIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_talkNpc_id not between", value1, value2, "talknpcId");
			return this;
		}
		public Criteria andTimeIsNull() {
			addCriterion("f_time is null");
			return this;
		}
		public Criteria andTimeIsNotNull() {
			addCriterion("f_time is not null");
			return this;
		}
		public Criteria andTimeEqualTo(Date value) {
			addCriterion("f_time =", value, "time");
			return this;
		}
		public Criteria andTimeNotEqualTo(Date value) {
			addCriterion("f_time <>", value, "time");
			return this;
		}
		public Criteria andTimeGreaterThan(Date value) {
			addCriterion("f_time >", value, "time");
			return this;
		}
		public Criteria andTimeGreaterThanOrEqualTo(Date value) {
			addCriterion("f_time >=", value, "time");
			return this;
		}
		public Criteria andTimeLessThan(Date value) {
			addCriterion("f_time <", value, "time");
			return this;
		}
		public Criteria andTimeLessThanOrEqualTo(Date value) {
			addCriterion("f_time <=", value, "time");
			return this;
		}
		public Criteria andTimeIn(List values) {
			addCriterion("f_time in", values, "time");
			return this;
		}
		public Criteria andTimeNotIn(List values) {
			addCriterion("f_time not in", values, "time");
			return this;
		}
		public Criteria andTimeBetween(Date value1, Date value2) {
			addCriterion("f_time between", value1, value2, "time");
			return this;
		}
		public Criteria andTimeNotBetween(Date value1, Date value2) {
			addCriterion("f_time not between", value1, value2, "time");
			return this;
		}
		public Criteria andTalkContentI18nIsNull() {
			addCriterion("f_talk_content_i18n is null");
			return this;
		}
		public Criteria andTalkContentI18nIsNotNull() {
			addCriterion("f_talk_content_i18n is not null");
			return this;
		}
		public Criteria andTalkContentI18nEqualTo(String value) {
			addCriterion("f_talk_content_i18n =", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nNotEqualTo(String value) {
			addCriterion("f_talk_content_i18n <>", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nGreaterThan(String value) {
			addCriterion("f_talk_content_i18n >", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_talk_content_i18n >=", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nLessThan(String value) {
			addCriterion("f_talk_content_i18n <", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nLessThanOrEqualTo(String value) {
			addCriterion("f_talk_content_i18n <=", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nLike(String value) {
			addCriterion("f_talk_content_i18n like", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nNotLike(String value) {
			addCriterion("f_talk_content_i18n not like", value, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nIn(List values) {
			addCriterion("f_talk_content_i18n in", values, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nNotIn(List values) {
			addCriterion("f_talk_content_i18n not in", values, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nBetween(String value1, String value2) {
			addCriterion("f_talk_content_i18n between", value1, value2, "talkContentI18n");
			return this;
		}
		public Criteria andTalkContentI18nNotBetween(String value1, String value2) {
			addCriterion("f_talk_content_i18n not between", value1, value2, "talkContentI18n");
			return this;
		}
	}
}
