package net.snake.dao.shopshengwang;

import java.util.List;

import net.snake.dao.shopshengwang.ShopShengWang;
import net.snake.dao.shopshengwang.ShopShengWangExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ShopShengWangDAOImpl extends SqlMapClientDaoSupport implements ShopShengWangDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public ShopShengWangDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int countByExample(ShopShengWangExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_shop_shengwang.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int deleteByExample(ShopShengWangExample example) {
		int rows = getSqlMapClientTemplate().delete("t_shop_shengwang.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		ShopShengWang key = new ShopShengWang();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("t_shop_shengwang.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public void insert(ShopShengWang record) {
		getSqlMapClientTemplate().insert("t_shop_shengwang.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public void insertSelective(ShopShengWang record) {
		getSqlMapClientTemplate().insert("t_shop_shengwang.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public List selectByExample(ShopShengWangExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_shop_shengwang.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public ShopShengWang selectByPrimaryKey(Integer id) {
		ShopShengWang key = new ShopShengWang();
		key.setId(id);
		ShopShengWang record = (ShopShengWang) getSqlMapClientTemplate().queryForObject(
				"t_shop_shengwang.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int updateByExampleSelective(ShopShengWang record, ShopShengWangExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_shop_shengwang.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int updateByExample(ShopShengWang record, ShopShengWangExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_shop_shengwang.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int updateByPrimaryKeySelective(ShopShengWang record) {
		int rows = getSqlMapClientTemplate().update(
				"t_shop_shengwang.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	public int updateByPrimaryKey(ShopShengWang record) {
		int rows = getSqlMapClientTemplate().update("t_shop_shengwang.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:57 CST 2011
	 */
	private static class UpdateByExampleParms extends ShopShengWangExample {
		private Object record;
		public UpdateByExampleParms(Object record, ShopShengWangExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
