package net.snake.dao.effect;

import java.util.List;

import net.snake.dao.effect.Effect;
import net.snake.dao.effect.EffectExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EffectDAOImpl extends SqlMapClientDaoSupport implements EffectDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public EffectDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int countByExample(EffectExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_effect.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int deleteByExample(EffectExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_effect.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int deleteByPrimaryKey(Integer id) {
		Effect key = new Effect();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_effect.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public void insert(Effect record) {
		getSqlMapClientTemplate().insert("t_effect.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public void insertSelective(Effect record) {
		getSqlMapClientTemplate().insert(
				"t_effect.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public List selectByExample(EffectExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_effect.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public Effect selectByPrimaryKey(Integer id) {
		Effect key = new Effect();
		key.setId(id);
		Effect record = (Effect) getSqlMapClientTemplate().queryForObject(
				"t_effect.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int updateByExampleSelective(Effect record, EffectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_effect.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int updateByExample(Effect record, EffectExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_effect.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int updateByPrimaryKeySelective(Effect record) {
		int rows = getSqlMapClientTemplate().update(
				"t_effect.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	public int updateByPrimaryKey(Effect record) {
		int rows = getSqlMapClientTemplate().update(
				"t_effect.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_effect
	 * @ibatorgenerated  Thu Nov 18 08:29:04 GMT 2010
	 */
	private static class UpdateByExampleParms extends EffectExample {
		private Object record;

		public UpdateByExampleParms(Object record, EffectExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Effect> getAvatar_effect() {
		 List list = getSqlMapClientTemplate().queryForList("t_effect.selectlianhechaxun_effect2");
	        return list;
	}

	@Override
	public List<Effect> getAvatar_effectByid(Effect effect) {
		return getSqlMapClientTemplate().queryForList("t_effect.selectlianhechaxun_effectid",effect);
	}


}
