package net.snake.dao.map2;

import java.util.List;

import net.snake.dao.map2.Map2;
import net.snake.dao.map2.Map2Example;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Map2DAOImpl extends SqlMapClientDaoSupport implements Map2DAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public Map2DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int countByExample(Map2Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_map_1.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int deleteByExample(Map2Example example) {
		int rows = getSqlMapClientTemplate().delete("t_map_1.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int deleteByPrimaryKey(Integer mapId) {
		Map2 key = new Map2();
		key.setMapId(mapId);
		int rows = getSqlMapClientTemplate().delete("t_map_1.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public void insert(Map2 record) {
		getSqlMapClientTemplate().insert("t_map_1.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public void insertSelective(Map2 record) {
		getSqlMapClientTemplate().insert("t_map_1.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public List selectByExample(Map2Example example) {
		List list = getSqlMapClientTemplate().queryForList("t_map_1.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public Map2 selectByPrimaryKey(Integer mapId) {
		Map2 key = new Map2();
		key.setMapId(mapId);
		Map2 record = (Map2) getSqlMapClientTemplate().queryForObject(
				"t_map_1.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int updateByExampleSelective(Map2 record, Map2Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_map_1.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int updateByExample(Map2 record, Map2Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_map_1.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int updateByPrimaryKeySelective(Map2 record) {
		int rows = getSqlMapClientTemplate().update("t_map_1.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	public int updateByPrimaryKey(Map2 record) {
		int rows = getSqlMapClientTemplate().update("t_map_1.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_map_1
	 * @ibatorgenerated  Fri May 06 16:50:49 CST 2011
	 */
	private static class UpdateByExampleParms extends Map2Example {
		private Object record;
		public UpdateByExampleParms(Object record, Map2Example example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
