package net.snake.dao.language;

import java.util.List;

import net.snake.dao.language.Language;
import net.snake.dao.language.LanguageExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LanguageDAOImpl extends SqlMapClientDaoSupport implements LanguageDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public LanguageDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int countByExample(LanguageExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_language.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int deleteByExample(LanguageExample example) {
		int rows = getSqlMapClientTemplate().delete("t_language.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Language key = new Language();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_language.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public void insert(Language record) {
		getSqlMapClientTemplate().insert("t_language.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public void insertSelective(Language record) {
		getSqlMapClientTemplate().insert("t_language.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public List selectByExample(LanguageExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_language.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public Language selectByPrimaryKey(Integer id) {
		Language key = new Language();
		key.setId(id);
		Language record = (Language) getSqlMapClientTemplate().queryForObject(
				"t_language.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int updateByExampleSelective(Language record, LanguageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_language.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int updateByExample(Language record, LanguageExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_language.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int updateByPrimaryKeySelective(Language record) {
		int rows = getSqlMapClientTemplate().update("t_language.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	public int updateByPrimaryKey(Language record) {
		int rows = getSqlMapClientTemplate().update("t_language.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_language
	 * @ibatorgenerated  Sat May 07 11:44:01 CST 2011
	 */
	private static class UpdateByExampleParms extends LanguageExample {
		private Object record;
		public UpdateByExampleParms(Object record, LanguageExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
