package net.snake.dao.skillupgradeexp;

import java.util.List;

import net.snake.dao.skillupgradeexp.SkillupgradeExp;
import net.snake.dao.skillupgradeexp.SkillupgradeExpExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SkillupgradeExpDAOImpl extends SqlMapClientDaoSupport implements SkillupgradeExpDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public SkillupgradeExpDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int countByExample(SkillupgradeExpExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_skillupgrade_exp.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int deleteByExample(SkillupgradeExpExample example) {
		int rows = getSqlMapClientTemplate().delete("t_skillupgrade_exp.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		SkillupgradeExp key = new SkillupgradeExp();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_skillupgrade_exp.ibatorgenerated_deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public void insert(SkillupgradeExp record) {
		getSqlMapClientTemplate().insert("t_skillupgrade_exp.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public void insertSelective(SkillupgradeExp record) {
		getSqlMapClientTemplate().insert("t_skillupgrade_exp.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public List selectByExample(SkillupgradeExpExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_skillupgrade_exp.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public SkillupgradeExp selectByPrimaryKey(Integer id) {
		SkillupgradeExp key = new SkillupgradeExp();
		key.setId(id);
		SkillupgradeExp record = (SkillupgradeExp) getSqlMapClientTemplate().queryForObject(
				"t_skillupgrade_exp.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int updateByExampleSelective(SkillupgradeExp record, SkillupgradeExpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_skillupgrade_exp.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int updateByExample(SkillupgradeExp record, SkillupgradeExpExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_skillupgrade_exp.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int updateByPrimaryKeySelective(SkillupgradeExp record) {
		int rows = getSqlMapClientTemplate().update(
				"t_skillupgrade_exp.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	public int updateByPrimaryKey(SkillupgradeExp record) {
		int rows = getSqlMapClientTemplate().update("t_skillupgrade_exp.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	private static class UpdateByExampleParms extends SkillupgradeExpExample {
		private Object record;
		public UpdateByExampleParms(Object record, SkillupgradeExpExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
