package net.snake.dao.channel;

import java.util.List;

import net.snake.dao.channel.Channel;
import net.snake.dao.channel.ChannelExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ChannelDAOImpl extends SqlMapClientDaoSupport implements ChannelDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public ChannelDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int countByExample(ChannelExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_channel.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int deleteByExample(ChannelExample example) {
		int rows = getSqlMapClientTemplate().delete("t_channel.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int deleteByPrimaryKey(Integer id) {
		Channel key = new Channel();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_channel.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public void insert(Channel record) {
		getSqlMapClientTemplate().insert("t_channel.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public void insertSelective(Channel record) {
		getSqlMapClientTemplate().insert("t_channel.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public List selectByExample(ChannelExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_channel.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public Channel selectByPrimaryKey(Integer id) {
		Channel key = new Channel();
		key.setId(id);
		Channel record = (Channel) getSqlMapClientTemplate().queryForObject(
				"t_channel.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int updateByExampleSelective(Channel record, ChannelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_channel.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int updateByExample(Channel record, ChannelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_channel.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int updateByPrimaryKeySelective(Channel record) {
		int rows = getSqlMapClientTemplate().update("t_channel.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public int updateByPrimaryKey(Channel record) {
		int rows = getSqlMapClientTemplate().update("t_channel.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_channel
	 */
	private static class UpdateByExampleParms extends ChannelExample {
		private Object record;
		public UpdateByExampleParms(Object record, ChannelExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
