package net.snake.dao.goodmodelv2;

import java.util.List;

import net.snake.dao.goodmodelv2.GoodModelV2;
import net.snake.dao.goodmodelv2.GoodModelV2Example;

public interface GoodModelV2DAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int countByExample(GoodModelV2Example example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int deleteByExample(GoodModelV2Example example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	void insert(GoodModelV2 record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	void insertSelective(GoodModelV2 record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	List selectByExample(GoodModelV2Example example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	GoodModelV2 selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int updateByExampleSelective(GoodModelV2 record, GoodModelV2Example example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int updateByExample(GoodModelV2 record, GoodModelV2Example example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int updateByPrimaryKeySelective(GoodModelV2 record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	int updateByPrimaryKey(GoodModelV2 record);
}
