package net.snake.dao.sound;

import java.util.List;

import net.snake.dao.sound.Sound;
import net.snake.dao.sound.SoundExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SoundDAOImpl extends SqlMapClientDaoSupport implements SoundDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public SoundDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int countByExample(SoundExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_sound.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int deleteByExample(SoundExample example) {
        int rows = getSqlMapClientTemplate().delete("t_sound.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int deleteByPrimaryKey(Integer id) {
        Sound key = new Sound();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_sound.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public void insert(Sound record) {
        getSqlMapClientTemplate().insert("t_sound.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public void insertSelective(Sound record) {
        getSqlMapClientTemplate().insert("t_sound.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public List selectByExample(SoundExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_sound.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public Sound selectByPrimaryKey(Integer id) {
        Sound key = new Sound();
        key.setId(id);
        Sound record = (Sound) getSqlMapClientTemplate().queryForObject("t_sound.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int updateByExampleSelective(Sound record, SoundExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sound.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int updateByExample(Sound record, SoundExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_sound.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int updateByPrimaryKeySelective(Sound record) {
        int rows = getSqlMapClientTemplate().update("t_sound.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    public int updateByPrimaryKey(Sound record) {
        int rows = getSqlMapClientTemplate().update("t_sound.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_sound
     *
     * @ibatorgenerated Mon Nov 29 08:46:29 GMT 2010
     */
    private static class UpdateByExampleParms extends SoundExample {
        private Object record;

        public UpdateByExampleParms(Object record, SoundExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<Sound> getSoundList() {
	      List list = getSqlMapClientTemplate().queryForList("t_sound.getSoundIn");
	      return list;
	}

	@Override
	public List<Sound> getSoundMP3() {
		 List list = getSqlMapClientTemplate().queryForList("t_sound.getSoundIn_t_map");
	      return list;
	}
}
