package net.snake.dao.transport2;

import java.util.List;

import net.snake.dao.transport2.Transport2;
import net.snake.dao.transport2.Transport2Example;

public interface Transport2DAO {
    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int countByExample(Transport2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int deleteByExample(Transport2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int deleteByPrimaryKey(Integer transportId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    void insert(Transport2 record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    void insertSelective(Transport2 record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    List selectByExample(Transport2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    Transport2 selectByPrimaryKey(Integer transportId);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int updateByExampleSelective(Transport2 record, Transport2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int updateByExample(Transport2 record, Transport2Example example);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int updateByPrimaryKeySelective(Transport2 record);

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    int updateByPrimaryKey(Transport2 record);
}
