package net.snake.dao.monstermodel;

import java.util.List;

import net.snake.dao.monstermodel.MonsterModel;
import net.snake.dao.monstermodel.MonsterModelExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MonsterModelDAOImpl extends SqlMapClientDaoSupport implements MonsterModelDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public MonsterModelDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int countByExample(MonsterModelExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_monster_model.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int deleteByExample(MonsterModelExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("t_monster_model.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		MonsterModel key = new MonsterModel();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_monster_model.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public void insert(MonsterModel record) {
		getSqlMapClientTemplate().insert("t_monster_model.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public void insertSelective(MonsterModel record) {
		getSqlMapClientTemplate().insert("t_monster_model.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public List selectByExample(MonsterModelExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_monster_model.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public MonsterModel selectByPrimaryKey(Integer id) {
		MonsterModel key = new MonsterModel();
		key.setId(id);
		MonsterModel record = (MonsterModel) getSqlMapClientTemplate().queryForObject(
				"t_monster_model.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int updateByExampleSelective(MonsterModel record, MonsterModelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_monster_model.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int updateByExample(MonsterModel record, MonsterModelExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_monster_model.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int updateByPrimaryKeySelective(MonsterModel record) {
		int rows = getSqlMapClientTemplate().update(
				"t_monster_model.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	public int updateByPrimaryKey(MonsterModel record) {
		int rows = getSqlMapClientTemplate().update("t_monster_model.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_monster_model
	 * @ibatorgenerated  Thu May 05 17:50:50 CST 2011
	 */
	private static class UpdateByExampleParms extends MonsterModelExample {
		private Object record;
		public UpdateByExampleParms(Object record, MonsterModelExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
