package net.snake.dao.resicon;


import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import net.snake.dao.resicon.Resicon;
import net.snake.dao.resicon.ResiconExample;

public class ResiconDAOImpl extends SqlMapClientDaoSupport implements ResiconDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public ResiconDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int countByExample(ResiconExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_res_icon.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int deleteByExample(ResiconExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"t_res_icon.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int deleteByPrimaryKey(Integer id) {
		Resicon key = new Resicon();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"t_res_icon.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public void insert(Resicon record) {
		getSqlMapClientTemplate().insert("t_res_icon.ibatorgenerated_insert",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public void insertSelective(Resicon record) {
		getSqlMapClientTemplate().insert(
				"t_res_icon.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public List selectByExample(ResiconExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_res_icon.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public Resicon selectByPrimaryKey(Integer id) {
		Resicon key = new Resicon();
		key.setId(id);
		Resicon record = (Resicon) getSqlMapClientTemplate().queryForObject(
				"t_res_icon.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int updateByExampleSelective(Resicon record, ResiconExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_res_icon.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int updateByExample(Resicon record, ResiconExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_res_icon.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int updateByPrimaryKeySelective(Resicon record) {
		int rows = getSqlMapClientTemplate().update(
				"t_res_icon.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	public int updateByPrimaryKey(Resicon record) {
		int rows = getSqlMapClientTemplate().update(
				"t_res_icon.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_res_icon
	 * @ibatorgenerated  Thu Oct 28 02:06:27 GMT 2010
	 */
	private static class UpdateByExampleParms extends ResiconExample {
		private Object record;

		public UpdateByExampleParms(Object record, ResiconExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Resicon> getLianHeChaXun(int type) {
		if(type==0){
		return getSqlMapClientTemplate().queryForList("t_res_icon.selectlianhechaxun");
		}else {
		return getSqlMapClientTemplate().queryForList("t_res_icon.selectlianhechaxunbig");
		}
	}
}
