package net.snake.dao.npc;

import java.util.List;

import net.snake.dao.npc.NPC;
import net.snake.dao.npc.NPCExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class NPCDAOImpl extends SqlMapClientDaoSupport implements NPCDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public NPCDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int countByExample(NPCExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_npc.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int deleteByExample(NPCExample example) {
		int rows = getSqlMapClientTemplate().delete("t_npc.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		NPC key = new NPC();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_npc.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public void insert(NPC record) {
		getSqlMapClientTemplate().insert("t_npc.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public void insertSelective(NPC record) {
		getSqlMapClientTemplate().insert("t_npc.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public List selectByExample(NPCExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_npc.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public NPC selectByPrimaryKey(Integer id) {
		NPC key = new NPC();
		key.setId(id);
		NPC record = (NPC) getSqlMapClientTemplate().queryForObject(
				"t_npc.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int updateByExampleSelective(NPC record, NPCExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_npc.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int updateByExample(NPC record, NPCExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_npc.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int updateByPrimaryKeySelective(NPC record) {
		int rows = getSqlMapClientTemplate().update("t_npc.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	public int updateByPrimaryKey(NPC record) {
		int rows = getSqlMapClientTemplate().update("t_npc.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_npc
	 * @ibatorgenerated  Fri May 06 16:57:44 CST 2011
	 */
	private static class UpdateByExampleParms extends NPCExample {
		private Object record;
		public UpdateByExampleParms(Object record, NPCExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
