package net.snake.dao.skill;

import java.util.List;

import net.snake.dao.skill.Skill;
import net.snake.dao.skill.SkillExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SkillDAOImpl extends SqlMapClientDaoSupport implements SkillDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public SkillDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int countByExample(SkillExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_skill.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int deleteByExample(SkillExample example) {
		int rows = getSqlMapClientTemplate().delete("t_skill.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Skill key = new Skill();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_skill.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public void insert(Skill record) {
		getSqlMapClientTemplate().insert("t_skill.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public void insertSelective(Skill record) {
		getSqlMapClientTemplate().insert("t_skill.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public List selectByExample(SkillExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_skill.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public Skill selectByPrimaryKey(Integer id) {
		Skill key = new Skill();
		key.setId(id);
		Skill record = (Skill) getSqlMapClientTemplate().queryForObject(
				"t_skill.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int updateByExampleSelective(Skill record, SkillExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_skill.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int updateByExample(Skill record, SkillExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_skill.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int updateByPrimaryKeySelective(Skill record) {
		int rows = getSqlMapClientTemplate().update("t_skill.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public int updateByPrimaryKey(Skill record) {
		int rows = getSqlMapClientTemplate().update("t_skill.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	private static class UpdateByExampleParms extends SkillExample {
		private Object record;
		public UpdateByExampleParms(Object record, SkillExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
