package net.snake.dao.skillupgradeexp;

import java.util.List;

import net.snake.dao.skillupgradeexp.SkillupgradeExp;
import net.snake.dao.skillupgradeexp.SkillupgradeExpExample;

public interface SkillupgradeExpDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int countByExample(SkillupgradeExpExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int deleteByExample(SkillupgradeExpExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	void insert(SkillupgradeExp record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	void insertSelective(SkillupgradeExp record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	List selectByExample(SkillupgradeExpExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	SkillupgradeExp selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int updateByExampleSelective(SkillupgradeExp record, SkillupgradeExpExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int updateByExample(SkillupgradeExp record, SkillupgradeExpExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int updateByPrimaryKeySelective(SkillupgradeExp record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skillupgrade_exp
	 * @ibatorgenerated  Fri May 06 17:22:36 CST 2011
	 */
	int updateByPrimaryKey(SkillupgradeExp record);
}
