package net.snake.dao.shopshengwang;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ShopShengWangExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public ShopShengWangExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	protected ShopShengWangExample(ShopShengWangExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_shop_shengwang
	 * @ibatorgenerated  Wed Jul 20 10:32:56 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}
		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}
		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}
		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}
		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}
		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}
		public Criteria andIdIsNull() {
			addCriterion("f_id is null");
			return this;
		}
		public Criteria andIdIsNotNull() {
			addCriterion("f_id is not null");
			return this;
		}
		public Criteria andIdEqualTo(Integer value) {
			addCriterion("f_id =", value, "id");
			return this;
		}
		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("f_id <>", value, "id");
			return this;
		}
		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("f_id >", value, "id");
			return this;
		}
		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_id >=", value, "id");
			return this;
		}
		public Criteria andIdLessThan(Integer value) {
			addCriterion("f_id <", value, "id");
			return this;
		}
		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_id <=", value, "id");
			return this;
		}
		public Criteria andIdIn(List values) {
			addCriterion("f_id in", values, "id");
			return this;
		}
		public Criteria andIdNotIn(List values) {
			addCriterion("f_id not in", values, "id");
			return this;
		}
		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("f_id between", value1, value2, "id");
			return this;
		}
		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_id not between", value1, value2, "id");
			return this;
		}
		public Criteria andGoodsTypeIsNull() {
			addCriterion("f_goods_type is null");
			return this;
		}
		public Criteria andGoodsTypeIsNotNull() {
			addCriterion("f_goods_type is not null");
			return this;
		}
		public Criteria andGoodsTypeEqualTo(Integer value) {
			addCriterion("f_goods_type =", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeNotEqualTo(Integer value) {
			addCriterion("f_goods_type <>", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeGreaterThan(Integer value) {
			addCriterion("f_goods_type >", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_goods_type >=", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeLessThan(Integer value) {
			addCriterion("f_goods_type <", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_goods_type <=", value, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeIn(List values) {
			addCriterion("f_goods_type in", values, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeNotIn(List values) {
			addCriterion("f_goods_type not in", values, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeBetween(Integer value1, Integer value2) {
			addCriterion("f_goods_type between", value1, value2, "goodsType");
			return this;
		}
		public Criteria andGoodsTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_goods_type not between", value1, value2, "goodsType");
			return this;
		}
		public Criteria andGoodmodelIdIsNull() {
			addCriterion("f_goodmodel_id is null");
			return this;
		}
		public Criteria andGoodmodelIdIsNotNull() {
			addCriterion("f_goodmodel_id is not null");
			return this;
		}
		public Criteria andGoodmodelIdEqualTo(Integer value) {
			addCriterion("f_goodmodel_id =", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotEqualTo(Integer value) {
			addCriterion("f_goodmodel_id <>", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdGreaterThan(Integer value) {
			addCriterion("f_goodmodel_id >", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_goodmodel_id >=", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdLessThan(Integer value) {
			addCriterion("f_goodmodel_id <", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_goodmodel_id <=", value, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdIn(List values) {
			addCriterion("f_goodmodel_id in", values, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotIn(List values) {
			addCriterion("f_goodmodel_id not in", values, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdBetween(Integer value1, Integer value2) {
			addCriterion("f_goodmodel_id between", value1, value2, "goodmodelId");
			return this;
		}
		public Criteria andGoodmodelIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_goodmodel_id not between", value1, value2, "goodmodelId");
			return this;
		}
		public Criteria andSaleTypeIsNull() {
			addCriterion("f_sale_type is null");
			return this;
		}
		public Criteria andSaleTypeIsNotNull() {
			addCriterion("f_sale_type is not null");
			return this;
		}
		public Criteria andSaleTypeEqualTo(Integer value) {
			addCriterion("f_sale_type =", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeNotEqualTo(Integer value) {
			addCriterion("f_sale_type <>", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeGreaterThan(Integer value) {
			addCriterion("f_sale_type >", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_sale_type >=", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeLessThan(Integer value) {
			addCriterion("f_sale_type <", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_sale_type <=", value, "saleType");
			return this;
		}
		public Criteria andSaleTypeIn(List values) {
			addCriterion("f_sale_type in", values, "saleType");
			return this;
		}
		public Criteria andSaleTypeNotIn(List values) {
			addCriterion("f_sale_type not in", values, "saleType");
			return this;
		}
		public Criteria andSaleTypeBetween(Integer value1, Integer value2) {
			addCriterion("f_sale_type between", value1, value2, "saleType");
			return this;
		}
		public Criteria andSaleTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_sale_type not between", value1, value2, "saleType");
			return this;
		}
		public Criteria andGoodsPriceIsNull() {
			addCriterion("f_goods_price is null");
			return this;
		}
		public Criteria andGoodsPriceIsNotNull() {
			addCriterion("f_goods_price is not null");
			return this;
		}
		public Criteria andGoodsPriceEqualTo(Integer value) {
			addCriterion("f_goods_price =", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceNotEqualTo(Integer value) {
			addCriterion("f_goods_price <>", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceGreaterThan(Integer value) {
			addCriterion("f_goods_price >", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_goods_price >=", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceLessThan(Integer value) {
			addCriterion("f_goods_price <", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceLessThanOrEqualTo(Integer value) {
			addCriterion("f_goods_price <=", value, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceIn(List values) {
			addCriterion("f_goods_price in", values, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceNotIn(List values) {
			addCriterion("f_goods_price not in", values, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceBetween(Integer value1, Integer value2) {
			addCriterion("f_goods_price between", value1, value2, "goodsPrice");
			return this;
		}
		public Criteria andGoodsPriceNotBetween(Integer value1, Integer value2) {
			addCriterion("f_goods_price not between", value1, value2, "goodsPrice");
			return this;
		}
		public Criteria andLastDateIsNull() {
			addCriterion("f_last_date is null");
			return this;
		}
		public Criteria andLastDateIsNotNull() {
			addCriterion("f_last_date is not null");
			return this;
		}
		public Criteria andLastDateEqualTo(Integer value) {
			addCriterion("f_last_date =", value, "lastDate");
			return this;
		}
		public Criteria andLastDateNotEqualTo(Integer value) {
			addCriterion("f_last_date <>", value, "lastDate");
			return this;
		}
		public Criteria andLastDateGreaterThan(Integer value) {
			addCriterion("f_last_date >", value, "lastDate");
			return this;
		}
		public Criteria andLastDateGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_last_date >=", value, "lastDate");
			return this;
		}
		public Criteria andLastDateLessThan(Integer value) {
			addCriterion("f_last_date <", value, "lastDate");
			return this;
		}
		public Criteria andLastDateLessThanOrEqualTo(Integer value) {
			addCriterion("f_last_date <=", value, "lastDate");
			return this;
		}
		public Criteria andLastDateIn(List values) {
			addCriterion("f_last_date in", values, "lastDate");
			return this;
		}
		public Criteria andLastDateNotIn(List values) {
			addCriterion("f_last_date not in", values, "lastDate");
			return this;
		}
		public Criteria andLastDateBetween(Integer value1, Integer value2) {
			addCriterion("f_last_date between", value1, value2, "lastDate");
			return this;
		}
		public Criteria andLastDateNotBetween(Integer value1, Integer value2) {
			addCriterion("f_last_date not between", value1, value2, "lastDate");
			return this;
		}
		public Criteria andIsBindIsNull() {
			addCriterion("f_is_bind is null");
			return this;
		}
		public Criteria andIsBindIsNotNull() {
			addCriterion("f_is_bind is not null");
			return this;
		}
		public Criteria andIsBindEqualTo(Integer value) {
			addCriterion("f_is_bind =", value, "isBind");
			return this;
		}
		public Criteria andIsBindNotEqualTo(Integer value) {
			addCriterion("f_is_bind <>", value, "isBind");
			return this;
		}
		public Criteria andIsBindGreaterThan(Integer value) {
			addCriterion("f_is_bind >", value, "isBind");
			return this;
		}
		public Criteria andIsBindGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_is_bind >=", value, "isBind");
			return this;
		}
		public Criteria andIsBindLessThan(Integer value) {
			addCriterion("f_is_bind <", value, "isBind");
			return this;
		}
		public Criteria andIsBindLessThanOrEqualTo(Integer value) {
			addCriterion("f_is_bind <=", value, "isBind");
			return this;
		}
		public Criteria andIsBindIn(List values) {
			addCriterion("f_is_bind in", values, "isBind");
			return this;
		}
		public Criteria andIsBindNotIn(List values) {
			addCriterion("f_is_bind not in", values, "isBind");
			return this;
		}
		public Criteria andIsBindBetween(Integer value1, Integer value2) {
			addCriterion("f_is_bind between", value1, value2, "isBind");
			return this;
		}
		public Criteria andIsBindNotBetween(Integer value1, Integer value2) {
			addCriterion("f_is_bind not between", value1, value2, "isBind");
			return this;
		}
		public Criteria andIsEnableIsNull() {
			addCriterion("f_is_enable is null");
			return this;
		}
		public Criteria andIsEnableIsNotNull() {
			addCriterion("f_is_enable is not null");
			return this;
		}
		public Criteria andIsEnableEqualTo(Integer value) {
			addCriterion("f_is_enable =", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableNotEqualTo(Integer value) {
			addCriterion("f_is_enable <>", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableGreaterThan(Integer value) {
			addCriterion("f_is_enable >", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_is_enable >=", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableLessThan(Integer value) {
			addCriterion("f_is_enable <", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableLessThanOrEqualTo(Integer value) {
			addCriterion("f_is_enable <=", value, "isEnable");
			return this;
		}
		public Criteria andIsEnableIn(List values) {
			addCriterion("f_is_enable in", values, "isEnable");
			return this;
		}
		public Criteria andIsEnableNotIn(List values) {
			addCriterion("f_is_enable not in", values, "isEnable");
			return this;
		}
		public Criteria andIsEnableBetween(Integer value1, Integer value2) {
			addCriterion("f_is_enable between", value1, value2, "isEnable");
			return this;
		}
		public Criteria andIsEnableNotBetween(Integer value1, Integer value2) {
			addCriterion("f_is_enable not between", value1, value2, "isEnable");
			return this;
		}
		public Criteria andAdditionDescIsNull() {
			addCriterion("f_addition_desc is null");
			return this;
		}
		public Criteria andAdditionDescIsNotNull() {
			addCriterion("f_addition_desc is not null");
			return this;
		}
		public Criteria andAdditionDescEqualTo(String value) {
			addCriterion("f_addition_desc =", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescNotEqualTo(String value) {
			addCriterion("f_addition_desc <>", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescGreaterThan(String value) {
			addCriterion("f_addition_desc >", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_addition_desc >=", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescLessThan(String value) {
			addCriterion("f_addition_desc <", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescLessThanOrEqualTo(String value) {
			addCriterion("f_addition_desc <=", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescLike(String value) {
			addCriterion("f_addition_desc like", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescNotLike(String value) {
			addCriterion("f_addition_desc not like", value, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescIn(List values) {
			addCriterion("f_addition_desc in", values, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescNotIn(List values) {
			addCriterion("f_addition_desc not in", values, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescBetween(String value1, String value2) {
			addCriterion("f_addition_desc between", value1, value2, "additionDesc");
			return this;
		}
		public Criteria andAdditionDescNotBetween(String value1, String value2) {
			addCriterion("f_addition_desc not between", value1, value2, "additionDesc");
			return this;
		}
		public Criteria andStrengthenDescIsNull() {
			addCriterion("f_strengthen_desc is null");
			return this;
		}
		public Criteria andStrengthenDescIsNotNull() {
			addCriterion("f_strengthen_desc is not null");
			return this;
		}
		public Criteria andStrengthenDescEqualTo(String value) {
			addCriterion("f_strengthen_desc =", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescNotEqualTo(String value) {
			addCriterion("f_strengthen_desc <>", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescGreaterThan(String value) {
			addCriterion("f_strengthen_desc >", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_strengthen_desc >=", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescLessThan(String value) {
			addCriterion("f_strengthen_desc <", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescLessThanOrEqualTo(String value) {
			addCriterion("f_strengthen_desc <=", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescLike(String value) {
			addCriterion("f_strengthen_desc like", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescNotLike(String value) {
			addCriterion("f_strengthen_desc not like", value, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescIn(List values) {
			addCriterion("f_strengthen_desc in", values, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescNotIn(List values) {
			addCriterion("f_strengthen_desc not in", values, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescBetween(String value1, String value2) {
			addCriterion("f_strengthen_desc between", value1, value2, "strengthenDesc");
			return this;
		}
		public Criteria andStrengthenDescNotBetween(String value1, String value2) {
			addCriterion("f_strengthen_desc not between", value1, value2, "strengthenDesc");
			return this;
		}
		public Criteria andDescIsNull() {
			addCriterion("f_desc is null");
			return this;
		}
		public Criteria andDescIsNotNull() {
			addCriterion("f_desc is not null");
			return this;
		}
		public Criteria andDescEqualTo(String value) {
			addCriterion("f_desc =", value, "desc");
			return this;
		}
		public Criteria andDescNotEqualTo(String value) {
			addCriterion("f_desc <>", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThan(String value) {
			addCriterion("f_desc >", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc >=", value, "desc");
			return this;
		}
		public Criteria andDescLessThan(String value) {
			addCriterion("f_desc <", value, "desc");
			return this;
		}
		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("f_desc <=", value, "desc");
			return this;
		}
		public Criteria andDescLike(String value) {
			addCriterion("f_desc like", value, "desc");
			return this;
		}
		public Criteria andDescNotLike(String value) {
			addCriterion("f_desc not like", value, "desc");
			return this;
		}
		public Criteria andDescIn(List values) {
			addCriterion("f_desc in", values, "desc");
			return this;
		}
		public Criteria andDescNotIn(List values) {
			addCriterion("f_desc not in", values, "desc");
			return this;
		}
		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("f_desc between", value1, value2, "desc");
			return this;
		}
		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("f_desc not between", value1, value2, "desc");
			return this;
		}
		public Criteria andDescI18nIsNull() {
			addCriterion("f_desc_i18n is null");
			return this;
		}
		public Criteria andDescI18nIsNotNull() {
			addCriterion("f_desc_i18n is not null");
			return this;
		}
		public Criteria andDescI18nEqualTo(String value) {
			addCriterion("f_desc_i18n =", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotEqualTo(String value) {
			addCriterion("f_desc_i18n <>", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThan(String value) {
			addCriterion("f_desc_i18n >", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n >=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThan(String value) {
			addCriterion("f_desc_i18n <", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n <=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLike(String value) {
			addCriterion("f_desc_i18n like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotLike(String value) {
			addCriterion("f_desc_i18n not like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nIn(List values) {
			addCriterion("f_desc_i18n in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotIn(List values) {
			addCriterion("f_desc_i18n not in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nBetween(String value1, String value2) {
			addCriterion("f_desc_i18n between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotBetween(String value1, String value2) {
			addCriterion("f_desc_i18n not between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andUseDescIsNull() {
			addCriterion("f_use_desc is null");
			return this;
		}
		public Criteria andUseDescIsNotNull() {
			addCriterion("f_use_desc is not null");
			return this;
		}
		public Criteria andUseDescEqualTo(String value) {
			addCriterion("f_use_desc =", value, "useDesc");
			return this;
		}
		public Criteria andUseDescNotEqualTo(String value) {
			addCriterion("f_use_desc <>", value, "useDesc");
			return this;
		}
		public Criteria andUseDescGreaterThan(String value) {
			addCriterion("f_use_desc >", value, "useDesc");
			return this;
		}
		public Criteria andUseDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_use_desc >=", value, "useDesc");
			return this;
		}
		public Criteria andUseDescLessThan(String value) {
			addCriterion("f_use_desc <", value, "useDesc");
			return this;
		}
		public Criteria andUseDescLessThanOrEqualTo(String value) {
			addCriterion("f_use_desc <=", value, "useDesc");
			return this;
		}
		public Criteria andUseDescLike(String value) {
			addCriterion("f_use_desc like", value, "useDesc");
			return this;
		}
		public Criteria andUseDescNotLike(String value) {
			addCriterion("f_use_desc not like", value, "useDesc");
			return this;
		}
		public Criteria andUseDescIn(List values) {
			addCriterion("f_use_desc in", values, "useDesc");
			return this;
		}
		public Criteria andUseDescNotIn(List values) {
			addCriterion("f_use_desc not in", values, "useDesc");
			return this;
		}
		public Criteria andUseDescBetween(String value1, String value2) {
			addCriterion("f_use_desc between", value1, value2, "useDesc");
			return this;
		}
		public Criteria andUseDescNotBetween(String value1, String value2) {
			addCriterion("f_use_desc not between", value1, value2, "useDesc");
			return this;
		}
		public Criteria andUseDescI18nIsNull() {
			addCriterion("f_use_desc_i18n is null");
			return this;
		}
		public Criteria andUseDescI18nIsNotNull() {
			addCriterion("f_use_desc_i18n is not null");
			return this;
		}
		public Criteria andUseDescI18nEqualTo(String value) {
			addCriterion("f_use_desc_i18n =", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nNotEqualTo(String value) {
			addCriterion("f_use_desc_i18n <>", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nGreaterThan(String value) {
			addCriterion("f_use_desc_i18n >", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_use_desc_i18n >=", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nLessThan(String value) {
			addCriterion("f_use_desc_i18n <", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nLessThanOrEqualTo(String value) {
			addCriterion("f_use_desc_i18n <=", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nLike(String value) {
			addCriterion("f_use_desc_i18n like", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nNotLike(String value) {
			addCriterion("f_use_desc_i18n not like", value, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nIn(List values) {
			addCriterion("f_use_desc_i18n in", values, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nNotIn(List values) {
			addCriterion("f_use_desc_i18n not in", values, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nBetween(String value1, String value2) {
			addCriterion("f_use_desc_i18n between", value1, value2, "useDescI18n");
			return this;
		}
		public Criteria andUseDescI18nNotBetween(String value1, String value2) {
			addCriterion("f_use_desc_i18n not between", value1, value2, "useDescI18n");
			return this;
		}
	}
}
