package net.snake.dao.equipmentplayconfig;

import java.util.List;

import net.snake.dao.equipmentplayconfig.EquipmentPlayconfig;
import net.snake.dao.equipmentplayconfig.EquipmentPlayconfigExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EquipmentPlayconfigDAOImpl extends SqlMapClientDaoSupport implements EquipmentPlayconfigDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public EquipmentPlayconfigDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int countByExample(EquipmentPlayconfigExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_equipment_playconfig.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int deleteByExample(EquipmentPlayconfigExample example) {
		int rows = getSqlMapClientTemplate().delete("t_equipment_playconfig.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int deleteByPrimaryKey(Integer scheme) {
		EquipmentPlayconfig key = new EquipmentPlayconfig();
		key.setScheme(scheme);
		int rows = getSqlMapClientTemplate().delete(
				"t_equipment_playconfig.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public void insert(EquipmentPlayconfig record) {
		getSqlMapClientTemplate().insert("t_equipment_playconfig.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public void insertSelective(EquipmentPlayconfig record) {
		getSqlMapClientTemplate().insert("t_equipment_playconfig.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public List selectByExample(EquipmentPlayconfigExample example) {
		List list = getSqlMapClientTemplate().queryForList(
				"t_equipment_playconfig.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public EquipmentPlayconfig selectByPrimaryKey(Integer scheme) {
		EquipmentPlayconfig key = new EquipmentPlayconfig();
		key.setScheme(scheme);
		EquipmentPlayconfig record = (EquipmentPlayconfig) getSqlMapClientTemplate().queryForObject(
				"t_equipment_playconfig.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int updateByExampleSelective(EquipmentPlayconfig record, EquipmentPlayconfigExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_equipment_playconfig.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int updateByExample(EquipmentPlayconfig record, EquipmentPlayconfigExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_equipment_playconfig.ibatorgenerated_updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int updateByPrimaryKeySelective(EquipmentPlayconfig record) {
		int rows = getSqlMapClientTemplate().update(
				"t_equipment_playconfig.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	public int updateByPrimaryKey(EquipmentPlayconfig record) {
		int rows = getSqlMapClientTemplate().update(
				"t_equipment_playconfig.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_equipment_playconfig
	 * @ibatorgenerated  Mon Feb 28 09:09:57 GMT 2011
	 */
	private static class UpdateByExampleParms extends EquipmentPlayconfigExample {
		private Object record;
		public UpdateByExampleParms(Object record, EquipmentPlayconfigExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
