package net.snake.dao.map;

import java.util.List;

import net.snake.dao.map.Map;
import net.snake.dao.map.MapExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class MapDAOImpl extends SqlMapClientDaoSupport implements MapDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public MapDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int countByExample(MapExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_map.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int deleteByExample(MapExample example) {
		int rows = getSqlMapClientTemplate().delete("t_map.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int deleteByPrimaryKey(Integer mapId) {
		Map key = new Map();
		key.setMapId(mapId);
		int rows = getSqlMapClientTemplate().delete("t_map.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public void insert(Map record) {
		getSqlMapClientTemplate().insert("t_map.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public void insertSelective(Map record) {
		getSqlMapClientTemplate().insert("t_map.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public List selectByExample(MapExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_map.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public Map selectByPrimaryKey(Integer mapId) {
		Map key = new Map();
		key.setMapId(mapId);
		Map record = (Map) getSqlMapClientTemplate().queryForObject(
				"t_map.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int updateByExampleSelective(Map record, MapExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_map.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int updateByExample(Map record, MapExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_map.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int updateByPrimaryKeySelective(Map record) {
		int rows = getSqlMapClientTemplate().update("t_map.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	public int updateByPrimaryKey(Map record) {
		int rows = getSqlMapClientTemplate().update("t_map.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_map
	 * @ibatorgenerated  Fri May 06 14:32:06 CST 2011
	 */
	private static class UpdateByExampleParms extends MapExample {
		private Object record;
		public UpdateByExampleParms(Object record, MapExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
