package net.snake.dao.skill;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class SkillExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public SkillExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	protected SkillExample(SkillExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_skill
	 * @ibatorgenerated  Fri May 06 17:22:31 CST 2011
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}
		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}
		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}
		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}
		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}
		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}
		public Criteria andIdIsNull() {
			addCriterion("f_id is null");
			return this;
		}
		public Criteria andIdIsNotNull() {
			addCriterion("f_id is not null");
			return this;
		}
		public Criteria andIdEqualTo(Integer value) {
			addCriterion("f_id =", value, "id");
			return this;
		}
		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("f_id <>", value, "id");
			return this;
		}
		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("f_id >", value, "id");
			return this;
		}
		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_id >=", value, "id");
			return this;
		}
		public Criteria andIdLessThan(Integer value) {
			addCriterion("f_id <", value, "id");
			return this;
		}
		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_id <=", value, "id");
			return this;
		}
		public Criteria andIdIn(List values) {
			addCriterion("f_id in", values, "id");
			return this;
		}
		public Criteria andIdNotIn(List values) {
			addCriterion("f_id not in", values, "id");
			return this;
		}
		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("f_id between", value1, value2, "id");
			return this;
		}
		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_id not between", value1, value2, "id");
			return this;
		}
		public Criteria andNameIsNull() {
			addCriterion("f_name is null");
			return this;
		}
		public Criteria andNameIsNotNull() {
			addCriterion("f_name is not null");
			return this;
		}
		public Criteria andNameEqualTo(String value) {
			addCriterion("f_name =", value, "name");
			return this;
		}
		public Criteria andNameNotEqualTo(String value) {
			addCriterion("f_name <>", value, "name");
			return this;
		}
		public Criteria andNameGreaterThan(String value) {
			addCriterion("f_name >", value, "name");
			return this;
		}
		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("f_name >=", value, "name");
			return this;
		}
		public Criteria andNameLessThan(String value) {
			addCriterion("f_name <", value, "name");
			return this;
		}
		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("f_name <=", value, "name");
			return this;
		}
		public Criteria andNameLike(String value) {
			addCriterion("f_name like", value, "name");
			return this;
		}
		public Criteria andNameNotLike(String value) {
			addCriterion("f_name not like", value, "name");
			return this;
		}
		public Criteria andNameIn(List values) {
			addCriterion("f_name in", values, "name");
			return this;
		}
		public Criteria andNameNotIn(List values) {
			addCriterion("f_name not in", values, "name");
			return this;
		}
		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("f_name between", value1, value2, "name");
			return this;
		}
		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("f_name not between", value1, value2, "name");
			return this;
		}
		public Criteria andImageIsNull() {
			addCriterion("f_image is null");
			return this;
		}
		public Criteria andImageIsNotNull() {
			addCriterion("f_image is not null");
			return this;
		}
		public Criteria andImageEqualTo(Integer value) {
			addCriterion("f_image =", value, "image");
			return this;
		}
		public Criteria andImageNotEqualTo(Integer value) {
			addCriterion("f_image <>", value, "image");
			return this;
		}
		public Criteria andImageGreaterThan(Integer value) {
			addCriterion("f_image >", value, "image");
			return this;
		}
		public Criteria andImageGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_image >=", value, "image");
			return this;
		}
		public Criteria andImageLessThan(Integer value) {
			addCriterion("f_image <", value, "image");
			return this;
		}
		public Criteria andImageLessThanOrEqualTo(Integer value) {
			addCriterion("f_image <=", value, "image");
			return this;
		}
		public Criteria andImageIn(List values) {
			addCriterion("f_image in", values, "image");
			return this;
		}
		public Criteria andImageNotIn(List values) {
			addCriterion("f_image not in", values, "image");
			return this;
		}
		public Criteria andImageBetween(Integer value1, Integer value2) {
			addCriterion("f_image between", value1, value2, "image");
			return this;
		}
		public Criteria andImageNotBetween(Integer value1, Integer value2) {
			addCriterion("f_image not between", value1, value2, "image");
			return this;
		}
		public Criteria andCoolingtimeIsNull() {
			addCriterion("f_coolingtime is null");
			return this;
		}
		public Criteria andCoolingtimeIsNotNull() {
			addCriterion("f_coolingtime is not null");
			return this;
		}
		public Criteria andCoolingtimeEqualTo(Integer value) {
			addCriterion("f_coolingtime =", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeNotEqualTo(Integer value) {
			addCriterion("f_coolingtime <>", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeGreaterThan(Integer value) {
			addCriterion("f_coolingtime >", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_coolingtime >=", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeLessThan(Integer value) {
			addCriterion("f_coolingtime <", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeLessThanOrEqualTo(Integer value) {
			addCriterion("f_coolingtime <=", value, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeIn(List values) {
			addCriterion("f_coolingtime in", values, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeNotIn(List values) {
			addCriterion("f_coolingtime not in", values, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeBetween(Integer value1, Integer value2) {
			addCriterion("f_coolingtime between", value1, value2, "coolingtime");
			return this;
		}
		public Criteria andCoolingtimeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_coolingtime not between", value1, value2, "coolingtime");
			return this;
		}
		public Criteria andIscommonCdIsNull() {
			addCriterion("f_iscommon_cd is null");
			return this;
		}
		public Criteria andIscommonCdIsNotNull() {
			addCriterion("f_iscommon_cd is not null");
			return this;
		}
		public Criteria andIscommonCdEqualTo(Boolean value) {
			addCriterion("f_iscommon_cd =", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdNotEqualTo(Boolean value) {
			addCriterion("f_iscommon_cd <>", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdGreaterThan(Boolean value) {
			addCriterion("f_iscommon_cd >", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdGreaterThanOrEqualTo(Boolean value) {
			addCriterion("f_iscommon_cd >=", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdLessThan(Boolean value) {
			addCriterion("f_iscommon_cd <", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdLessThanOrEqualTo(Boolean value) {
			addCriterion("f_iscommon_cd <=", value, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdIn(List values) {
			addCriterion("f_iscommon_cd in", values, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdNotIn(List values) {
			addCriterion("f_iscommon_cd not in", values, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdBetween(Boolean value1, Boolean value2) {
			addCriterion("f_iscommon_cd between", value1, value2, "iscommonCd");
			return this;
		}
		public Criteria andIscommonCdNotBetween(Boolean value1, Boolean value2) {
			addCriterion("f_iscommon_cd not between", value1, value2, "iscommonCd");
			return this;
		}
		public Criteria andDepletionParameterIsNull() {
			addCriterion("f_depletion_parameter is null");
			return this;
		}
		public Criteria andDepletionParameterIsNotNull() {
			addCriterion("f_depletion_parameter is not null");
			return this;
		}
		public Criteria andDepletionParameterEqualTo(Byte value) {
			addCriterion("f_depletion_parameter =", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterNotEqualTo(Byte value) {
			addCriterion("f_depletion_parameter <>", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterGreaterThan(Byte value) {
			addCriterion("f_depletion_parameter >", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_depletion_parameter >=", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterLessThan(Byte value) {
			addCriterion("f_depletion_parameter <", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterLessThanOrEqualTo(Byte value) {
			addCriterion("f_depletion_parameter <=", value, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterIn(List values) {
			addCriterion("f_depletion_parameter in", values, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterNotIn(List values) {
			addCriterion("f_depletion_parameter not in", values, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterBetween(Byte value1, Byte value2) {
			addCriterion("f_depletion_parameter between", value1, value2, "depletionParameter");
			return this;
		}
		public Criteria andDepletionParameterNotBetween(Byte value1, Byte value2) {
			addCriterion("f_depletion_parameter not between", value1, value2, "depletionParameter");
			return this;
		}
		public Criteria andDepletionValueIsNull() {
			addCriterion("f_depletion_value is null");
			return this;
		}
		public Criteria andDepletionValueIsNotNull() {
			addCriterion("f_depletion_value is not null");
			return this;
		}
		public Criteria andDepletionValueEqualTo(Integer value) {
			addCriterion("f_depletion_value =", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueNotEqualTo(Integer value) {
			addCriterion("f_depletion_value <>", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueGreaterThan(Integer value) {
			addCriterion("f_depletion_value >", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_depletion_value >=", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueLessThan(Integer value) {
			addCriterion("f_depletion_value <", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueLessThanOrEqualTo(Integer value) {
			addCriterion("f_depletion_value <=", value, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueIn(List values) {
			addCriterion("f_depletion_value in", values, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueNotIn(List values) {
			addCriterion("f_depletion_value not in", values, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueBetween(Integer value1, Integer value2) {
			addCriterion("f_depletion_value between", value1, value2, "depletionValue");
			return this;
		}
		public Criteria andDepletionValueNotBetween(Integer value1, Integer value2) {
			addCriterion("f_depletion_value not between", value1, value2, "depletionValue");
			return this;
		}
		public Criteria andDistanceIsNull() {
			addCriterion("f_distance is null");
			return this;
		}
		public Criteria andDistanceIsNotNull() {
			addCriterion("f_distance is not null");
			return this;
		}
		public Criteria andDistanceEqualTo(Integer value) {
			addCriterion("f_distance =", value, "distance");
			return this;
		}
		public Criteria andDistanceNotEqualTo(Integer value) {
			addCriterion("f_distance <>", value, "distance");
			return this;
		}
		public Criteria andDistanceGreaterThan(Integer value) {
			addCriterion("f_distance >", value, "distance");
			return this;
		}
		public Criteria andDistanceGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_distance >=", value, "distance");
			return this;
		}
		public Criteria andDistanceLessThan(Integer value) {
			addCriterion("f_distance <", value, "distance");
			return this;
		}
		public Criteria andDistanceLessThanOrEqualTo(Integer value) {
			addCriterion("f_distance <=", value, "distance");
			return this;
		}
		public Criteria andDistanceIn(List values) {
			addCriterion("f_distance in", values, "distance");
			return this;
		}
		public Criteria andDistanceNotIn(List values) {
			addCriterion("f_distance not in", values, "distance");
			return this;
		}
		public Criteria andDistanceBetween(Integer value1, Integer value2) {
			addCriterion("f_distance between", value1, value2, "distance");
			return this;
		}
		public Criteria andDistanceNotBetween(Integer value1, Integer value2) {
			addCriterion("f_distance not between", value1, value2, "distance");
			return this;
		}
		public Criteria andUsewayIsNull() {
			addCriterion("f_useway is null");
			return this;
		}
		public Criteria andUsewayIsNotNull() {
			addCriterion("f_useway is not null");
			return this;
		}
		public Criteria andUsewayEqualTo(Byte value) {
			addCriterion("f_useway =", value, "useway");
			return this;
		}
		public Criteria andUsewayNotEqualTo(Byte value) {
			addCriterion("f_useway <>", value, "useway");
			return this;
		}
		public Criteria andUsewayGreaterThan(Byte value) {
			addCriterion("f_useway >", value, "useway");
			return this;
		}
		public Criteria andUsewayGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_useway >=", value, "useway");
			return this;
		}
		public Criteria andUsewayLessThan(Byte value) {
			addCriterion("f_useway <", value, "useway");
			return this;
		}
		public Criteria andUsewayLessThanOrEqualTo(Byte value) {
			addCriterion("f_useway <=", value, "useway");
			return this;
		}
		public Criteria andUsewayIn(List values) {
			addCriterion("f_useway in", values, "useway");
			return this;
		}
		public Criteria andUsewayNotIn(List values) {
			addCriterion("f_useway not in", values, "useway");
			return this;
		}
		public Criteria andUsewayBetween(Byte value1, Byte value2) {
			addCriterion("f_useway between", value1, value2, "useway");
			return this;
		}
		public Criteria andUsewayNotBetween(Byte value1, Byte value2) {
			addCriterion("f_useway not between", value1, value2, "useway");
			return this;
		}
		public Criteria andTargetIsNull() {
			addCriterion("f_target is null");
			return this;
		}
		public Criteria andTargetIsNotNull() {
			addCriterion("f_target is not null");
			return this;
		}
		public Criteria andTargetEqualTo(Byte value) {
			addCriterion("f_target =", value, "target");
			return this;
		}
		public Criteria andTargetNotEqualTo(Byte value) {
			addCriterion("f_target <>", value, "target");
			return this;
		}
		public Criteria andTargetGreaterThan(Byte value) {
			addCriterion("f_target >", value, "target");
			return this;
		}
		public Criteria andTargetGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_target >=", value, "target");
			return this;
		}
		public Criteria andTargetLessThan(Byte value) {
			addCriterion("f_target <", value, "target");
			return this;
		}
		public Criteria andTargetLessThanOrEqualTo(Byte value) {
			addCriterion("f_target <=", value, "target");
			return this;
		}
		public Criteria andTargetIn(List values) {
			addCriterion("f_target in", values, "target");
			return this;
		}
		public Criteria andTargetNotIn(List values) {
			addCriterion("f_target not in", values, "target");
			return this;
		}
		public Criteria andTargetBetween(Byte value1, Byte value2) {
			addCriterion("f_target between", value1, value2, "target");
			return this;
		}
		public Criteria andTargetNotBetween(Byte value1, Byte value2) {
			addCriterion("f_target not between", value1, value2, "target");
			return this;
		}
		public Criteria andEffectIdsIsNull() {
			addCriterion("f_effect_ids is null");
			return this;
		}
		public Criteria andEffectIdsIsNotNull() {
			addCriterion("f_effect_ids is not null");
			return this;
		}
		public Criteria andEffectIdsEqualTo(String value) {
			addCriterion("f_effect_ids =", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsNotEqualTo(String value) {
			addCriterion("f_effect_ids <>", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsGreaterThan(String value) {
			addCriterion("f_effect_ids >", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsGreaterThanOrEqualTo(String value) {
			addCriterion("f_effect_ids >=", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsLessThan(String value) {
			addCriterion("f_effect_ids <", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsLessThanOrEqualTo(String value) {
			addCriterion("f_effect_ids <=", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsLike(String value) {
			addCriterion("f_effect_ids like", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsNotLike(String value) {
			addCriterion("f_effect_ids not like", value, "effectIds");
			return this;
		}
		public Criteria andEffectIdsIn(List values) {
			addCriterion("f_effect_ids in", values, "effectIds");
			return this;
		}
		public Criteria andEffectIdsNotIn(List values) {
			addCriterion("f_effect_ids not in", values, "effectIds");
			return this;
		}
		public Criteria andEffectIdsBetween(String value1, String value2) {
			addCriterion("f_effect_ids between", value1, value2, "effectIds");
			return this;
		}
		public Criteria andEffectIdsNotBetween(String value1, String value2) {
			addCriterion("f_effect_ids not between", value1, value2, "effectIds");
			return this;
		}
		public Criteria andIsgeneralIsNull() {
			addCriterion("f_isgeneral is null");
			return this;
		}
		public Criteria andIsgeneralIsNotNull() {
			addCriterion("f_isgeneral is not null");
			return this;
		}
		public Criteria andIsgeneralEqualTo(Byte value) {
			addCriterion("f_isgeneral =", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralNotEqualTo(Byte value) {
			addCriterion("f_isgeneral <>", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralGreaterThan(Byte value) {
			addCriterion("f_isgeneral >", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_isgeneral >=", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralLessThan(Byte value) {
			addCriterion("f_isgeneral <", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralLessThanOrEqualTo(Byte value) {
			addCriterion("f_isgeneral <=", value, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralIn(List values) {
			addCriterion("f_isgeneral in", values, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralNotIn(List values) {
			addCriterion("f_isgeneral not in", values, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralBetween(Byte value1, Byte value2) {
			addCriterion("f_isgeneral between", value1, value2, "isgeneral");
			return this;
		}
		public Criteria andIsgeneralNotBetween(Byte value1, Byte value2) {
			addCriterion("f_isgeneral not between", value1, value2, "isgeneral");
			return this;
		}
		public Criteria andCharLevelIsNull() {
			addCriterion("f_char_level is null");
			return this;
		}
		public Criteria andCharLevelIsNotNull() {
			addCriterion("f_char_level is not null");
			return this;
		}
		public Criteria andCharLevelEqualTo(Byte value) {
			addCriterion("f_char_level =", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelNotEqualTo(Byte value) {
			addCriterion("f_char_level <>", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelGreaterThan(Byte value) {
			addCriterion("f_char_level >", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_char_level >=", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelLessThan(Byte value) {
			addCriterion("f_char_level <", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelLessThanOrEqualTo(Byte value) {
			addCriterion("f_char_level <=", value, "charLevel");
			return this;
		}
		public Criteria andCharLevelIn(List values) {
			addCriterion("f_char_level in", values, "charLevel");
			return this;
		}
		public Criteria andCharLevelNotIn(List values) {
			addCriterion("f_char_level not in", values, "charLevel");
			return this;
		}
		public Criteria andCharLevelBetween(Byte value1, Byte value2) {
			addCriterion("f_char_level between", value1, value2, "charLevel");
			return this;
		}
		public Criteria andCharLevelNotBetween(Byte value1, Byte value2) {
			addCriterion("f_char_level not between", value1, value2, "charLevel");
			return this;
		}
		public Criteria andPopsingerIsNull() {
			addCriterion("f_popsinger is null");
			return this;
		}
		public Criteria andPopsingerIsNotNull() {
			addCriterion("f_popsinger is not null");
			return this;
		}
		public Criteria andPopsingerEqualTo(Byte value) {
			addCriterion("f_popsinger =", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerNotEqualTo(Byte value) {
			addCriterion("f_popsinger <>", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerGreaterThan(Byte value) {
			addCriterion("f_popsinger >", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_popsinger >=", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerLessThan(Byte value) {
			addCriterion("f_popsinger <", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerLessThanOrEqualTo(Byte value) {
			addCriterion("f_popsinger <=", value, "popsinger");
			return this;
		}
		public Criteria andPopsingerIn(List values) {
			addCriterion("f_popsinger in", values, "popsinger");
			return this;
		}
		public Criteria andPopsingerNotIn(List values) {
			addCriterion("f_popsinger not in", values, "popsinger");
			return this;
		}
		public Criteria andPopsingerBetween(Byte value1, Byte value2) {
			addCriterion("f_popsinger between", value1, value2, "popsinger");
			return this;
		}
		public Criteria andPopsingerNotBetween(Byte value1, Byte value2) {
			addCriterion("f_popsinger not between", value1, value2, "popsinger");
			return this;
		}
		public Criteria andLearningBookIsNull() {
			addCriterion("f_learning_book is null");
			return this;
		}
		public Criteria andLearningBookIsNotNull() {
			addCriterion("f_learning_book is not null");
			return this;
		}
		public Criteria andLearningBookEqualTo(Integer value) {
			addCriterion("f_learning_book =", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookNotEqualTo(Integer value) {
			addCriterion("f_learning_book <>", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookGreaterThan(Integer value) {
			addCriterion("f_learning_book >", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_learning_book >=", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookLessThan(Integer value) {
			addCriterion("f_learning_book <", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookLessThanOrEqualTo(Integer value) {
			addCriterion("f_learning_book <=", value, "learningBook");
			return this;
		}
		public Criteria andLearningBookIn(List values) {
			addCriterion("f_learning_book in", values, "learningBook");
			return this;
		}
		public Criteria andLearningBookNotIn(List values) {
			addCriterion("f_learning_book not in", values, "learningBook");
			return this;
		}
		public Criteria andLearningBookBetween(Integer value1, Integer value2) {
			addCriterion("f_learning_book between", value1, value2, "learningBook");
			return this;
		}
		public Criteria andLearningBookNotBetween(Integer value1, Integer value2) {
			addCriterion("f_learning_book not between", value1, value2, "learningBook");
			return this;
		}
		public Criteria andDescIsNull() {
			addCriterion("f_desc is null");
			return this;
		}
		public Criteria andDescIsNotNull() {
			addCriterion("f_desc is not null");
			return this;
		}
		public Criteria andDescEqualTo(String value) {
			addCriterion("f_desc =", value, "desc");
			return this;
		}
		public Criteria andDescNotEqualTo(String value) {
			addCriterion("f_desc <>", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThan(String value) {
			addCriterion("f_desc >", value, "desc");
			return this;
		}
		public Criteria andDescGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc >=", value, "desc");
			return this;
		}
		public Criteria andDescLessThan(String value) {
			addCriterion("f_desc <", value, "desc");
			return this;
		}
		public Criteria andDescLessThanOrEqualTo(String value) {
			addCriterion("f_desc <=", value, "desc");
			return this;
		}
		public Criteria andDescLike(String value) {
			addCriterion("f_desc like", value, "desc");
			return this;
		}
		public Criteria andDescNotLike(String value) {
			addCriterion("f_desc not like", value, "desc");
			return this;
		}
		public Criteria andDescIn(List values) {
			addCriterion("f_desc in", values, "desc");
			return this;
		}
		public Criteria andDescNotIn(List values) {
			addCriterion("f_desc not in", values, "desc");
			return this;
		}
		public Criteria andDescBetween(String value1, String value2) {
			addCriterion("f_desc between", value1, value2, "desc");
			return this;
		}
		public Criteria andDescNotBetween(String value1, String value2) {
			addCriterion("f_desc not between", value1, value2, "desc");
			return this;
		}
		public Criteria andReviseIsNull() {
			addCriterion("f_revise is null");
			return this;
		}
		public Criteria andReviseIsNotNull() {
			addCriterion("f_revise is not null");
			return this;
		}
		public Criteria andReviseEqualTo(Integer value) {
			addCriterion("f_revise =", value, "revise");
			return this;
		}
		public Criteria andReviseNotEqualTo(Integer value) {
			addCriterion("f_revise <>", value, "revise");
			return this;
		}
		public Criteria andReviseGreaterThan(Integer value) {
			addCriterion("f_revise >", value, "revise");
			return this;
		}
		public Criteria andReviseGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_revise >=", value, "revise");
			return this;
		}
		public Criteria andReviseLessThan(Integer value) {
			addCriterion("f_revise <", value, "revise");
			return this;
		}
		public Criteria andReviseLessThanOrEqualTo(Integer value) {
			addCriterion("f_revise <=", value, "revise");
			return this;
		}
		public Criteria andReviseIn(List values) {
			addCriterion("f_revise in", values, "revise");
			return this;
		}
		public Criteria andReviseNotIn(List values) {
			addCriterion("f_revise not in", values, "revise");
			return this;
		}
		public Criteria andReviseBetween(Integer value1, Integer value2) {
			addCriterion("f_revise between", value1, value2, "revise");
			return this;
		}
		public Criteria andReviseNotBetween(Integer value1, Integer value2) {
			addCriterion("f_revise not between", value1, value2, "revise");
			return this;
		}
		public Criteria andHurtReviseIsNull() {
			addCriterion("f_hurt_revise is null");
			return this;
		}
		public Criteria andHurtReviseIsNotNull() {
			addCriterion("f_hurt_revise is not null");
			return this;
		}
		public Criteria andHurtReviseEqualTo(Float value) {
			addCriterion("f_hurt_revise =", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseNotEqualTo(Float value) {
			addCriterion("f_hurt_revise <>", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseGreaterThan(Float value) {
			addCriterion("f_hurt_revise >", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseGreaterThanOrEqualTo(Float value) {
			addCriterion("f_hurt_revise >=", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseLessThan(Float value) {
			addCriterion("f_hurt_revise <", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseLessThanOrEqualTo(Float value) {
			addCriterion("f_hurt_revise <=", value, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseIn(List values) {
			addCriterion("f_hurt_revise in", values, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseNotIn(List values) {
			addCriterion("f_hurt_revise not in", values, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseBetween(Float value1, Float value2) {
			addCriterion("f_hurt_revise between", value1, value2, "hurtRevise");
			return this;
		}
		public Criteria andHurtReviseNotBetween(Float value1, Float value2) {
			addCriterion("f_hurt_revise not between", value1, value2, "hurtRevise");
			return this;
		}
		public Criteria andHurtAppendIsNull() {
			addCriterion("f_hurt_append is null");
			return this;
		}
		public Criteria andHurtAppendIsNotNull() {
			addCriterion("f_hurt_append is not null");
			return this;
		}
		public Criteria andHurtAppendEqualTo(Integer value) {
			addCriterion("f_hurt_append =", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendNotEqualTo(Integer value) {
			addCriterion("f_hurt_append <>", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendGreaterThan(Integer value) {
			addCriterion("f_hurt_append >", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_append >=", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendLessThan(Integer value) {
			addCriterion("f_hurt_append <", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendLessThanOrEqualTo(Integer value) {
			addCriterion("f_hurt_append <=", value, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendIn(List values) {
			addCriterion("f_hurt_append in", values, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendNotIn(List values) {
			addCriterion("f_hurt_append not in", values, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_append between", value1, value2, "hurtAppend");
			return this;
		}
		public Criteria andHurtAppendNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hurt_append not between", value1, value2, "hurtAppend");
			return this;
		}
		public Criteria andGradeLimitIsNull() {
			addCriterion("f_grade_limit is null");
			return this;
		}
		public Criteria andGradeLimitIsNotNull() {
			addCriterion("f_grade_limit is not null");
			return this;
		}
		public Criteria andGradeLimitEqualTo(Integer value) {
			addCriterion("f_grade_limit =", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitNotEqualTo(Integer value) {
			addCriterion("f_grade_limit <>", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitGreaterThan(Integer value) {
			addCriterion("f_grade_limit >", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_grade_limit >=", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitLessThan(Integer value) {
			addCriterion("f_grade_limit <", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitLessThanOrEqualTo(Integer value) {
			addCriterion("f_grade_limit <=", value, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitIn(List values) {
			addCriterion("f_grade_limit in", values, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitNotIn(List values) {
			addCriterion("f_grade_limit not in", values, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitBetween(Integer value1, Integer value2) {
			addCriterion("f_grade_limit between", value1, value2, "gradeLimit");
			return this;
		}
		public Criteria andGradeLimitNotBetween(Integer value1, Integer value2) {
			addCriterion("f_grade_limit not between", value1, value2, "gradeLimit");
			return this;
		}
		public Criteria andSkilltypeIsNull() {
			addCriterion("f_skilltype is null");
			return this;
		}
		public Criteria andSkilltypeIsNotNull() {
			addCriterion("f_skilltype is not null");
			return this;
		}
		public Criteria andSkilltypeEqualTo(Integer value) {
			addCriterion("f_skilltype =", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeNotEqualTo(Integer value) {
			addCriterion("f_skilltype <>", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeGreaterThan(Integer value) {
			addCriterion("f_skilltype >", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_skilltype >=", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeLessThan(Integer value) {
			addCriterion("f_skilltype <", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_skilltype <=", value, "skilltype");
			return this;
		}
		public Criteria andSkilltypeIn(List values) {
			addCriterion("f_skilltype in", values, "skilltype");
			return this;
		}
		public Criteria andSkilltypeNotIn(List values) {
			addCriterion("f_skilltype not in", values, "skilltype");
			return this;
		}
		public Criteria andSkilltypeBetween(Integer value1, Integer value2) {
			addCriterion("f_skilltype between", value1, value2, "skilltype");
			return this;
		}
		public Criteria andSkilltypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_skilltype not between", value1, value2, "skilltype");
			return this;
		}
		public Criteria andTriggerProbabilityIsNull() {
			addCriterion("f_trigger_probability is null");
			return this;
		}
		public Criteria andTriggerProbabilityIsNotNull() {
			addCriterion("f_trigger_probability is not null");
			return this;
		}
		public Criteria andTriggerProbabilityEqualTo(Integer value) {
			addCriterion("f_trigger_probability =", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityNotEqualTo(Integer value) {
			addCriterion("f_trigger_probability <>", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityGreaterThan(Integer value) {
			addCriterion("f_trigger_probability >", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_trigger_probability >=", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityLessThan(Integer value) {
			addCriterion("f_trigger_probability <", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityLessThanOrEqualTo(Integer value) {
			addCriterion("f_trigger_probability <=", value, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityIn(List values) {
			addCriterion("f_trigger_probability in", values, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityNotIn(List values) {
			addCriterion("f_trigger_probability not in", values, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityBetween(Integer value1, Integer value2) {
			addCriterion("f_trigger_probability between", value1, value2, "triggerProbability");
			return this;
		}
		public Criteria andTriggerProbabilityNotBetween(Integer value1, Integer value2) {
			addCriterion("f_trigger_probability not between", value1, value2, "triggerProbability");
			return this;
		}
		public Criteria andEffectResId0IsNull() {
			addCriterion("f_effect_res_id0 is null");
			return this;
		}
		public Criteria andEffectResId0IsNotNull() {
			addCriterion("f_effect_res_id0 is not null");
			return this;
		}
		public Criteria andEffectResId0EqualTo(Integer value) {
			addCriterion("f_effect_res_id0 =", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0NotEqualTo(Integer value) {
			addCriterion("f_effect_res_id0 <>", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0GreaterThan(Integer value) {
			addCriterion("f_effect_res_id0 >", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0GreaterThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id0 >=", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0LessThan(Integer value) {
			addCriterion("f_effect_res_id0 <", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0LessThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id0 <=", value, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0In(List values) {
			addCriterion("f_effect_res_id0 in", values, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0NotIn(List values) {
			addCriterion("f_effect_res_id0 not in", values, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0Between(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id0 between", value1, value2, "effectResId0");
			return this;
		}
		public Criteria andEffectResId0NotBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id0 not between", value1, value2, "effectResId0");
			return this;
		}
		public Criteria andEffectResId1IsNull() {
			addCriterion("f_effect_res_id1 is null");
			return this;
		}
		public Criteria andEffectResId1IsNotNull() {
			addCriterion("f_effect_res_id1 is not null");
			return this;
		}
		public Criteria andEffectResId1EqualTo(Integer value) {
			addCriterion("f_effect_res_id1 =", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1NotEqualTo(Integer value) {
			addCriterion("f_effect_res_id1 <>", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1GreaterThan(Integer value) {
			addCriterion("f_effect_res_id1 >", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1GreaterThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id1 >=", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1LessThan(Integer value) {
			addCriterion("f_effect_res_id1 <", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1LessThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id1 <=", value, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1In(List values) {
			addCriterion("f_effect_res_id1 in", values, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1NotIn(List values) {
			addCriterion("f_effect_res_id1 not in", values, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1Between(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id1 between", value1, value2, "effectResId1");
			return this;
		}
		public Criteria andEffectResId1NotBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id1 not between", value1, value2, "effectResId1");
			return this;
		}
		public Criteria andEffectResId2IsNull() {
			addCriterion("f_effect_res_id2 is null");
			return this;
		}
		public Criteria andEffectResId2IsNotNull() {
			addCriterion("f_effect_res_id2 is not null");
			return this;
		}
		public Criteria andEffectResId2EqualTo(Integer value) {
			addCriterion("f_effect_res_id2 =", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2NotEqualTo(Integer value) {
			addCriterion("f_effect_res_id2 <>", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2GreaterThan(Integer value) {
			addCriterion("f_effect_res_id2 >", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2GreaterThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id2 >=", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2LessThan(Integer value) {
			addCriterion("f_effect_res_id2 <", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2LessThanOrEqualTo(Integer value) {
			addCriterion("f_effect_res_id2 <=", value, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2In(List values) {
			addCriterion("f_effect_res_id2 in", values, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2NotIn(List values) {
			addCriterion("f_effect_res_id2 not in", values, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2Between(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id2 between", value1, value2, "effectResId2");
			return this;
		}
		public Criteria andEffectResId2NotBetween(Integer value1, Integer value2) {
			addCriterion("f_effect_res_id2 not between", value1, value2, "effectResId2");
			return this;
		}
		public Criteria andShowOrderIsNull() {
			addCriterion("f_show_order is null");
			return this;
		}
		public Criteria andShowOrderIsNotNull() {
			addCriterion("f_show_order is not null");
			return this;
		}
		public Criteria andShowOrderEqualTo(Integer value) {
			addCriterion("f_show_order =", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderNotEqualTo(Integer value) {
			addCriterion("f_show_order <>", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderGreaterThan(Integer value) {
			addCriterion("f_show_order >", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_show_order >=", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderLessThan(Integer value) {
			addCriterion("f_show_order <", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderLessThanOrEqualTo(Integer value) {
			addCriterion("f_show_order <=", value, "showOrder");
			return this;
		}
		public Criteria andShowOrderIn(List values) {
			addCriterion("f_show_order in", values, "showOrder");
			return this;
		}
		public Criteria andShowOrderNotIn(List values) {
			addCriterion("f_show_order not in", values, "showOrder");
			return this;
		}
		public Criteria andShowOrderBetween(Integer value1, Integer value2) {
			addCriterion("f_show_order between", value1, value2, "showOrder");
			return this;
		}
		public Criteria andShowOrderNotBetween(Integer value1, Integer value2) {
			addCriterion("f_show_order not between", value1, value2, "showOrder");
			return this;
		}
		public Criteria andSkillRelevanceIsNull() {
			addCriterion("f_skill_relevance is null");
			return this;
		}
		public Criteria andSkillRelevanceIsNotNull() {
			addCriterion("f_skill_relevance is not null");
			return this;
		}
		public Criteria andSkillRelevanceEqualTo(Integer value) {
			addCriterion("f_skill_relevance =", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceNotEqualTo(Integer value) {
			addCriterion("f_skill_relevance <>", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceGreaterThan(Integer value) {
			addCriterion("f_skill_relevance >", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_skill_relevance >=", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceLessThan(Integer value) {
			addCriterion("f_skill_relevance <", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceLessThanOrEqualTo(Integer value) {
			addCriterion("f_skill_relevance <=", value, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceIn(List values) {
			addCriterion("f_skill_relevance in", values, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceNotIn(List values) {
			addCriterion("f_skill_relevance not in", values, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceBetween(Integer value1, Integer value2) {
			addCriterion("f_skill_relevance between", value1, value2, "skillRelevance");
			return this;
		}
		public Criteria andSkillRelevanceNotBetween(Integer value1, Integer value2) {
			addCriterion("f_skill_relevance not between", value1, value2, "skillRelevance");
			return this;
		}
		public Criteria andPlayDelayIsNull() {
			addCriterion("f_play_delay is null");
			return this;
		}
		public Criteria andPlayDelayIsNotNull() {
			addCriterion("f_play_delay is not null");
			return this;
		}
		public Criteria andPlayDelayEqualTo(Integer value) {
			addCriterion("f_play_delay =", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayNotEqualTo(Integer value) {
			addCriterion("f_play_delay <>", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayGreaterThan(Integer value) {
			addCriterion("f_play_delay >", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_play_delay >=", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayLessThan(Integer value) {
			addCriterion("f_play_delay <", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayLessThanOrEqualTo(Integer value) {
			addCriterion("f_play_delay <=", value, "playDelay");
			return this;
		}
		public Criteria andPlayDelayIn(List values) {
			addCriterion("f_play_delay in", values, "playDelay");
			return this;
		}
		public Criteria andPlayDelayNotIn(List values) {
			addCriterion("f_play_delay not in", values, "playDelay");
			return this;
		}
		public Criteria andPlayDelayBetween(Integer value1, Integer value2) {
			addCriterion("f_play_delay between", value1, value2, "playDelay");
			return this;
		}
		public Criteria andPlayDelayNotBetween(Integer value1, Integer value2) {
			addCriterion("f_play_delay not between", value1, value2, "playDelay");
			return this;
		}
		public Criteria andFlySpeedIsNull() {
			addCriterion("f_fly_speed is null");
			return this;
		}
		public Criteria andFlySpeedIsNotNull() {
			addCriterion("f_fly_speed is not null");
			return this;
		}
		public Criteria andFlySpeedEqualTo(Integer value) {
			addCriterion("f_fly_speed =", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedNotEqualTo(Integer value) {
			addCriterion("f_fly_speed <>", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedGreaterThan(Integer value) {
			addCriterion("f_fly_speed >", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_fly_speed >=", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedLessThan(Integer value) {
			addCriterion("f_fly_speed <", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedLessThanOrEqualTo(Integer value) {
			addCriterion("f_fly_speed <=", value, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedIn(List values) {
			addCriterion("f_fly_speed in", values, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedNotIn(List values) {
			addCriterion("f_fly_speed not in", values, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedBetween(Integer value1, Integer value2) {
			addCriterion("f_fly_speed between", value1, value2, "flySpeed");
			return this;
		}
		public Criteria andFlySpeedNotBetween(Integer value1, Integer value2) {
			addCriterion("f_fly_speed not between", value1, value2, "flySpeed");
			return this;
		}
		public Criteria andCreateLearnIsNull() {
			addCriterion("f_create_learn is null");
			return this;
		}
		public Criteria andCreateLearnIsNotNull() {
			addCriterion("f_create_learn is not null");
			return this;
		}
		public Criteria andCreateLearnEqualTo(Byte value) {
			addCriterion("f_create_learn =", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnNotEqualTo(Byte value) {
			addCriterion("f_create_learn <>", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnGreaterThan(Byte value) {
			addCriterion("f_create_learn >", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_create_learn >=", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnLessThan(Byte value) {
			addCriterion("f_create_learn <", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnLessThanOrEqualTo(Byte value) {
			addCriterion("f_create_learn <=", value, "createLearn");
			return this;
		}
		public Criteria andCreateLearnIn(List values) {
			addCriterion("f_create_learn in", values, "createLearn");
			return this;
		}
		public Criteria andCreateLearnNotIn(List values) {
			addCriterion("f_create_learn not in", values, "createLearn");
			return this;
		}
		public Criteria andCreateLearnBetween(Byte value1, Byte value2) {
			addCriterion("f_create_learn between", value1, value2, "createLearn");
			return this;
		}
		public Criteria andCreateLearnNotBetween(Byte value1, Byte value2) {
			addCriterion("f_create_learn not between", value1, value2, "createLearn");
			return this;
		}
		public Criteria andCommonCoolTypeIsNull() {
			addCriterion("f_common_cool_type is null");
			return this;
		}
		public Criteria andCommonCoolTypeIsNotNull() {
			addCriterion("f_common_cool_type is not null");
			return this;
		}
		public Criteria andCommonCoolTypeEqualTo(Byte value) {
			addCriterion("f_common_cool_type =", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeNotEqualTo(Byte value) {
			addCriterion("f_common_cool_type <>", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeGreaterThan(Byte value) {
			addCriterion("f_common_cool_type >", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_common_cool_type >=", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeLessThan(Byte value) {
			addCriterion("f_common_cool_type <", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_common_cool_type <=", value, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeIn(List values) {
			addCriterion("f_common_cool_type in", values, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeNotIn(List values) {
			addCriterion("f_common_cool_type not in", values, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_common_cool_type between", value1, value2, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_common_cool_type not between", value1, value2, "commonCoolType");
			return this;
		}
		public Criteria andCommonCoolTimeIsNull() {
			addCriterion("f_common_cool_time is null");
			return this;
		}
		public Criteria andCommonCoolTimeIsNotNull() {
			addCriterion("f_common_cool_time is not null");
			return this;
		}
		public Criteria andCommonCoolTimeEqualTo(Integer value) {
			addCriterion("f_common_cool_time =", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeNotEqualTo(Integer value) {
			addCriterion("f_common_cool_time <>", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeGreaterThan(Integer value) {
			addCriterion("f_common_cool_time >", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_common_cool_time >=", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeLessThan(Integer value) {
			addCriterion("f_common_cool_time <", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeLessThanOrEqualTo(Integer value) {
			addCriterion("f_common_cool_time <=", value, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeIn(List values) {
			addCriterion("f_common_cool_time in", values, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeNotIn(List values) {
			addCriterion("f_common_cool_time not in", values, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeBetween(Integer value1, Integer value2) {
			addCriterion("f_common_cool_time between", value1, value2, "commonCoolTime");
			return this;
		}
		public Criteria andCommonCoolTimeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_common_cool_time not between", value1, value2, "commonCoolTime");
			return this;
		}
		public Criteria andEnmityValueIsNull() {
			addCriterion("f_enmity_value is null");
			return this;
		}
		public Criteria andEnmityValueIsNotNull() {
			addCriterion("f_enmity_value is not null");
			return this;
		}
		public Criteria andEnmityValueEqualTo(Integer value) {
			addCriterion("f_enmity_value =", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueNotEqualTo(Integer value) {
			addCriterion("f_enmity_value <>", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueGreaterThan(Integer value) {
			addCriterion("f_enmity_value >", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_enmity_value >=", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueLessThan(Integer value) {
			addCriterion("f_enmity_value <", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueLessThanOrEqualTo(Integer value) {
			addCriterion("f_enmity_value <=", value, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueIn(List values) {
			addCriterion("f_enmity_value in", values, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueNotIn(List values) {
			addCriterion("f_enmity_value not in", values, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueBetween(Integer value1, Integer value2) {
			addCriterion("f_enmity_value between", value1, value2, "enmityValue");
			return this;
		}
		public Criteria andEnmityValueNotBetween(Integer value1, Integer value2) {
			addCriterion("f_enmity_value not between", value1, value2, "enmityValue");
			return this;
		}
		public Criteria andTypeIsNull() {
			addCriterion("f_type is null");
			return this;
		}
		public Criteria andTypeIsNotNull() {
			addCriterion("f_type is not null");
			return this;
		}
		public Criteria andTypeEqualTo(Byte value) {
			addCriterion("f_type =", value, "type");
			return this;
		}
		public Criteria andTypeNotEqualTo(Byte value) {
			addCriterion("f_type <>", value, "type");
			return this;
		}
		public Criteria andTypeGreaterThan(Byte value) {
			addCriterion("f_type >", value, "type");
			return this;
		}
		public Criteria andTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_type >=", value, "type");
			return this;
		}
		public Criteria andTypeLessThan(Byte value) {
			addCriterion("f_type <", value, "type");
			return this;
		}
		public Criteria andTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_type <=", value, "type");
			return this;
		}
		public Criteria andTypeIn(List values) {
			addCriterion("f_type in", values, "type");
			return this;
		}
		public Criteria andTypeNotIn(List values) {
			addCriterion("f_type not in", values, "type");
			return this;
		}
		public Criteria andTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_type between", value1, value2, "type");
			return this;
		}
		public Criteria andTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_type not between", value1, value2, "type");
			return this;
		}
		public Criteria andBigIcoIsNull() {
			addCriterion("f_big_ico is null");
			return this;
		}
		public Criteria andBigIcoIsNotNull() {
			addCriterion("f_big_ico is not null");
			return this;
		}
		public Criteria andBigIcoEqualTo(Integer value) {
			addCriterion("f_big_ico =", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoNotEqualTo(Integer value) {
			addCriterion("f_big_ico <>", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoGreaterThan(Integer value) {
			addCriterion("f_big_ico >", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_big_ico >=", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoLessThan(Integer value) {
			addCriterion("f_big_ico <", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoLessThanOrEqualTo(Integer value) {
			addCriterion("f_big_ico <=", value, "bigIco");
			return this;
		}
		public Criteria andBigIcoIn(List values) {
			addCriterion("f_big_ico in", values, "bigIco");
			return this;
		}
		public Criteria andBigIcoNotIn(List values) {
			addCriterion("f_big_ico not in", values, "bigIco");
			return this;
		}
		public Criteria andBigIcoBetween(Integer value1, Integer value2) {
			addCriterion("f_big_ico between", value1, value2, "bigIco");
			return this;
		}
		public Criteria andBigIcoNotBetween(Integer value1, Integer value2) {
			addCriterion("f_big_ico not between", value1, value2, "bigIco");
			return this;
		}
		public Criteria andSoundIsNull() {
			addCriterion("f_sound is null");
			return this;
		}
		public Criteria andSoundIsNotNull() {
			addCriterion("f_sound is not null");
			return this;
		}
		public Criteria andSoundEqualTo(Integer value) {
			addCriterion("f_sound =", value, "sound");
			return this;
		}
		public Criteria andSoundNotEqualTo(Integer value) {
			addCriterion("f_sound <>", value, "sound");
			return this;
		}
		public Criteria andSoundGreaterThan(Integer value) {
			addCriterion("f_sound >", value, "sound");
			return this;
		}
		public Criteria andSoundGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_sound >=", value, "sound");
			return this;
		}
		public Criteria andSoundLessThan(Integer value) {
			addCriterion("f_sound <", value, "sound");
			return this;
		}
		public Criteria andSoundLessThanOrEqualTo(Integer value) {
			addCriterion("f_sound <=", value, "sound");
			return this;
		}
		public Criteria andSoundIn(List values) {
			addCriterion("f_sound in", values, "sound");
			return this;
		}
		public Criteria andSoundNotIn(List values) {
			addCriterion("f_sound not in", values, "sound");
			return this;
		}
		public Criteria andSoundBetween(Integer value1, Integer value2) {
			addCriterion("f_sound between", value1, value2, "sound");
			return this;
		}
		public Criteria andSoundNotBetween(Integer value1, Integer value2) {
			addCriterion("f_sound not between", value1, value2, "sound");
			return this;
		}
		public Criteria andHurtedTribIsNull() {
			addCriterion("f_hurted_trib is null");
			return this;
		}
		public Criteria andHurtedTribIsNotNull() {
			addCriterion("f_hurted_trib is not null");
			return this;
		}
		public Criteria andHurtedTribEqualTo(Boolean value) {
			addCriterion("f_hurted_trib =", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribNotEqualTo(Boolean value) {
			addCriterion("f_hurted_trib <>", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribGreaterThan(Boolean value) {
			addCriterion("f_hurted_trib >", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribGreaterThanOrEqualTo(Boolean value) {
			addCriterion("f_hurted_trib >=", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribLessThan(Boolean value) {
			addCriterion("f_hurted_trib <", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribLessThanOrEqualTo(Boolean value) {
			addCriterion("f_hurted_trib <=", value, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribIn(List values) {
			addCriterion("f_hurted_trib in", values, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribNotIn(List values) {
			addCriterion("f_hurted_trib not in", values, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribBetween(Boolean value1, Boolean value2) {
			addCriterion("f_hurted_trib between", value1, value2, "hurtedTrib");
			return this;
		}
		public Criteria andHurtedTribNotBetween(Boolean value1, Boolean value2) {
			addCriterion("f_hurted_trib not between", value1, value2, "hurtedTrib");
			return this;
		}
		public Criteria andWugongTypeIsNull() {
			addCriterion("f_wugong_type is null");
			return this;
		}
		public Criteria andWugongTypeIsNotNull() {
			addCriterion("f_wugong_type is not null");
			return this;
		}
		public Criteria andWugongTypeEqualTo(Byte value) {
			addCriterion("f_wugong_type =", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeNotEqualTo(Byte value) {
			addCriterion("f_wugong_type <>", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeGreaterThan(Byte value) {
			addCriterion("f_wugong_type >", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_wugong_type >=", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeLessThan(Byte value) {
			addCriterion("f_wugong_type <", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeLessThanOrEqualTo(Byte value) {
			addCriterion("f_wugong_type <=", value, "wugongType");
			return this;
		}
		public Criteria andWugongTypeIn(List values) {
			addCriterion("f_wugong_type in", values, "wugongType");
			return this;
		}
		public Criteria andWugongTypeNotIn(List values) {
			addCriterion("f_wugong_type not in", values, "wugongType");
			return this;
		}
		public Criteria andWugongTypeBetween(Byte value1, Byte value2) {
			addCriterion("f_wugong_type between", value1, value2, "wugongType");
			return this;
		}
		public Criteria andWugongTypeNotBetween(Byte value1, Byte value2) {
			addCriterion("f_wugong_type not between", value1, value2, "wugongType");
			return this;
		}
		public Criteria andSourceIsNull() {
			addCriterion("f_source is null");
			return this;
		}
		public Criteria andSourceIsNotNull() {
			addCriterion("f_source is not null");
			return this;
		}
		public Criteria andSourceEqualTo(String value) {
			addCriterion("f_source =", value, "source");
			return this;
		}
		public Criteria andSourceNotEqualTo(String value) {
			addCriterion("f_source <>", value, "source");
			return this;
		}
		public Criteria andSourceGreaterThan(String value) {
			addCriterion("f_source >", value, "source");
			return this;
		}
		public Criteria andSourceGreaterThanOrEqualTo(String value) {
			addCriterion("f_source >=", value, "source");
			return this;
		}
		public Criteria andSourceLessThan(String value) {
			addCriterion("f_source <", value, "source");
			return this;
		}
		public Criteria andSourceLessThanOrEqualTo(String value) {
			addCriterion("f_source <=", value, "source");
			return this;
		}
		public Criteria andSourceLike(String value) {
			addCriterion("f_source like", value, "source");
			return this;
		}
		public Criteria andSourceNotLike(String value) {
			addCriterion("f_source not like", value, "source");
			return this;
		}
		public Criteria andSourceIn(List values) {
			addCriterion("f_source in", values, "source");
			return this;
		}
		public Criteria andSourceNotIn(List values) {
			addCriterion("f_source not in", values, "source");
			return this;
		}
		public Criteria andSourceBetween(String value1, String value2) {
			addCriterion("f_source between", value1, value2, "source");
			return this;
		}
		public Criteria andSourceNotBetween(String value1, String value2) {
			addCriterion("f_source not between", value1, value2, "source");
			return this;
		}
		public Criteria andKanxingSkillIsNull() {
			addCriterion("f_kanxing_skill is null");
			return this;
		}
		public Criteria andKanxingSkillIsNotNull() {
			addCriterion("f_kanxing_skill is not null");
			return this;
		}
		public Criteria andKanxingSkillEqualTo(Integer value) {
			addCriterion("f_kanxing_skill =", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillNotEqualTo(Integer value) {
			addCriterion("f_kanxing_skill <>", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillGreaterThan(Integer value) {
			addCriterion("f_kanxing_skill >", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_kanxing_skill >=", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillLessThan(Integer value) {
			addCriterion("f_kanxing_skill <", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillLessThanOrEqualTo(Integer value) {
			addCriterion("f_kanxing_skill <=", value, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillIn(List values) {
			addCriterion("f_kanxing_skill in", values, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillNotIn(List values) {
			addCriterion("f_kanxing_skill not in", values, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillBetween(Integer value1, Integer value2) {
			addCriterion("f_kanxing_skill between", value1, value2, "kanxingSkill");
			return this;
		}
		public Criteria andKanxingSkillNotBetween(Integer value1, Integer value2) {
			addCriterion("f_kanxing_skill not between", value1, value2, "kanxingSkill");
			return this;
		}
		public Criteria andBeidongBaseValueIsNull() {
			addCriterion("f_beidong_base_value is null");
			return this;
		}
		public Criteria andBeidongBaseValueIsNotNull() {
			addCriterion("f_beidong_base_value is not null");
			return this;
		}
		public Criteria andBeidongBaseValueEqualTo(Integer value) {
			addCriterion("f_beidong_base_value =", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueNotEqualTo(Integer value) {
			addCriterion("f_beidong_base_value <>", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueGreaterThan(Integer value) {
			addCriterion("f_beidong_base_value >", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_beidong_base_value >=", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueLessThan(Integer value) {
			addCriterion("f_beidong_base_value <", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueLessThanOrEqualTo(Integer value) {
			addCriterion("f_beidong_base_value <=", value, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueIn(List values) {
			addCriterion("f_beidong_base_value in", values, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueNotIn(List values) {
			addCriterion("f_beidong_base_value not in", values, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueBetween(Integer value1, Integer value2) {
			addCriterion("f_beidong_base_value between", value1, value2, "beidongBaseValue");
			return this;
		}
		public Criteria andBeidongBaseValueNotBetween(Integer value1, Integer value2) {
			addCriterion("f_beidong_base_value not between", value1, value2, "beidongBaseValue");
			return this;
		}
		public Criteria andIsZuheIsNull() {
			addCriterion("f_is_zuhe is null");
			return this;
		}
		public Criteria andIsZuheIsNotNull() {
			addCriterion("f_is_zuhe is not null");
			return this;
		}
		public Criteria andIsZuheEqualTo(Byte value) {
			addCriterion("f_is_zuhe =", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheNotEqualTo(Byte value) {
			addCriterion("f_is_zuhe <>", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheGreaterThan(Byte value) {
			addCriterion("f_is_zuhe >", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheGreaterThanOrEqualTo(Byte value) {
			addCriterion("f_is_zuhe >=", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheLessThan(Byte value) {
			addCriterion("f_is_zuhe <", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheLessThanOrEqualTo(Byte value) {
			addCriterion("f_is_zuhe <=", value, "isZuhe");
			return this;
		}
		public Criteria andIsZuheIn(List values) {
			addCriterion("f_is_zuhe in", values, "isZuhe");
			return this;
		}
		public Criteria andIsZuheNotIn(List values) {
			addCriterion("f_is_zuhe not in", values, "isZuhe");
			return this;
		}
		public Criteria andIsZuheBetween(Byte value1, Byte value2) {
			addCriterion("f_is_zuhe between", value1, value2, "isZuhe");
			return this;
		}
		public Criteria andIsZuheNotBetween(Byte value1, Byte value2) {
			addCriterion("f_is_zuhe not between", value1, value2, "isZuhe");
			return this;
		}
		public Criteria andBangGongIsNull() {
			addCriterion("f_bang_gong is null");
			return this;
		}
		public Criteria andBangGongIsNotNull() {
			addCriterion("f_bang_gong is not null");
			return this;
		}
		public Criteria andBangGongEqualTo(Integer value) {
			addCriterion("f_bang_gong =", value, "bangGong");
			return this;
		}
		public Criteria andBangGongNotEqualTo(Integer value) {
			addCriterion("f_bang_gong <>", value, "bangGong");
			return this;
		}
		public Criteria andBangGongGreaterThan(Integer value) {
			addCriterion("f_bang_gong >", value, "bangGong");
			return this;
		}
		public Criteria andBangGongGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_bang_gong >=", value, "bangGong");
			return this;
		}
		public Criteria andBangGongLessThan(Integer value) {
			addCriterion("f_bang_gong <", value, "bangGong");
			return this;
		}
		public Criteria andBangGongLessThanOrEqualTo(Integer value) {
			addCriterion("f_bang_gong <=", value, "bangGong");
			return this;
		}
		public Criteria andBangGongIn(List values) {
			addCriterion("f_bang_gong in", values, "bangGong");
			return this;
		}
		public Criteria andBangGongNotIn(List values) {
			addCriterion("f_bang_gong not in", values, "bangGong");
			return this;
		}
		public Criteria andBangGongBetween(Integer value1, Integer value2) {
			addCriterion("f_bang_gong between", value1, value2, "bangGong");
			return this;
		}
		public Criteria andBangGongNotBetween(Integer value1, Integer value2) {
			addCriterion("f_bang_gong not between", value1, value2, "bangGong");
			return this;
		}
		public Criteria andLearnTypeIsNull() {
			addCriterion("f_learn_type is null");
			return this;
		}
		public Criteria andLearnTypeIsNotNull() {
			addCriterion("f_learn_type is not null");
			return this;
		}
		public Criteria andLearnTypeEqualTo(Integer value) {
			addCriterion("f_learn_type =", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeNotEqualTo(Integer value) {
			addCriterion("f_learn_type <>", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeGreaterThan(Integer value) {
			addCriterion("f_learn_type >", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_learn_type >=", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeLessThan(Integer value) {
			addCriterion("f_learn_type <", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeLessThanOrEqualTo(Integer value) {
			addCriterion("f_learn_type <=", value, "learnType");
			return this;
		}
		public Criteria andLearnTypeIn(List values) {
			addCriterion("f_learn_type in", values, "learnType");
			return this;
		}
		public Criteria andLearnTypeNotIn(List values) {
			addCriterion("f_learn_type not in", values, "learnType");
			return this;
		}
		public Criteria andLearnTypeBetween(Integer value1, Integer value2) {
			addCriterion("f_learn_type between", value1, value2, "learnType");
			return this;
		}
		public Criteria andLearnTypeNotBetween(Integer value1, Integer value2) {
			addCriterion("f_learn_type not between", value1, value2, "learnType");
			return this;
		}
		public Criteria andNameI18nIsNull() {
			addCriterion("f_name_i18n is null");
			return this;
		}
		public Criteria andNameI18nIsNotNull() {
			addCriterion("f_name_i18n is not null");
			return this;
		}
		public Criteria andNameI18nEqualTo(String value) {
			addCriterion("f_name_i18n =", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotEqualTo(String value) {
			addCriterion("f_name_i18n <>", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThan(String value) {
			addCriterion("f_name_i18n >", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_name_i18n >=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThan(String value) {
			addCriterion("f_name_i18n <", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThanOrEqualTo(String value) {
			addCriterion("f_name_i18n <=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLike(String value) {
			addCriterion("f_name_i18n like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotLike(String value) {
			addCriterion("f_name_i18n not like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nIn(List values) {
			addCriterion("f_name_i18n in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotIn(List values) {
			addCriterion("f_name_i18n not in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nBetween(String value1, String value2) {
			addCriterion("f_name_i18n between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotBetween(String value1, String value2) {
			addCriterion("f_name_i18n not between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andDescI18nIsNull() {
			addCriterion("f_desc_i18n is null");
			return this;
		}
		public Criteria andDescI18nIsNotNull() {
			addCriterion("f_desc_i18n is not null");
			return this;
		}
		public Criteria andDescI18nEqualTo(String value) {
			addCriterion("f_desc_i18n =", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotEqualTo(String value) {
			addCriterion("f_desc_i18n <>", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThan(String value) {
			addCriterion("f_desc_i18n >", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n >=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThan(String value) {
			addCriterion("f_desc_i18n <", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLessThanOrEqualTo(String value) {
			addCriterion("f_desc_i18n <=", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nLike(String value) {
			addCriterion("f_desc_i18n like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotLike(String value) {
			addCriterion("f_desc_i18n not like", value, "descI18n");
			return this;
		}
		public Criteria andDescI18nIn(List values) {
			addCriterion("f_desc_i18n in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotIn(List values) {
			addCriterion("f_desc_i18n not in", values, "descI18n");
			return this;
		}
		public Criteria andDescI18nBetween(String value1, String value2) {
			addCriterion("f_desc_i18n between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andDescI18nNotBetween(String value1, String value2) {
			addCriterion("f_desc_i18n not between", value1, value2, "descI18n");
			return this;
		}
		public Criteria andSourceI18nIsNull() {
			addCriterion("f_source_i18n is null");
			return this;
		}
		public Criteria andSourceI18nIsNotNull() {
			addCriterion("f_source_i18n is not null");
			return this;
		}
		public Criteria andSourceI18nEqualTo(String value) {
			addCriterion("f_source_i18n =", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nNotEqualTo(String value) {
			addCriterion("f_source_i18n <>", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nGreaterThan(String value) {
			addCriterion("f_source_i18n >", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_source_i18n >=", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nLessThan(String value) {
			addCriterion("f_source_i18n <", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nLessThanOrEqualTo(String value) {
			addCriterion("f_source_i18n <=", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nLike(String value) {
			addCriterion("f_source_i18n like", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nNotLike(String value) {
			addCriterion("f_source_i18n not like", value, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nIn(List values) {
			addCriterion("f_source_i18n in", values, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nNotIn(List values) {
			addCriterion("f_source_i18n not in", values, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nBetween(String value1, String value2) {
			addCriterion("f_source_i18n between", value1, value2, "sourceI18n");
			return this;
		}
		public Criteria andSourceI18nNotBetween(String value1, String value2) {
			addCriterion("f_source_i18n not between", value1, value2, "sourceI18n");
			return this;
		}
	}
}
