package net.snake.dao.channel;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class ChannelExample {

	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_channel
	 */
	protected String orderByClause;
	/**
	 * This field was generated by Apache iBATIS ibator. This field corresponds to the database table t_channel
	 */
	protected List oredCriteria;

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public ChannelExample() {
		oredCriteria = new ArrayList();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	protected ChannelExample(ChannelExample example) {
		this.orderByClause = example.orderByClause;
		this.oredCriteria = example.oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public List getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_channel
	 */
	public void clear() {
		oredCriteria.clear();
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_channel
	 */
	public static class Criteria {
		protected List criteriaWithoutValue;
		protected List criteriaWithSingleValue;
		protected List criteriaWithListValue;
		protected List criteriaWithBetweenValue;
		protected Criteria() {
			super();
			criteriaWithoutValue = new ArrayList();
			criteriaWithSingleValue = new ArrayList();
			criteriaWithListValue = new ArrayList();
			criteriaWithBetweenValue = new ArrayList();
		}
		public boolean isValid() {
			return criteriaWithoutValue.size() > 0 || criteriaWithSingleValue.size() > 0
					|| criteriaWithListValue.size() > 0 || criteriaWithBetweenValue.size() > 0;
		}
		public List getCriteriaWithoutValue() {
			return criteriaWithoutValue;
		}
		public List getCriteriaWithSingleValue() {
			return criteriaWithSingleValue;
		}
		public List getCriteriaWithListValue() {
			return criteriaWithListValue;
		}
		public List getCriteriaWithBetweenValue() {
			return criteriaWithBetweenValue;
		}
		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteriaWithoutValue.add(condition);
		}
		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("value", value);
			criteriaWithSingleValue.add(map);
		}
		protected void addCriterion(String condition, List values, String property) {
			if (values == null || values.size() == 0) {
				throw new RuntimeException("Value list for " + property + " cannot be null or empty");
			}
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", values);
			criteriaWithListValue.add(map);
		}
		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			List list = new ArrayList();
			list.add(value1);
			list.add(value2);
			Map map = new HashMap();
			map.put("condition", condition);
			map.put("values", list);
			criteriaWithBetweenValue.add(map);
		}
		public Criteria andIdIsNull() {
			addCriterion("f_id is null");
			return this;
		}
		public Criteria andIdIsNotNull() {
			addCriterion("f_id is not null");
			return this;
		}
		public Criteria andIdEqualTo(Integer value) {
			addCriterion("f_id =", value, "id");
			return this;
		}
		public Criteria andIdNotEqualTo(Integer value) {
			addCriterion("f_id <>", value, "id");
			return this;
		}
		public Criteria andIdGreaterThan(Integer value) {
			addCriterion("f_id >", value, "id");
			return this;
		}
		public Criteria andIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_id >=", value, "id");
			return this;
		}
		public Criteria andIdLessThan(Integer value) {
			addCriterion("f_id <", value, "id");
			return this;
		}
		public Criteria andIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_id <=", value, "id");
			return this;
		}
		public Criteria andIdIn(List values) {
			addCriterion("f_id in", values, "id");
			return this;
		}
		public Criteria andIdNotIn(List values) {
			addCriterion("f_id not in", values, "id");
			return this;
		}
		public Criteria andIdBetween(Integer value1, Integer value2) {
			addCriterion("f_id between", value1, value2, "id");
			return this;
		}
		public Criteria andIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_id not between", value1, value2, "id");
			return this;
		}
		public Criteria andNameIsNull() {
			addCriterion("f_name is null");
			return this;
		}
		public Criteria andNameIsNotNull() {
			addCriterion("f_name is not null");
			return this;
		}
		public Criteria andNameEqualTo(String value) {
			addCriterion("f_name =", value, "name");
			return this;
		}
		public Criteria andNameNotEqualTo(String value) {
			addCriterion("f_name <>", value, "name");
			return this;
		}
		public Criteria andNameGreaterThan(String value) {
			addCriterion("f_name >", value, "name");
			return this;
		}
		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("f_name >=", value, "name");
			return this;
		}
		public Criteria andNameLessThan(String value) {
			addCriterion("f_name <", value, "name");
			return this;
		}
		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("f_name <=", value, "name");
			return this;
		}
		public Criteria andNameLike(String value) {
			addCriterion("f_name like", value, "name");
			return this;
		}
		public Criteria andNameNotLike(String value) {
			addCriterion("f_name not like", value, "name");
			return this;
		}
		public Criteria andNameIn(List values) {
			addCriterion("f_name in", values, "name");
			return this;
		}
		public Criteria andNameNotIn(List values) {
			addCriterion("f_name not in", values, "name");
			return this;
		}
		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("f_name between", value1, value2, "name");
			return this;
		}
		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("f_name not between", value1, value2, "name");
			return this;
		}
		public Criteria andHpAddIsNull() {
			addCriterion("f_hp_add is null");
			return this;
		}
		public Criteria andHpAddIsNotNull() {
			addCriterion("f_hp_add is not null");
			return this;
		}
		public Criteria andHpAddEqualTo(Integer value) {
			addCriterion("f_hp_add =", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddNotEqualTo(Integer value) {
			addCriterion("f_hp_add <>", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddGreaterThan(Integer value) {
			addCriterion("f_hp_add >", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_hp_add >=", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddLessThan(Integer value) {
			addCriterion("f_hp_add <", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_hp_add <=", value, "hpAdd");
			return this;
		}
		public Criteria andHpAddIn(List values) {
			addCriterion("f_hp_add in", values, "hpAdd");
			return this;
		}
		public Criteria andHpAddNotIn(List values) {
			addCriterion("f_hp_add not in", values, "hpAdd");
			return this;
		}
		public Criteria andHpAddBetween(Integer value1, Integer value2) {
			addCriterion("f_hp_add between", value1, value2, "hpAdd");
			return this;
		}
		public Criteria andHpAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_hp_add not between", value1, value2, "hpAdd");
			return this;
		}
		public Criteria andMpAddIsNull() {
			addCriterion("f_mp_add is null");
			return this;
		}
		public Criteria andMpAddIsNotNull() {
			addCriterion("f_mp_add is not null");
			return this;
		}
		public Criteria andMpAddEqualTo(Integer value) {
			addCriterion("f_mp_add =", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddNotEqualTo(Integer value) {
			addCriterion("f_mp_add <>", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddGreaterThan(Integer value) {
			addCriterion("f_mp_add >", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_mp_add >=", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddLessThan(Integer value) {
			addCriterion("f_mp_add <", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_mp_add <=", value, "mpAdd");
			return this;
		}
		public Criteria andMpAddIn(List values) {
			addCriterion("f_mp_add in", values, "mpAdd");
			return this;
		}
		public Criteria andMpAddNotIn(List values) {
			addCriterion("f_mp_add not in", values, "mpAdd");
			return this;
		}
		public Criteria andMpAddBetween(Integer value1, Integer value2) {
			addCriterion("f_mp_add between", value1, value2, "mpAdd");
			return this;
		}
		public Criteria andMpAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_mp_add not between", value1, value2, "mpAdd");
			return this;
		}
		public Criteria andSpAddIsNull() {
			addCriterion("f_sp_add is null");
			return this;
		}
		public Criteria andSpAddIsNotNull() {
			addCriterion("f_sp_add is not null");
			return this;
		}
		public Criteria andSpAddEqualTo(Integer value) {
			addCriterion("f_sp_add =", value, "spAdd");
			return this;
		}
		public Criteria andSpAddNotEqualTo(Integer value) {
			addCriterion("f_sp_add <>", value, "spAdd");
			return this;
		}
		public Criteria andSpAddGreaterThan(Integer value) {
			addCriterion("f_sp_add >", value, "spAdd");
			return this;
		}
		public Criteria andSpAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_sp_add >=", value, "spAdd");
			return this;
		}
		public Criteria andSpAddLessThan(Integer value) {
			addCriterion("f_sp_add <", value, "spAdd");
			return this;
		}
		public Criteria andSpAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_sp_add <=", value, "spAdd");
			return this;
		}
		public Criteria andSpAddIn(List values) {
			addCriterion("f_sp_add in", values, "spAdd");
			return this;
		}
		public Criteria andSpAddNotIn(List values) {
			addCriterion("f_sp_add not in", values, "spAdd");
			return this;
		}
		public Criteria andSpAddBetween(Integer value1, Integer value2) {
			addCriterion("f_sp_add between", value1, value2, "spAdd");
			return this;
		}
		public Criteria andSpAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_sp_add not between", value1, value2, "spAdd");
			return this;
		}
		public Criteria andAttackAddIsNull() {
			addCriterion("f_attack_add is null");
			return this;
		}
		public Criteria andAttackAddIsNotNull() {
			addCriterion("f_attack_add is not null");
			return this;
		}
		public Criteria andAttackAddEqualTo(Integer value) {
			addCriterion("f_attack_add =", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddNotEqualTo(Integer value) {
			addCriterion("f_attack_add <>", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddGreaterThan(Integer value) {
			addCriterion("f_attack_add >", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_attack_add >=", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddLessThan(Integer value) {
			addCriterion("f_attack_add <", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_attack_add <=", value, "attackAdd");
			return this;
		}
		public Criteria andAttackAddIn(List values) {
			addCriterion("f_attack_add in", values, "attackAdd");
			return this;
		}
		public Criteria andAttackAddNotIn(List values) {
			addCriterion("f_attack_add not in", values, "attackAdd");
			return this;
		}
		public Criteria andAttackAddBetween(Integer value1, Integer value2) {
			addCriterion("f_attack_add between", value1, value2, "attackAdd");
			return this;
		}
		public Criteria andAttackAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_attack_add not between", value1, value2, "attackAdd");
			return this;
		}
		public Criteria andDefenceAddIsNull() {
			addCriterion("f_defence_add is null");
			return this;
		}
		public Criteria andDefenceAddIsNotNull() {
			addCriterion("f_defence_add is not null");
			return this;
		}
		public Criteria andDefenceAddEqualTo(Integer value) {
			addCriterion("f_defence_add =", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddNotEqualTo(Integer value) {
			addCriterion("f_defence_add <>", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddGreaterThan(Integer value) {
			addCriterion("f_defence_add >", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_defence_add >=", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddLessThan(Integer value) {
			addCriterion("f_defence_add <", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_defence_add <=", value, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddIn(List values) {
			addCriterion("f_defence_add in", values, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddNotIn(List values) {
			addCriterion("f_defence_add not in", values, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddBetween(Integer value1, Integer value2) {
			addCriterion("f_defence_add between", value1, value2, "defenceAdd");
			return this;
		}
		public Criteria andDefenceAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_defence_add not between", value1, value2, "defenceAdd");
			return this;
		}
		public Criteria andDodgeAddIsNull() {
			addCriterion("f_dodge_add is null");
			return this;
		}
		public Criteria andDodgeAddIsNotNull() {
			addCriterion("f_dodge_add is not null");
			return this;
		}
		public Criteria andDodgeAddEqualTo(Integer value) {
			addCriterion("f_dodge_add =", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddNotEqualTo(Integer value) {
			addCriterion("f_dodge_add <>", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddGreaterThan(Integer value) {
			addCriterion("f_dodge_add >", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_dodge_add >=", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddLessThan(Integer value) {
			addCriterion("f_dodge_add <", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_dodge_add <=", value, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddIn(List values) {
			addCriterion("f_dodge_add in", values, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddNotIn(List values) {
			addCriterion("f_dodge_add not in", values, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddBetween(Integer value1, Integer value2) {
			addCriterion("f_dodge_add between", value1, value2, "dodgeAdd");
			return this;
		}
		public Criteria andDodgeAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_dodge_add not between", value1, value2, "dodgeAdd");
			return this;
		}
		public Criteria andCrtAddIsNull() {
			addCriterion("f_crt_add is null");
			return this;
		}
		public Criteria andCrtAddIsNotNull() {
			addCriterion("f_crt_add is not null");
			return this;
		}
		public Criteria andCrtAddEqualTo(Integer value) {
			addCriterion("f_crt_add =", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddNotEqualTo(Integer value) {
			addCriterion("f_crt_add <>", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddGreaterThan(Integer value) {
			addCriterion("f_crt_add >", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_crt_add >=", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddLessThan(Integer value) {
			addCriterion("f_crt_add <", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddLessThanOrEqualTo(Integer value) {
			addCriterion("f_crt_add <=", value, "crtAdd");
			return this;
		}
		public Criteria andCrtAddIn(List values) {
			addCriterion("f_crt_add in", values, "crtAdd");
			return this;
		}
		public Criteria andCrtAddNotIn(List values) {
			addCriterion("f_crt_add not in", values, "crtAdd");
			return this;
		}
		public Criteria andCrtAddBetween(Integer value1, Integer value2) {
			addCriterion("f_crt_add between", value1, value2, "crtAdd");
			return this;
		}
		public Criteria andCrtAddNotBetween(Integer value1, Integer value2) {
			addCriterion("f_crt_add not between", value1, value2, "crtAdd");
			return this;
		}
		public Criteria andNeedZhenqiIsNull() {
			addCriterion("f_need_zhenqi is null");
			return this;
		}
		public Criteria andNeedZhenqiIsNotNull() {
			addCriterion("f_need_zhenqi is not null");
			return this;
		}
		public Criteria andNeedZhenqiEqualTo(Integer value) {
			addCriterion("f_need_zhenqi =", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiNotEqualTo(Integer value) {
			addCriterion("f_need_zhenqi <>", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiGreaterThan(Integer value) {
			addCriterion("f_need_zhenqi >", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_need_zhenqi >=", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiLessThan(Integer value) {
			addCriterion("f_need_zhenqi <", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiLessThanOrEqualTo(Integer value) {
			addCriterion("f_need_zhenqi <=", value, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiIn(List values) {
			addCriterion("f_need_zhenqi in", values, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiNotIn(List values) {
			addCriterion("f_need_zhenqi not in", values, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiBetween(Integer value1, Integer value2) {
			addCriterion("f_need_zhenqi between", value1, value2, "needZhenqi");
			return this;
		}
		public Criteria andNeedZhenqiNotBetween(Integer value1, Integer value2) {
			addCriterion("f_need_zhenqi not between", value1, value2, "needZhenqi");
			return this;
		}
		public Criteria andOddsIsNull() {
			addCriterion("f_odds is null");
			return this;
		}
		public Criteria andOddsIsNotNull() {
			addCriterion("f_odds is not null");
			return this;
		}
		public Criteria andOddsEqualTo(Integer value) {
			addCriterion("f_odds =", value, "odds");
			return this;
		}
		public Criteria andOddsNotEqualTo(Integer value) {
			addCriterion("f_odds <>", value, "odds");
			return this;
		}
		public Criteria andOddsGreaterThan(Integer value) {
			addCriterion("f_odds >", value, "odds");
			return this;
		}
		public Criteria andOddsGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_odds >=", value, "odds");
			return this;
		}
		public Criteria andOddsLessThan(Integer value) {
			addCriterion("f_odds <", value, "odds");
			return this;
		}
		public Criteria andOddsLessThanOrEqualTo(Integer value) {
			addCriterion("f_odds <=", value, "odds");
			return this;
		}
		public Criteria andOddsIn(List values) {
			addCriterion("f_odds in", values, "odds");
			return this;
		}
		public Criteria andOddsNotIn(List values) {
			addCriterion("f_odds not in", values, "odds");
			return this;
		}
		public Criteria andOddsBetween(Integer value1, Integer value2) {
			addCriterion("f_odds between", value1, value2, "odds");
			return this;
		}
		public Criteria andOddsNotBetween(Integer value1, Integer value2) {
			addCriterion("f_odds not between", value1, value2, "odds");
			return this;
		}
		public Criteria andNameI18nIsNull() {
			addCriterion("f_name_i18n is null");
			return this;
		}
		public Criteria andNameI18nIsNotNull() {
			addCriterion("f_name_i18n is not null");
			return this;
		}
		public Criteria andNameI18nEqualTo(String value) {
			addCriterion("f_name_i18n =", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotEqualTo(String value) {
			addCriterion("f_name_i18n <>", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThan(String value) {
			addCriterion("f_name_i18n >", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nGreaterThanOrEqualTo(String value) {
			addCriterion("f_name_i18n >=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThan(String value) {
			addCriterion("f_name_i18n <", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLessThanOrEqualTo(String value) {
			addCriterion("f_name_i18n <=", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nLike(String value) {
			addCriterion("f_name_i18n like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotLike(String value) {
			addCriterion("f_name_i18n not like", value, "nameI18n");
			return this;
		}
		public Criteria andNameI18nIn(List values) {
			addCriterion("f_name_i18n in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotIn(List values) {
			addCriterion("f_name_i18n not in", values, "nameI18n");
			return this;
		}
		public Criteria andNameI18nBetween(String value1, String value2) {
			addCriterion("f_name_i18n between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andNameI18nNotBetween(String value1, String value2) {
			addCriterion("f_name_i18n not between", value1, value2, "nameI18n");
			return this;
		}
		public Criteria andDebuffIdIsNull() {
			addCriterion("f_debuff_id is null");
			return this;
		}
		public Criteria andDebuffIdIsNotNull() {
			addCriterion("f_debuff_id is not null");
			return this;
		}
		public Criteria andDebuffIdEqualTo(Integer value) {
			addCriterion("f_debuff_id =", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdNotEqualTo(Integer value) {
			addCriterion("f_debuff_id <>", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdGreaterThan(Integer value) {
			addCriterion("f_debuff_id >", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdGreaterThanOrEqualTo(Integer value) {
			addCriterion("f_debuff_id >=", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdLessThan(Integer value) {
			addCriterion("f_debuff_id <", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdLessThanOrEqualTo(Integer value) {
			addCriterion("f_debuff_id <=", value, "debuffId");
			return this;
		}
		public Criteria andDebuffIdIn(List values) {
			addCriterion("f_debuff_id in", values, "debuffId");
			return this;
		}
		public Criteria andDebuffIdNotIn(List values) {
			addCriterion("f_debuff_id not in", values, "debuffId");
			return this;
		}
		public Criteria andDebuffIdBetween(Integer value1, Integer value2) {
			addCriterion("f_debuff_id between", value1, value2, "debuffId");
			return this;
		}
		public Criteria andDebuffIdNotBetween(Integer value1, Integer value2) {
			addCriterion("f_debuff_id not between", value1, value2, "debuffId");
			return this;
		}
	}
}
