package net.snake.dao.taskdialog;

import java.util.List;

import net.snake.dao.taskdialog.Taskdialog;
import net.snake.dao.taskdialog.TaskdialogExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TaskdialogDAOImpl extends SqlMapClientDaoSupport implements TaskdialogDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public TaskdialogDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int countByExample(TaskdialogExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_task_dialog.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int deleteByExample(TaskdialogExample example) {
		int rows = getSqlMapClientTemplate().delete("t_task_dialog.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Taskdialog key = new Taskdialog();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_task_dialog.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public void insert(Taskdialog record) {
		getSqlMapClientTemplate().insert("t_task_dialog.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public void insertSelective(Taskdialog record) {
		getSqlMapClientTemplate().insert("t_task_dialog.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public List selectByExample(TaskdialogExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_task_dialog.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public Taskdialog selectByPrimaryKey(Integer id) {
		Taskdialog key = new Taskdialog();
		key.setId(id);
		Taskdialog record = (Taskdialog) getSqlMapClientTemplate().queryForObject(
				"t_task_dialog.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int updateByExampleSelective(Taskdialog record, TaskdialogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_task_dialog.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int updateByExample(Taskdialog record, TaskdialogExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_task_dialog.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int updateByPrimaryKeySelective(Taskdialog record) {
		int rows = getSqlMapClientTemplate().update(
				"t_task_dialog.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	public int updateByPrimaryKey(Taskdialog record) {
		int rows = getSqlMapClientTemplate()
				.update("t_task_dialog.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	private static class UpdateByExampleParms extends TaskdialogExample {
		private Object record;
		public UpdateByExampleParms(Object record, TaskdialogExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
