package net.snake.dao.goodsdc;

import java.util.List;

import net.snake.dao.goodsdc.Goodsdc;
import net.snake.dao.goodsdc.GoodsdcExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodsdcDAOImpl extends SqlMapClientDaoSupport implements GoodsdcDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public GoodsdcDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int countByExample(GoodsdcExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_goods_dc.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int deleteByExample(GoodsdcExample example) {
		int rows = getSqlMapClientTemplate().delete("t_goods_dc.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Goodsdc key = new Goodsdc();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_goods_dc.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public void insert(Goodsdc record) {
		getSqlMapClientTemplate().insert("t_goods_dc.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public void insertSelective(Goodsdc record) {
		getSqlMapClientTemplate().insert("t_goods_dc.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public List selectByExample(GoodsdcExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_goods_dc.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public Goodsdc selectByPrimaryKey(Integer id) {
		Goodsdc key = new Goodsdc();
		key.setId(id);
		Goodsdc record = (Goodsdc) getSqlMapClientTemplate().queryForObject(
				"t_goods_dc.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int updateByExampleSelective(Goodsdc record, GoodsdcExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_goods_dc.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int updateByExample(Goodsdc record, GoodsdcExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_goods_dc.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int updateByPrimaryKeySelective(Goodsdc record) {
		int rows = getSqlMapClientTemplate().update("t_goods_dc.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	public int updateByPrimaryKey(Goodsdc record) {
		int rows = getSqlMapClientTemplate().update("t_goods_dc.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_goods_dc
	 * @ibatorgenerated  Thu May 05 17:53:42 CST 2011
	 */
	private static class UpdateByExampleParms extends GoodsdcExample {
		private Object record;
		public UpdateByExampleParms(Object record, GoodsdcExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
