package net.snake.dao.taskdialog;

import java.util.List;

import net.snake.dao.taskdialog.Taskdialog;
import net.snake.dao.taskdialog.TaskdialogExample;

public interface TaskdialogDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int countByExample(TaskdialogExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int deleteByExample(TaskdialogExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	void insert(Taskdialog record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	void insertSelective(Taskdialog record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	List selectByExample(TaskdialogExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	Taskdialog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int updateByExampleSelective(Taskdialog record, TaskdialogExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int updateByExample(Taskdialog record, TaskdialogExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int updateByPrimaryKeySelective(Taskdialog record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task_dialog
	 * @ibatorgenerated  Sat May 07 11:41:05 CST 2011
	 */
	int updateByPrimaryKey(Taskdialog record);
}
