package net.snake.dao.lianti;

import java.util.List;

import net.snake.dao.lianti.Lianti;
import net.snake.dao.lianti.LiantiExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LiantiDAOImpl extends SqlMapClientDaoSupport implements LiantiDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public LiantiDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int countByExample(LiantiExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_lianti.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int deleteByExample(LiantiExample example) {
		int rows = getSqlMapClientTemplate().delete("t_lianti.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Lianti key = new Lianti();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_lianti.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public void insert(Lianti record) {
		getSqlMapClientTemplate().insert("t_lianti.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public void insertSelective(Lianti record) {
		getSqlMapClientTemplate().insert("t_lianti.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public List selectByExample(LiantiExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList("t_lianti.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public Lianti selectByPrimaryKey(Integer id) {
		Lianti key = new Lianti();
		key.setId(id);
		Lianti record = (Lianti) getSqlMapClientTemplate().queryForObject(
				"t_lianti.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int updateByExampleSelective(Lianti record, LiantiExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_lianti.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int updateByExample(Lianti record, LiantiExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_lianti.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int updateByPrimaryKeySelective(Lianti record) {
		int rows = getSqlMapClientTemplate().update("t_lianti.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	public int updateByPrimaryKey(Lianti record) {
		int rows = getSqlMapClientTemplate().update("t_lianti.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_lianti
	 * @ibatorgenerated  Sat May 07 12:35:40 CST 2011
	 */
	private static class UpdateByExampleParms extends LiantiExample {
		private Object record;
		public UpdateByExampleParms(Object record, LiantiExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
