package net.snake.dao.goodmodelv2;

import java.util.List;

import net.snake.dao.goodmodelv2.GoodModelV2;
import net.snake.dao.goodmodelv2.GoodModelV2Example;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class GoodModelV2DAOImpl extends SqlMapClientDaoSupport implements GoodModelV2DAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public GoodModelV2DAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int countByExample(GoodModelV2Example example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_goodmodel.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int deleteByExample(GoodModelV2Example example) {
		int rows = getSqlMapClientTemplate().delete("t_goodmodel.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		GoodModelV2 key = new GoodModelV2();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_goodmodel.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public void insert(GoodModelV2 record) {
		getSqlMapClientTemplate().insert("t_goodmodel.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public void insertSelective(GoodModelV2 record) {
		getSqlMapClientTemplate().insert("t_goodmodel.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public List selectByExample(GoodModelV2Example example) {
		List list = getSqlMapClientTemplate().queryForList("t_goodmodel.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public GoodModelV2 selectByPrimaryKey(Integer id) {
		GoodModelV2 key = new GoodModelV2();
		key.setId(id);
		GoodModelV2 record = (GoodModelV2) getSqlMapClientTemplate().queryForObject(
				"t_goodmodel.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int updateByExampleSelective(GoodModelV2 record, GoodModelV2Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_goodmodel.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int updateByExample(GoodModelV2 record, GoodModelV2Example example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_goodmodel.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int updateByPrimaryKeySelective(GoodModelV2 record) {
		int rows = getSqlMapClientTemplate().update("t_goodmodel.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	public int updateByPrimaryKey(GoodModelV2 record) {
		int rows = getSqlMapClientTemplate().update("t_goodmodel.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_goodmodel
	 * @ibatorgenerated  Fri Jul 22 14:21:48 CST 2011
	 */
	private static class UpdateByExampleParms extends GoodModelV2Example {
		private Object record;
		public UpdateByExampleParms(Object record, GoodModelV2Example example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
