package net.snake.dao.dgwd;

import java.util.List;

import net.snake.dao.dgwd.Dgwd;
import net.snake.dao.dgwd.DgwdExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class DgwdDAOImpl extends SqlMapClientDaoSupport implements DgwdDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public DgwdDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int countByExample(DgwdExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_dgwd.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int deleteByExample(DgwdExample example) {
		int rows = getSqlMapClientTemplate().delete("t_dgwd.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int deleteByPrimaryKey(Integer id) {
		Dgwd key = new Dgwd();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_dgwd.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public void insert(Dgwd record) {
		getSqlMapClientTemplate().insert("t_dgwd.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public void insertSelective(Dgwd record) {
		getSqlMapClientTemplate().insert("t_dgwd.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public List selectByExample(DgwdExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_dgwd.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public Dgwd selectByPrimaryKey(Integer id) {
		Dgwd key = new Dgwd();
		key.setId(id);
		Dgwd record = (Dgwd) getSqlMapClientTemplate().queryForObject(
				"t_dgwd.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int updateByExampleSelective(Dgwd record, DgwdExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_dgwd.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int updateByExample(Dgwd record, DgwdExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_dgwd.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int updateByPrimaryKeySelective(Dgwd record) {
		int rows = getSqlMapClientTemplate().update("t_dgwd.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_dgwd
	 */
	public int updateByPrimaryKey(Dgwd record) {
		int rows = getSqlMapClientTemplate().update("t_dgwd.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_dgwd
	 */
	private static class UpdateByExampleParms extends DgwdExample {
		private Object record;
		public UpdateByExampleParms(Object record, DgwdExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
