package net.snake.dao.channel.channelrealdragon;

import java.util.List;

import net.snake.dao.channel.channelrealdragon.ChannelRealdragon;
import net.snake.dao.channel.channelrealdragon.ChannelRealdragonExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ChannelRealdragonDAOImpl extends SqlMapClientDaoSupport implements ChannelRealdragonDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public ChannelRealdragonDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int countByExample(ChannelRealdragonExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_channel_realdragon.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int deleteByExample(ChannelRealdragonExample example) {
        int rows = getSqlMapClientTemplate().delete("t_channel_realdragon.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int deleteByPrimaryKey(Integer id) {
        ChannelRealdragon key = new ChannelRealdragon();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_channel_realdragon.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public void insert(ChannelRealdragon record) {
        getSqlMapClientTemplate().insert("t_channel_realdragon.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public void insertSelective(ChannelRealdragon record) {
        getSqlMapClientTemplate().insert("t_channel_realdragon.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public List selectByExample(ChannelRealdragonExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_channel_realdragon.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public ChannelRealdragon selectByPrimaryKey(Integer id) {
        ChannelRealdragon key = new ChannelRealdragon();
        key.setId(id);
        ChannelRealdragon record = (ChannelRealdragon) getSqlMapClientTemplate().queryForObject("t_channel_realdragon.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int updateByExampleSelective(ChannelRealdragon record, ChannelRealdragonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_channel_realdragon.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int updateByExample(ChannelRealdragon record, ChannelRealdragonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_channel_realdragon.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int updateByPrimaryKeySelective(ChannelRealdragon record) {
        int rows = getSqlMapClientTemplate().update("t_channel_realdragon.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_channel_realdragon
     *
     */
    public int updateByPrimaryKey(ChannelRealdragon record) {
        int rows = getSqlMapClientTemplate().update("t_channel_realdragon.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_channel_realdragon
     *
     */
    private static class UpdateByExampleParms extends ChannelRealdragonExample {
        private Object record;

        public UpdateByExampleParms(Object record, ChannelRealdragonExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
