package net.snake.dao.avatar;

import java.util.List;


import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import net.snake.dao.avatar.Avatar;
import net.snake.dao.avatar.AvatarExample;

public class AvatarDAOImpl extends SqlMapClientDaoSupport implements AvatarDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public AvatarDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int countByExample(AvatarExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_avatar.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int deleteByExample(AvatarExample example) {
		int rows = getSqlMapClientTemplate().delete("t_avatar.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int deleteByPrimaryKey(Integer id) {
		Avatar key = new Avatar();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_avatar.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public void insert(Avatar record) {
		getSqlMapClientTemplate().insert("t_avatar.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public void insertSelective(Avatar record) {
		getSqlMapClientTemplate().insert("t_avatar.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public List selectByExample(AvatarExample example) {
		List list = getSqlMapClientTemplate()
				.queryForList("t_avatar.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public Avatar selectByPrimaryKey(Integer id) {
		Avatar key = new Avatar();
		key.setId(id);
		Avatar record = (Avatar) getSqlMapClientTemplate().queryForObject(
				"t_avatar.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int updateByExampleSelective(Avatar record, AvatarExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate()
				.update("t_avatar.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int updateByExample(Avatar record, AvatarExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_avatar.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int updateByPrimaryKeySelective(Avatar record) {
		int rows = getSqlMapClientTemplate().update("t_avatar.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_avatar
	 */
	public int updateByPrimaryKey(Avatar record) {
		int rows = getSqlMapClientTemplate().update("t_avatar.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_avatar
	 */
	private static class UpdateByExampleParms extends AvatarExample {
		private Object record;
		public UpdateByExampleParms(Object record, AvatarExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Avatar> getAvatar_avatar() {
		 List list = getSqlMapClientTemplate().queryForList("t_avatar.selectlianhechaxun_avatar2");
	        return list;
	}

	@Override
	public List<Avatar> getAvatar_avatarByid(Avatar avatar) {
		return getSqlMapClientTemplate().queryForList("t_avatar.selectlianhechaxun_avatarid",avatar);
	}

	
}
