package net.snake.dao.sceneMonster;

import java.util.List;

import net.snake.dao.sceneMonster.SceneMonster;
import net.snake.dao.sceneMonster.SceneMonsterExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SceneMonsterDAOImpl extends SqlMapClientDaoSupport implements SceneMonsterDAO {

    /**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public SceneMonsterDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int countByExample(SceneMonsterExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_scene_monster.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int deleteByExample(SceneMonsterExample example) {
		int rows = getSqlMapClientTemplate()
				.delete("t_scene_monster.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		SceneMonster key = new SceneMonster();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_scene_monster.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public void insert(SceneMonster record) {
		getSqlMapClientTemplate().insert("t_scene_monster.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public void insertSelective(SceneMonster record) {
		getSqlMapClientTemplate().insert("t_scene_monster.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public List selectByExample(SceneMonsterExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_scene_monster.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public SceneMonster selectByPrimaryKey(Integer id) {
		SceneMonster key = new SceneMonster();
		key.setId(id);
		SceneMonster record = (SceneMonster) getSqlMapClientTemplate().queryForObject(
				"t_scene_monster.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int updateByExampleSelective(SceneMonster record, SceneMonsterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_scene_monster.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int updateByExample(SceneMonster record, SceneMonsterExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_scene_monster.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int updateByPrimaryKeySelective(SceneMonster record) {
		int rows = getSqlMapClientTemplate().update(
				"t_scene_monster.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	public int updateByPrimaryKey(SceneMonster record) {
		int rows = getSqlMapClientTemplate().update("t_scene_monster.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_scene_monster
	 * @ibatorgenerated  Thu Jun 09 15:59:17 CST 2011
	 */
	private static class UpdateByExampleParms extends SceneMonsterExample {
		private Object record;
		public UpdateByExampleParms(Object record, SceneMonsterExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<SceneMonster> selectSceneMonsters() {
		return getSqlMapClientTemplate().queryForList("t_scene_monster.getGuoLvChongfu");
	}
}
