package net.snake.dao.task;

import java.util.List;

import net.snake.dao.task.Task;
import net.snake.dao.task.TaskExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TaskDAOImpl extends SqlMapClientDaoSupport implements TaskDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public TaskDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int countByExample(TaskExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_task.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int deleteByExample(TaskExample example) {
		int rows = getSqlMapClientTemplate().delete("t_task.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		Task key = new Task();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_task.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public void insert(Task record) {
		getSqlMapClientTemplate().insert("t_task.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public void insertSelective(Task record) {
		getSqlMapClientTemplate().insert("t_task.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public List selectByExample(TaskExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_task.ibatorgenerated_selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public Task selectByPrimaryKey(Integer id) {
		Task key = new Task();
		key.setId(id);
		Task record = (Task) getSqlMapClientTemplate().queryForObject(
				"t_task.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int updateByExampleSelective(Task record, TaskExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_task.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int updateByExample(Task record, TaskExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_task.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int updateByPrimaryKeySelective(Task record) {
		int rows = getSqlMapClientTemplate().update("t_task.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	public int updateByPrimaryKey(Task record) {
		int rows = getSqlMapClientTemplate().update("t_task.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_task
	 * @ibatorgenerated  Fri May 06 17:25:38 CST 2011
	 */
	private static class UpdateByExampleParms extends TaskExample {
		private Object record;
		public UpdateByExampleParms(Object record, TaskExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
