package net.snake.dao.hiddenweapons;

import java.util.List;

import net.snake.dao.hiddenweapons.HiddenWeapons;
import net.snake.dao.hiddenweapons.HiddenWeaponsExample;

public interface HiddenWeaponsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int countByExample(HiddenWeaponsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int deleteByExample(HiddenWeaponsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	void insert(HiddenWeapons record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	void insertSelective(HiddenWeapons record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	List selectByExample(HiddenWeaponsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	HiddenWeapons selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int updateByExampleSelective(HiddenWeapons record, HiddenWeaponsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int updateByExample(HiddenWeapons record, HiddenWeaponsExample example);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int updateByPrimaryKeySelective(HiddenWeapons record);

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	int updateByPrimaryKey(HiddenWeapons record);
}
