package net.snake.dao.hiddenweapons;

import java.util.List;

import net.snake.dao.hiddenweapons.HiddenWeapons;
import net.snake.dao.hiddenweapons.HiddenWeaponsExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HiddenWeaponsDAOImpl extends SqlMapClientDaoSupport implements HiddenWeaponsDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public HiddenWeaponsDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int countByExample(HiddenWeaponsExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_hidden_weapons.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int deleteByExample(HiddenWeaponsExample example) {
		int rows = getSqlMapClientTemplate().delete("t_hidden_weapons.ibatorgenerated_deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int deleteByPrimaryKey(Integer id) {
		HiddenWeapons key = new HiddenWeapons();
		key.setId(id);
		int rows = getSqlMapClientTemplate()
				.delete("t_hidden_weapons.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public void insert(HiddenWeapons record) {
		getSqlMapClientTemplate().insert("t_hidden_weapons.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public void insertSelective(HiddenWeapons record) {
		getSqlMapClientTemplate().insert("t_hidden_weapons.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public List selectByExample(HiddenWeaponsExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_hidden_weapons.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public HiddenWeapons selectByPrimaryKey(Integer id) {
		HiddenWeapons key = new HiddenWeapons();
		key.setId(id);
		HiddenWeapons record = (HiddenWeapons) getSqlMapClientTemplate().queryForObject(
				"t_hidden_weapons.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int updateByExampleSelective(HiddenWeapons record, HiddenWeaponsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"t_hidden_weapons.ibatorgenerated_updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int updateByExample(HiddenWeapons record, HiddenWeaponsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_hidden_weapons.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int updateByPrimaryKeySelective(HiddenWeapons record) {
		int rows = getSqlMapClientTemplate().update(
				"t_hidden_weapons.ibatorgenerated_updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	public int updateByPrimaryKey(HiddenWeapons record) {
		int rows = getSqlMapClientTemplate().update("t_hidden_weapons.ibatorgenerated_updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_hidden_weapons
	 * @ibatorgenerated  Sat May 07 11:47:57 CST 2011
	 */
	private static class UpdateByExampleParms extends HiddenWeaponsExample {
		private Object record;
		public UpdateByExampleParms(Object record, HiddenWeaponsExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
