package net.snake.dao.instance;

import java.util.List;

import net.snake.dao.instance.Instance;
import net.snake.dao.instance.InstanceExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class InstanceDAOImpl extends SqlMapClientDaoSupport implements InstanceDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public InstanceDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int countByExample(InstanceExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_instance.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int deleteByExample(InstanceExample example) {
		int rows = getSqlMapClientTemplate().delete("t_instance.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int deleteByPrimaryKey(Integer instanceModelId) {
		Instance key = new Instance();
		key.setInstanceModelId(instanceModelId);
		int rows = getSqlMapClientTemplate().delete("t_instance.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public void insert(Instance record) {
		getSqlMapClientTemplate().insert("t_instance.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public void insertSelective(Instance record) {
		getSqlMapClientTemplate().insert("t_instance.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public List selectByExample(InstanceExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_instance.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public Instance selectByPrimaryKey(Integer instanceModelId) {
		Instance key = new Instance();
		key.setInstanceModelId(instanceModelId);
		Instance record = (Instance) getSqlMapClientTemplate().queryForObject(
				"t_instance.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int updateByExampleSelective(Instance record, InstanceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_instance.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int updateByExample(Instance record, InstanceExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_instance.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int updateByPrimaryKeySelective(Instance record) {
		int rows = getSqlMapClientTemplate().update("t_instance.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	public int updateByPrimaryKey(Instance record) {
		int rows = getSqlMapClientTemplate().update("t_instance.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_instance
	 * @ibatorgenerated  Sat May 07 12:35:27 CST 2011
	 */
	private static class UpdateByExampleParms extends InstanceExample {
		private Object record;
		public UpdateByExampleParms(Object record, InstanceExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}
}
