package net.snake.dao.achieve;

import java.util.List;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

import net.snake.dao.achieve.Achieve;
import net.snake.dao.achieve.AchieveExample;

public class AchieveDAOImpl extends SqlMapClientDaoSupport implements AchieveDAO {

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public AchieveDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int countByExample(AchieveExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"t_achieve.ibatorgenerated_countByExample", example);
		return count.intValue();
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int deleteByExample(AchieveExample example) {
		int rows = getSqlMapClientTemplate().delete("t_achieve.ibatorgenerated_deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int deleteByPrimaryKey(Integer id) {
		Achieve key = new Achieve();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("t_achieve.ibatorgenerated_deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public void insert(Achieve record) {
		getSqlMapClientTemplate().insert("t_achieve.ibatorgenerated_insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public void insertSelective(Achieve record) {
		getSqlMapClientTemplate().insert("t_achieve.ibatorgenerated_insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public List selectByExample(AchieveExample example) {
		List list = getSqlMapClientTemplate().queryForList("t_achieve.ibatorgenerated_selectByExample",
				example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public Achieve selectByPrimaryKey(Integer id) {
		Achieve key = new Achieve();
		key.setId(id);
		Achieve record = (Achieve) getSqlMapClientTemplate().queryForObject(
				"t_achieve.ibatorgenerated_selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int updateByExampleSelective(Achieve record, AchieveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_achieve.ibatorgenerated_updateByExampleSelective",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int updateByExample(Achieve record, AchieveExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("t_achieve.ibatorgenerated_updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int updateByPrimaryKeySelective(Achieve record) {
		int rows = getSqlMapClientTemplate().update("t_achieve.ibatorgenerated_updateByPrimaryKeySelective",
				record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS ibator. This method corresponds to the database table t_achieve
	 */
	public int updateByPrimaryKey(Achieve record) {
		int rows = getSqlMapClientTemplate().update("t_achieve.ibatorgenerated_updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS ibator. This class corresponds to the database table t_achieve
	 */
	private static class UpdateByExampleParms extends AchieveExample {
		private Object record;
		public UpdateByExampleParms(Object record, AchieveExample example) {
			super(example);
			this.record = record;
		}
		public Object getRecord() {
			return record;
		}
	}

	@Override
	public List<Object> getSelectTable(String Table) {
		return (List<Object>) getSqlMapClientTemplate().queryForList(Table);
	}
}
