package net.snake.dao.totem;

import java.util.List;

import net.snake.dao.totem.Totem;
import net.snake.dao.totem.TotemExample;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class TotemDAOImpl extends SqlMapClientDaoSupport implements TotemDAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public TotemDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int countByExample(TotemExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_totem.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int deleteByExample(TotemExample example) {
        int rows = getSqlMapClientTemplate().delete("t_totem.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int deleteByPrimaryKey(Integer id) {
        Totem key = new Totem();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("t_totem.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public void insert(Totem record) {
        getSqlMapClientTemplate().insert("t_totem.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public void insertSelective(Totem record) {
        getSqlMapClientTemplate().insert("t_totem.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public List selectByExample(TotemExample example) {
        List list = getSqlMapClientTemplate().queryForList("t_totem.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public Totem selectByPrimaryKey(Integer id) {
        Totem key = new Totem();
        key.setId(id);
        Totem record = (Totem) getSqlMapClientTemplate().queryForObject("t_totem.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int updateByExampleSelective(Totem record, TotemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_totem.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int updateByExample(Totem record, TotemExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_totem.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int updateByPrimaryKeySelective(Totem record) {
        int rows = getSqlMapClientTemplate().update("t_totem.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    public int updateByPrimaryKey(Totem record) {
        int rows = getSqlMapClientTemplate().update("t_totem.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_totem
     *
     * @ibatorgenerated Wed Apr 06 16:29:12 CST 2011
     */
    private static class UpdateByExampleParms extends TotemExample {
        private Object record;

        public UpdateByExampleParms(Object record, TotemExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
