package net.snake.dao.transport2;

import java.util.List;

import net.snake.dao.transport2.Transport2;
import net.snake.dao.transport2.Transport2Example;

import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class Transport2DAOImpl extends SqlMapClientDaoSupport implements Transport2DAO {

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public Transport2DAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int countByExample(Transport2Example example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("t_transport2.ibatorgenerated_countByExample", example);
        return count.intValue();
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int deleteByExample(Transport2Example example) {
        int rows = getSqlMapClientTemplate().delete("t_transport2.ibatorgenerated_deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int deleteByPrimaryKey(Integer transportId) {
        Transport2 key = new Transport2();
        key.setTransportId(transportId);
        int rows = getSqlMapClientTemplate().delete("t_transport2.ibatorgenerated_deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public void insert(Transport2 record) {
        getSqlMapClientTemplate().insert("t_transport2.ibatorgenerated_insert", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public void insertSelective(Transport2 record) {
        getSqlMapClientTemplate().insert("t_transport2.ibatorgenerated_insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public List selectByExample(Transport2Example example) {
        List list = getSqlMapClientTemplate().queryForList("t_transport2.ibatorgenerated_selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public Transport2 selectByPrimaryKey(Integer transportId) {
        Transport2 key = new Transport2();
        key.setTransportId(transportId);
        Transport2 record = (Transport2) getSqlMapClientTemplate().queryForObject("t_transport2.ibatorgenerated_selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int updateByExampleSelective(Transport2 record, Transport2Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_transport2.ibatorgenerated_updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int updateByExample(Transport2 record, Transport2Example example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("t_transport2.ibatorgenerated_updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int updateByPrimaryKeySelective(Transport2 record) {
        int rows = getSqlMapClientTemplate().update("t_transport2.ibatorgenerated_updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS ibator.
     * This method corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    public int updateByPrimaryKey(Transport2 record) {
        int rows = getSqlMapClientTemplate().update("t_transport2.ibatorgenerated_updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS ibator.
     * This class corresponds to the database table t_transport2
     *
     * @ibatorgenerated Mon Oct 18 10:34:31 GMT 2010
     */
    private static class UpdateByExampleParms extends Transport2Example {
        private Object record;

        public UpdateByExampleParms(Object record, Transport2Example example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}
